/*
   FEEL p2  MAKE FORTRAN LIBRARY   p_msbicg_stab
 */

#include <stdio.h>
#include "../feel_def/feel_def.h"
#include "../system/system.h"

#define FNAME "p_msbicg_stab.f"
lib_p_msbicg_stab()
{
   FILE *fp;
   StoreMakefile(FNAME,SYSTEM_LIBRARY);
   if(LIMIT_FILE == 1) return;
   fp = OpenFileToWrite( FNAME );
   F77("      subroutine p_msbicg_stab (rank,npesum,U,B,neq_sub,naisum,\n");
   F77("     $     naieq,ninner,nintotal,IT,A,JA,MJ,w,eps,IPM,\n");
   F77("     $     srb,nsrequ,nsendnum,nrecvnum,\n");
   F77("     $     nsesum,nresum,rnorm,nsendlist,nrecvlist,\n");
   F77("     $     nsendkaz,nrecvkaz,nsendtable,nrecvtable,\n");
   F77("     $     JDP,KTI,feelpara)\n");
   F77("* \n");
   F77("c---------------------------------------------------\n");
   F77("c     Scaled BiCGSTAB method (two dimensinal array)\n");
   F77("c---------------------------------------------------\n");
   F77("*\n");
   F77("      implicit real*8 (a-h,o-z)\n");
   F77("      include 'mpi.incl'\n");
   F77("c\n");
   F77("      integer rank\n");
   F77("*\n");
   F77("      real*4 feelpara(*)\n");
   F77("*\n");
   F77("      dimension nsendlist(npesum),nrecvlist(npesum)\n");
   F77("      dimension nsendkaz(npesum),nrecvkaz(npesum)\n");
   F77("      dimension nsendtable(npesum),nrecvtable(npesum)      \n");
   F77("c     \n");
   F77("      dimension IPM(2)\n");
   F77("c\n");
   F77("      dimension B(neq_sub)\n");
   F77("*\n");
   F77("      dimension w(neq_sub,8)\n");
   F77("*\n");
   F77("      dimension naieq(naisum)\n");
   F77("*\n");
   F77("      dimension ninner(*)\n");
   F77("*\n");
   F77("      dimension A(neq_sub,MJ),JA(neq_sub,MJ)\n");
   F77("      dimension U(neq_sub)\n");
   F77("*\n");
   F77("*     ---- send_buffer(srb(i),i=1,nsesum) & \n");
   F77("*     receive buffer(srb(i),i=nsesum+1,nsesum+nresum) ----\n");
   F77("      dimension srb(nsesum+nresum)\n");
   F77("*\n");
   F77("      dimension nsrequ(nsesum+nresum)\n");
   F77("*\n");
   F77("c---------------------------------------\n");
   F77("c   Set the value 'KTI'\n");
   F77("c---------------------------------------\n");
   F77("      KTI = IT\n");
   F77("c\n");
   F77("c-----------------------------------------------\n");
   F77("c     Calculation of \"JL,JR\"\n");
   F77("c                 JL : bandwidth of lower part\n");
   F77("c                 JR : bandwidth of upper part\n");
   F77("c-----------------------------------------------\n");
   F77("      call f_alloc (np_il,'solve_il',neq_sub,0,0)\n");
   F77("      call f_alloc (np_ir,'solve_ir',neq_sub,0,0)\n");
   F77("c\n");
   F77("      call p_get_band (feelpara(np_il),feelpara(np_ir),neq_sub,\n");
   F77("     $     A,JA,MJ,JDP,JL,JR)\n");
   F77("c\n");
   F77("c--------------------------------------\n");
   F77("c     Initialization of w(*,8) ( = 0)\n");
   F77("c--------------------------------\n");
   F77("      do 610 i=1,8\n");
   F77("         do 620 j=1,neq_sub\n");
   F77("            w(j,i)=0.d0\n");
   F77(" 620     continue\n");
   F77(" 610  continue      \n");
   F77("c\n");
   F77("c------------------------------------\n");
   F77("*     Bi-CGSTAB method\n");
   F77("c-------------------------------------------------------\n");
   F77("c     Calculation of L^(2) norm of the right hand vector\n");
   F77("c-------------------------------------------------------\n");
   F77("c     \n");
   F77("      bsahen=0.d0\n");
   F77("      bsahenint=0.d0\n");
   F77("      bsahennai=0.d0\n");
   F77("      do 300 i=1,naisum\n");
   F77("         bsahennai=bsahennai+B(naieq(i))*B(naieq(i))\n");
   F77(" 300  continue\n");
   F77("*\n");
   F77("      if (nrecvlist(rank+1).eq.1) then\n");
   F77("         do 310 i=1,nintotal\n");
   F77("            bsahenint=bsahenint+B(ninner(i))*B(ninner(i))\n");
   F77(" 310     continue\n");
   F77("      end if\n");
   F77("      bsahen=bsahenint+bsahennai\n");
   F77("*\n");
   F77("*c\n");
   F77("*c\n");
   F77("      call mpi_allreduce(bsahen,bsahen,1,\n");
   F77("     $     mpi_double_precision,mpi_sum,mpi_comm_world,\n");
   F77("     $     ierror)               \n");
   F77("*\n");
   F77("*---------------------------\n");
   F77("* check of the right side\n");
   F77("*--------------------------\n");
   F77("*\n");
   F77("*------------------------------------\n");
   F77("*     Get machine epsilon in double precision \n");
   F77("*------------------------------------\n");
   F77("c\n");
   F77("      epsmac=1.d-36\n");
   F77("c\n");
   F77("*\n");
   F77("      if (bsahen.lt.epsmac) then\n");
   F77("         do 500 i=1,neq_sub\n");
   F77("            U(i)=0.d0\n");
   F77(" 500     continue\n");
   F77("      end if\n");
   F77("c\n");
   F77("c-------------------------------------------\n");
   F77("c     Setting of the initial vector U(i)\n");
   F77("c             : U = B * (DIAG(A))^(-1)\n");
   F77("c--------------------------------------------\n");
   F77("c\n");
   F77("c--------------------------------------------     \n");
   F77("c     IPM(1)=0 : Scaled BiCGSTAB method\n");
   F77("c--------------------------------------------\n");
   F77("c\n");
   F77("      if (IPM(1).eq.0) then\n");
   F77("         do 200 i=1,neq_sub\n");
   F77("            w(i,7)=A(i,JDP)\n");
   F77(" 200     continue\n");
   F77("c\n");
   F77("c------------------------------------------------------\n");
   F77("c     summation of the values on the interface\n");
   F77("c------------------------------------------------------\n");
   F77("c\n");
   F77("         call data_plus (rank,neq_sub,w(1,7),srb,\n");
   F77("     $        nsrequ,\n");
   F77("     $        nsendnum,nrecvnum,npesum,\n");
   F77("     $        nsesum,nresum,nsendkaz,nrecvkaz,nsendlist,\n");
   F77("     $        nrecvlist,nsendtable,nrecvtable)\n");
   F77("c\n");
   F77("c-----------------------------------------\n");
   F77("c     check diagonal component of A(*,*) \n");
   F77("c-----------------------------------------\n");
   F77("         do 210 i=1,neq_sub\n");
   F77("            if (dabs(w(i,7)).eq.epsmac) then\n");
   F77("               stop ' diagonal element too small '\n");
   F77("            end if\n");
   F77("            U(i)=B(i)/w(i,7)\n");
   F77(" 210     continue\n");
   F77("      end if\n");
   F77("c\n");
   F77("c------------------------------------\n");
   F77("c   Initialization of w(i,1) ( = 0 )\n");
   F77("c-------------------------------------\n");
   F77("c\n");
   F77("      do 29 i=1,neq_sub\n");
   F77("         w(i,1)=0.d0\n");
   F77(" 29   continue\n");
   F77("c\n");
   F77("c----------------------------------------\n");
   F77("c     w(i,1):residual vector r_k(i)\n");
   F77("c----------------------------------------\n");
   F77("c     Upper Element \n");
   F77("c      \n");
   F77("      do 10 j=1,JL\n");
   F77("         do 20 i=1,neq_sub\n");
   F77("            w(i,1)=w(i,1)+A(i,j)*U(JA(i,j))\n");
   F77(" 20      continue\n");
   F77(" 10   continue\n");
   F77("c\n");
   F77("c--------------------------------------\n");
   F77("c     Diagonal Element\n");
   F77("c--------------------------------------\n");
   F77("c     \n");
   F77("      do 11 i=1,neq_sub\n");
   F77("         w(i,1)=w(i,1)+A(i,JDP)*U(JA(i,JDP))\n");
   F77(" 11   continue\n");
   F77("c\n");
   F77("c-----------------------------------------------\n");
   F77("c    Lower Element\n");
   F77("c-----------------------------------------------\n");
   F77("c\n");
   F77("      do 12 j=JDP+1,JR\n");
   F77("         do 22 i=1,neq_sub\n");
   F77("            w(i,1)=w(i,1)+A(i,j)*U(JA(i,j))\n");
   F77(" 22      continue\n");
   F77(" 12   continue\n");
   F77("c\n");
   F77("c-----------------------------------------------------------\n");
   F77("c Summation of the residual vector 'w(*,1)' on the interface\n");
   F77("c-----------------------------------------------------------\n");
   F77("c\n");
   F77("      call data_plus (rank,neq_sub,w(1,1),srb,\n");
   F77("     $     nsrequ,\n");
   F77("     $     nsendnum,nrecvnum,npesum,\n");
   F77("     $     nsesum,nresum,nsendkaz,nrecvkaz,nsendlist,\n");
   F77("     $     nrecvlist,nsendtable,nrecvtable)\n");
   F77("c\n");
   F77("c--------------------------------------------\n");
   F77("c Initial residual vector ' w(*,8) '\n");
   F77("c--------------------------------------------\n");
   F77("c\n");
   F77("      do 30 i=1,neq_sub\n");
   F77("         w(i,1)=B(i)-w(i,1)\n");
   F77("         w(i,8)=w(i,1)\n");
   F77(" 30   continue\n");
   F77("c\n");
   F77("c------------------------------------\n");
   F77("c     Calculation of inner product \n");
   F77("c------------------------------------\n");
   F77("c    \n");
   F77("c    \n");
   F77("      rnai=0.d0\n");
   F77("      do 40 i=1,naisum\n");
   F77("         rnai=rnai+w(naieq(i),1)*w(naieq(i),1)\n");
   F77(" 40   continue\n");
   F77("c\n");
   F77("c\n");
   F77("      rint=0.d0\n");
   F77("      if (nrecvlist(rank+1).eq.1) then\n");
   F77("         do 50 i=1,nintotal\n");
   F77("            rint=rint+w(ninner(i),1)*w(ninner(i),1)\n");
   F77(" 50      continue\n");
   F77("      end if\n");
   F77("c\n");
   F77("      rtotal=0.d0\n");
   F77("      rtotal=rint+rnai\n");
   F77("c\n");
   F77("      call mpi_reduce(rtotal,rtotal,1,\n");
   F77("     $     mpi_double_precision,mpi_sum,0,mpi_comm_world,\n");
   F77("     $     ierror)\n");
   F77("c\n");
   F77("c---------------------------------------------\n");
   F77("c     Convergence (about the initial vector)\n");
   F77("c---------------------------------------------\n");
   F77("c\n");
   F77("      if (rank.eq.0) then\n");
   F77("         rnorm=rtotal/bsahen\n");
   F77("         if (rnorm.le.eps) then\n");
   F77("            mflg=1\n");
   F77("         else\n");
   F77("            mflg=0\n");
   F77("         end if\n");
   F77("      end if\n");
   F77("c\n");
   F77("      call mpi_bcast(mflg,1,mpi_integer,0,mpi_comm_world,\n");
   F77("     $     ierror)\n");
   F77("c\n");
   F77("      if (mflg.eq.1) return      \n");
   F77("c\n");
   F77("c---------------------------------------------------\n");
   F77("c     Setting of the initial vector \n");
   F77("c                                  :p_k(i)=w(i,2)\n");
   F77("c                                  :A*p_k(i)=w(i,3)\n");
   F77("c---------------------------------------------------\n");
   F77("      do 60 i=1,neq_sub\n");
   F77("         w(i,2)=0.d0\n");
   F77("         w(i,3)=0.d0\n");
   F77(" 60   continue\n");
   F77("*\n");
   F77("      alpha=1.d0\n");
   F77("      omega=1.d0\n");
   F77("c\n");
   F77("c-----------------------------------\n");
   F77("c     rprerotal = (r_0,r_{-1})\n");
   F77("c-----------------------------------\n");
   F77("      rpretotal=1.d0\n");
   F77("c\n");
   F77("      do 100 k=1,IT\n");
   F77("c\n");
   F77("c------------------------------------\n");
   F77("c Calculation of 'beta'\n");
   F77("c-----------------------------------     \n");
   F77("c\n");
   F77("c     \n");
   F77("         if (rank.eq.0) then\n");
   F77("            if (dabs((rpretotal*omega)).le.epsmac) then\n");
   F77("               write (6,*) 'Iteration count,\n");
   F77("     $              (r_0,r_{i-2}),omega_{i-1}',\n");
   F77("     $              k,rpretotal,omega\n");
   F77("               stop '(r_0,r_{i-2})*omega_{i-1} too small'\n");
   F77("            end if\n");
   F77("            beta=(rtotal*alpha)/(rpretotal*omega)\n");
   F77("         end if\n");
   F77("c\n");
   F77("         call mpi_bcast(beta,1,mpi_double_precision,0,\n");
   F77("     $        mpi_comm_world,ierror)\n");
   F77("c\n");
   F77("c\n");
   F77("c     w(i,2)=p_k\n");
   F77("         do 110 i=1,neq_sub\n");
   F77("            w(i,3)=(w(i,1)-beta*omega*w(i,3))/w(i,7)\n");
   F77("            w(i,2)=w(i,3)+beta*w(i,2)\n");
   F77(" 110     continue\n");
   F77("c\n");
   F77("c----------------------------------------\n");
   F77("c  Calculation of 'alpha'\n");
   F77("c----------------------------------------\n");
   F77("c--------------------------\n");
   F77("c     w(i,3)=A*p_k\n");
   F77("c--------------------------\n");
   F77("         do 120 i=1,neq_sub\n");
   F77("            w(i,3)=0.d0\n");
   F77(" 120     continue\n");
   F77("c---------------------------\n");
   F77("c    Upper Element\n");
   F77("c---------------------------\n");
   F77("c    \n");
   F77("         do 130 j=1,JL\n");
   F77("            do 140 i=1,neq_sub\n");
   F77("               w(i,3)=w(i,3)+A(i,j)*w(JA(i,j),2)\n");
   F77(" 140        continue\n");
   F77(" 130     continue\n");
   F77("c----------------------------------\n");
   F77("c    Diagonal Element\n");
   F77("c----------------------------------\n");
   F77("         do 131 i=1,neq_sub\n");
   F77("            w(i,3)=w(i,3)+A(i,JDP)*w(JA(i,JDP),2)\n");
   F77(" 131     continue\n");
   F77("c----------------------------------\n");
   F77("c    Lower Element\n");
   F77("c---------------------------------\n");
   F77("         do 132 j=JDP+1,JR\n");
   F77("            do 142 i=1,neq_sub\n");
   F77("               w(i,3)=w(i,3)+A(i,j)*w(JA(i,j),2)\n");
   F77(" 142        continue\n");
   F77(" 132     continue\n");
   F77("c--------------------------------------\n");
   F77("c Summation of w(*,3) on the interface\n");
   F77("c--------------------------------------\n");
   F77("c     \n");
   F77("         call data_plus (rank,neq_sub,w(1,3),srb,\n");
   F77("     $        nsrequ,\n");
   F77("     $        nsendnum,nrecvnum,npesum,\n");
   F77("     $        nsesum,nresum,nsendkaz,nrecvkaz,nsendlist,\n");
   F77("     $        nrecvlist,nsendtable,nrecvtable)\n");
   F77("c------------------------------------\n");
   F77("c   Calculation of the inner product\n");
   F77("c------------------------------------\n");
   F77("         raseki=0.d0\n");
   F77("c  \n");
   F77("         do 150 i=1,naisum\n");
   F77("            raseki=raseki+w(naieq(i),8)*w(naieq(i),3)\n");
   F77(" 150     continue\n");
   F77("c     \n");
   F77("         riseki=0.d0\n");
   F77("         if (nrecvlist(rank+1).eq.1) then\n");
   F77("            do 160 i=1,nintotal\n");
   F77("               riseki=riseki+w(ninner(i),8)*w(ninner(i),3)\n");
   F77(" 160        continue\n");
   F77("         end if\n");
   F77("         rseki=0.d0\n");
   F77("         rseki=riseki+raseki\n");
   F77("c\n");
   F77("         call mpi_reduce(rseki,rseki,1,\n");
   F77("     $        mpi_double_precision,mpi_sum,0,mpi_comm_world,\n");
   F77("     $        ierror)         \n");
   F77("c\n");
   F77("         if (rank.eq.0) then\n");
   F77("            if (dabs(rseki).le.epsmac) then\n");
   F77("               write (6,*) '(r_0,Ap_i),epsmac',rseki,epsmac\n");
   F77("               write (6,*) ' Iteration count = ',k\n");
   F77("               stop ' (r_0,Ap_i) too small '\n");
   F77("            end if\n");
   F77("            alpha=rtotal/rseki\n");
   F77("            rpretotal=rtotal\n");
   F77("         end if\n");
   F77("c\n");
   F77("         call mpi_bcast(alpha,1,mpi_double_precision,0,\n");
   F77("     $        mpi_comm_world,ierror)\n");
   F77("c\n");
   F77("         do 170 i=1,neq_sub\n");
   F77("            w(i,4)=w(i,1)-alpha*w(i,3)\n");
   F77("            w(i,5)=w(i,4)/w(i,7)\n");
   F77(" 170     continue\n");
   F77("c------------------------------\n");
   F77("c  Calculation of 'omega'\n");
   F77("c------------------------------\n");
   F77("c     w(i,6)=A*s_k\n");
   F77("c------------------------------\n");
   F77("         do 180 i=1,neq_sub\n");
   F77("            w(i,6)=0.d0\n");
   F77(" 180     continue\n");
   F77("c------------------------------\n");
   F77("c Upper Element\n");
   F77("c------------------------------ \n");
   F77("         do 190 j=1,JL\n");
   F77("            do 700 i=1,neq_sub\n");
   F77("               w(i,6)=w(i,6)+A(i,j)*w(JA(i,j),5)\n");
   F77(" 700        continue\n");
   F77(" 190     continue\n");
   F77("c--------------------------------\n");
   F77("c Diagonal Element\n");
   F77("c--------------------------------\n");
   F77("         do 191 i=1,neq_sub\n");
   F77("            w(i,6)=w(i,6)+A(i,JDP)*w(JA(i,JDP),5)\n");
   F77(" 191     continue\n");
   F77("c----------------------------------\n");
   F77("c Lower Element    \n");
   F77("c-----------------------------------\n");
   F77("         do 192 j=JDP+1,JR\n");
   F77("            do 702 i=1,neq_sub\n");
   F77("               w(i,6)=w(i,6)+A(i,j)*w(JA(i,j),5)\n");
   F77(" 702        continue\n");
   F77(" 192     continue\n");
   F77("c---------------------------------------\n");
   F77("c Summation of w(*,6) on the interface\n");
   F77("c---------------------------------------\n");
   F77("c\n");
   F77("         call data_plus (rank,neq_sub,w(1,6),srb,\n");
   F77("     $        nsrequ,\n");
   F77("     $        nsendnum,nrecvnum,npesum,\n");
   F77("     $        nsesum,nresum,nsendkaz,nrecvkaz,nsendlist,\n");
   F77("     $        nrecvlist,nsendtable,nrecvtable)\n");
   F77("c\n");
   F77("         ramseki=0.d0\n");
   F77("         do 710 i=1,naisum\n");
   F77("            ramseki=ramseki+w(naieq(i),6)*w(naieq(i),6)\n");
   F77(" 710     continue\n");
   F77("*\n");
   F77("         rimseki=0.d0\n");
   F77("         if (nrecvlist(rank+1).eq.1) then\n");
   F77("            do 720 i=1,nintotal\n");
   F77("               rimseki=rimseki+w(ninner(i),6)*w(ninner(i),6)\n");
   F77(" 720        continue\n");
   F77("         end if\n");
   F77("*     \n");
   F77("         rmseki=0.d0\n");
   F77("         rmseki=ramseki+rimseki\n");
   F77("c\n");
   F77("         call mpi_reduce(rmseki,rmseki,1,\n");
   F77("     $        mpi_double_precision,mpi_sum,0,mpi_comm_world,\n");
   F77("     $        ierror)         \n");
   F77("c\n");
   F77("         ranseki=0.d0\n");
   F77("         rinseki=0.d0\n");
   F77("         rnseki=0.d0\n");
   F77("         do 730 i=1,naisum\n");
   F77("            ranseki=ranseki+w(naieq(i),4)*w(naieq(i),6)\n");
   F77(" 730     continue\n");
   F77("c\n");
   F77("         if (nrecvlist(rank+1).eq.1) then\n");
   F77("            do 740 i=1,nintotal\n");
   F77("               rinseki=rinseki+w(ninner(i),4)*w(ninner(i),6)\n");
   F77(" 740        continue\n");
   F77("         end if\n");
   F77("c\n");
   F77("         rnseki=rinseki+ranseki\n");
   F77("c     \n");
   F77("         call mpi_reduce(rnseki,rnseki,1,\n");
   F77("     $        mpi_double_precision,mpi_sum,0,mpi_comm_world,\n");
   F77("     $        ierror)         \n");
   F77("c\n");
   F77("         if (rank.eq.0) then\n");
   F77("            if (dabs(rmseki).le.epsmac) then\n");
   F77("               write (6,*) ' ( As_{i},As_{i} ) = ',rmseki\n");
   F77("               stop ' ( As_{i},As_{i} ) too small '\n");
   F77("            end if\n");
   F77("            omega=rnseki/rmseki\n");
   F77("         end if\n");
   F77("c\n");
   F77("         call mpi_bcast(omega,1,mpi_double_precision,0,\n");
   F77("     $        mpi_comm_world,ierror)                  \n");
   F77("c\n");
   F77("         do 750 i=1,neq_sub\n");
   F77("            U(i)=U(i)+alpha*w(i,2)+omega*w(i,5)\n");
   F77("            w(i,1)=w(i,4)-omega*w(i,6)\n");
   F77(" 750     continue\n");
   F77("c--------------------------------------\n");
   F77("c Convergence Criterion \n");
   F77("c-------------------------------------    \n");
   F77("         razan=0.d0\n");
   F77("         rizan=0.d0\n");
   F77("         rzan=0.d0\n");
   F77("         do 760 i=1,naisum\n");
   F77("            razan=razan+w(naieq(i),1)*w(naieq(i),1)\n");
   F77(" 760     continue\n");
   F77("c     \n");
   F77("         if (nrecvlist(rank+1).eq.1) then\n");
   F77("            do 770 i=1,nintotal\n");
   F77("               rizan=rizan+w(ninner(i),1)*w(ninner(i),1)\n");
   F77(" 770        continue\n");
   F77("         end if\n");
   F77("c     \n");
   F77("         rzan=razan+rizan\n");
   F77("c\n");
   F77("         call mpi_reduce(rzan,rzan,1,\n");
   F77("     $        mpi_double_precision,mpi_sum,0,mpi_comm_world,\n");
   F77("     $        ierror)         \n");
   F77("c\n");
   F77("         if (rank.eq.0) then\n");
   F77("            rnorm=rzan/bsahen\n");
   F77("c\n");
   F77("            if (rnorm.le.eps) then\n");
   F77("               nflg=1\n");
   F77("c---------------------------\n");
   F77("c     Iteration Count : KTI\n");
   F77("c---------------------------\n");
   F77("               KTI=k\n");
   F77("            else \n");
   F77("               nflg=0\n");
   F77("            end if\n");
   F77("         end if\n");
   F77("c\n");
   F77("         call mpi_bcast(nflg,1,mpi_integer,0,mpi_comm_world,\n");
   F77("     $        ierror)\n");
   F77("         if (nflg.eq.1) return\n");
   F77("c-------------------------------------------------------\n");
   F77("c Calculation of (r_{0},r_{i}) = rtotal\n");
   F77("c----------------------------------------\n");
   F77("c\n");
   F77("         ratotal=0.d0\n");
   F77("         ritotal=0.d0\n");
   F77("         rtotal=0.d0\n");
   F77("         do 780 i=1,naisum\n");
   F77("            ratotal=ratotal+w(naieq(i),1)*w(naieq(i),8)\n");
   F77(" 780     continue\n");
   F77("c\n");
   F77("         if (nrecvlist(rank+1).eq.1) then\n");
   F77("            do 790 i=1,nintotal\n");
   F77("               ritotal=ritotal+w(ninner(i),1)*w(ninner(i),8)\n");
   F77(" 790        continue\n");
   F77("         end if\n");
   F77("c\n");
   F77("         rtotal=ratotal+ritotal\n");
   F77("c\n");
   F77("         call mpi_reduce(rtotal,rtotal,1,\n");
   F77("     $        mpi_double_precision,mpi_sum,0,mpi_comm_world,\n");
   F77("     $        ierror)  \n");
   F77("c\n");
   F77(" 100  continue\n");
   F77("      return\n");
   F77("      end\n");
   F77("\n");
 CloseFile(fp);
 return;
}
