/*
   FEEL p2  MAKE FORTRAN LIBRARY   p_solve_pmset
 */

#include <stdio.h>
#include "../feel_def/feel_def.h"
#include "../system/system.h"

#define FNAME "p_solve_pmset.f"
lib_p_solve_pmset()
{
   FILE *fp;
   StoreMakefile(FNAME,SYSTEM_LIBRARY);
   if(LIMIT_FILE == 1) return;
   fp = OpenFileToWrite( FNAME );
   F77("      subroutine p_solve_pmset (npe,feel,icons,ipdat,\n");
   F77("     $     ncont1,ncont2,\n");
   F77("     $     ndim,npesum,npmaxsub,nelemsub,np,ndisub,neusub,\n");
   F77("     $     neq_sub,naisum,ninsum,nsendnum,nrecvnum,nintotal,\n");
   F77("     $     nmatrix,\n");
   F77("     $     npp_xsub,npp_ysub,npp_isubelem,npp_nelegru,\n");
   F77("     $     npp_nloglo,npp_nsendlist,npp_nrecvlist,npp_ndikaz,\n");
   F77("     $     npp_ndinum,npp_neukaz,npp_neunum,npp_matno,npp_ipdsub,\n");
   F77("     $     npp_IPFsub,npp_naieq,npp_nineq,npp_nsendtable,\n");
   F77("     $     npp_nrecvtable,npp_nsendkaz,npp_nrecvkaz,npp_npsre,\n");
   F77("     $     npp_ninner,npp_npsyo,npp_npins,npp_npibsub)\n");
   F77("*\n");
   F77("      implicit real*8 (a-h,o-z)\n");
   F77("*\n");
   F77("      real*4 feel(*)\n");
   F77("      dimension icons(ncont1)\n");
   F77("      dimension ipdat(2,ncont2)\n");
   F77("*\n");
   F77("      ndim     = icons(1)\n");
   F77("      npesum   = icons(2)\n");
   F77("      npmaxsub = icons(3)\n");
   F77("      nelemsub = icons(4)\n");
   F77("      np       = icons(5)\n");
   F77("      ndisub   = icons(6)\n");
   F77("      neusub   = icons(7)\n");
   F77("      neq_sub  = icons(8)\n");
   F77("      naisum   = icons(9)\n");
   F77("      ninsum   = icons(10)\n");
   F77("      nsendnum = icons(11)\n");
   F77("      nrecvnum = icons(12)\n");
   F77("      nintotal = icons(13)\n");
   F77("      nmatrix  = icons(14)\n");
   F77("*     \n");
   F77("      npp_xsub = ipdat(1,1)\n");
   F77("      npp_ysub = ipdat(1,2)\n");
   F77("c\n");
   F77("      if (ndim.ne.2) stop 'ndim error'\n");
   F77("c\n");
   F77("      npp_isubelem = ipdat(1,ndim+1)\n");
   F77("      npp_nelegru = ipdat(1,ndim+2)\n");
   F77("      npp_nloglo = ipdat(1,ndim+3)\n");
   F77("      npp_nsendlist = ipdat(1,ndim+4)\n");
   F77("      npp_nrecvlist = ipdat(1,ndim+5)\n");
   F77("      npp_ndikaz = ipdat(1,ndim+6)\n");
   F77("      npp_ndinum = ipdat(1,ndim+7)\n");
   F77("      npp_neukaz = ipdat(1,ndim+8)\n");
   F77("      npp_neunum = ipdat(1,ndim+9)\n");
   F77("      npp_matno = ipdat(1,ndim+10)\n");
   F77("      npp_ipdsub = ipdat(1,ndim+11)\n");
   F77("      npp_IPFsub = ipdat(1,ndim+12)\n");
   F77("      npp_naieq = ipdat(1,ndim+13)\n");
   F77("      npp_nineq = ipdat(1,ndim+14)\n");
   F77("      npp_nsendtable = ipdat(1,ndim+15)\n");
   F77("      npp_nrecvtable = ipdat(1,ndim+16)\n");
   F77("      npp_nsendkaz = ipdat(1,ndim+17)\n");
   F77("      npp_nrecvkaz = ipdat(1,ndim+18)\n");
   F77("      npp_npsre = ipdat(1,ndim+19)\n");
   F77("      npp_ninner = ipdat(1,ndim+20)\n");
   F77("      npp_npsyo = ipdat(1,ndim+21)\n");
   F77("      npp_npins = ipdat(1,ndim+22)\n");
   F77("      npp_npibsub = ipdat(1,ndim+23)\n");
   F77("*\n");
   F77("*     with respect to sending data and recving data\n");
   F77("*\n");
   F77("      call p_solve_sreqset(npe,ipdat,ndim,ndisub,\n");
   F77("     $     neusub,nsendnum,nrecvnum,npesum,feel(npp_npsre))\n");
   F77("*\n");
   F77("*     with respect to Dirichlet data\n");
   F77("      if (ndisub.gt.0) then\n");
   F77("         call p_solve_dset (ndisub,ndim,feel(npp_ndikaz),\n");
   F77("     $        ipdat,feel(npp_npsyo),feel(npp_npins))\n");
   F77("      end if\n");
   F77("*\n");
   F77("*     with respect to Neumann data\n");
   F77("      if (neusub.gt.0) then\n");
   F77("         call p_solve_nset (ndisub,neusub,ndim,feel(npp_neukaz),\n");
   F77("     $        ipdat,feel(npp_npibsub))\n");
   F77("      end if\n");
   F77("      return\n");
   F77("      end\n");
   F77("*\n");
   F77("      subroutine p_solve_sreqset (npe,ipdat,ndim,ndisub,\n");
   F77("     $     neusub,nsendnum,nrecvnum,npesum,npp_nsrequ)\n");
   F77("*\n");
   F77("*++++++++++++++++++++++++++++++\n");
   F77("*     FEEL/P2/Cenju-3/MPI subprogram\n");
   F77("*     Purpose : sending and receiving data\n");
   F77("*++++++++++++++++++++++++++\n");
   F77("*\n");
   F77("      implicit real*8 (a-h,o-z)\n");
   F77("*\n");
   F77("      dimension npp_nsrequ(npesum)\n");
   F77("      dimension ipdat(2,*)\n");
   F77("*\n");
   F77("*     with respect to sending data\n");
   F77("*\n");
   F77("      do 100 i=1,nsendnum\n");
   F77("         npp_nsrequ(i) = ipdat(1,ndim+23+2*ndisub+neusub+i)\n");
   F77(" 100  continue\n");
   F77("*\n");
   F77("*     with respect to receiving data\n");
   F77("*\n");
   F77("      do 200 i=1,nrecvnum\n");
   F77("         npp_nsrequ(i+nsendnum)\n");
   F77("     $        = ipdat(1,ndim+23+2*ndisub+neusub+npe+i)\n");
   F77(" 200  continue\n");
   F77("*\n");
   F77("*     if using one processor,.....(nsendnum=nrecvnum=0)\n");
   F77("*     \n");
   F77("      if ((nsendnum.eq.0).and.(nrecvnum.eq.0)) then\n");
   F77("         npp_nsrequ(1)=ipdat(1,ndim+23+2*ndisub+neusub+1)\n");
   F77("      end if\n");
   F77("*\n");
   F77("      return\n");
   F77("      end\n");
   F77("\n");
   F77("*\n");
   F77("      subroutine p_solve_dset (ndisub,ndim,ndikaz,ipdat,\n");
   F77("     $     npp_nsyori,npp_inset)\n");
   F77("*\n");
   F77("*++++++++++++++++++++++++++++++\n");
   F77("*     FEEL/P2/Cenju-3/MPI subprogram\n");
   F77("*     Purpose : Dirichlet data\n");
   F77("*++++++++++++++++++++++++++\n");
   F77("*\n");
   F77("      implicit real*8 (a-h,o-z)\n");
   F77("*\n");
   F77("      dimension ipdat(2,*)\n");
   F77("      dimension ndikaz(*)\n");
   F77("      dimension npp_nsyori(ndisub),npp_inset(ndisub)\n");
   F77("*\n");
   F77("      do 10 i=1,ndisub\n");
   F77("         if (ndikaz(i).gt.0) then\n");
   F77("            npp_inset(i)=ipdat(1,ndim+23+ndisub+i)\n");
   F77("            npp_nsyori(i)=ipdat(1,ndim+23+i)\n");
   F77("         end if\n");
   F77(" 10   continue\n");
   F77("      return\n");
   F77("      end\n");
   F77("*\n");
   F77("      subroutine p_solve_nset (ndisub,neusub,ndim,neukaz,\n");
   F77("     $     ipdat,npp_ibsubelem)\n");
   F77("*\n");
   F77("*\n");
   F77("*++++++++++++++++++++++++++++++\n");
   F77("*     FEEL/P2/Cenju-3/MPI subprogram\n");
   F77("*     Purpose :  Neumann data\n");
   F77("*++++++++++++++++++++++++++\n");
   F77("*\n");
   F77("      implicit real*8 (a-h,o-z)\n");
   F77("*      \n");
   F77("      dimension ipdat(2,*)\n");
   F77("      dimension neukaz(*)\n");
   F77("      dimension npp_ibsubelem(neusub)\n");
   F77("*\n");
   F77("      do 10 i=1,neusub\n");
   F77("         if (neukaz(i).gt.0) then\n");
   F77("            npp_ibsubelem(i)=ipdat(1,ndim+23+i+2*ndisub)\n");
   F77("         end if\n");
   F77(" 10   continue\n");
   F77("      return\n");
   F77("      end\n");
   F77("\n");
   F77("\n");
 CloseFile(fp);
 return;
}
