/*
   FEEL p2  MAKE FORTRAN LIBRARY   parallel_report
 */

#include <stdio.h>
#include "../feel_def/feel_def.h"
#include "../system/system.h"

#define FNAME "parallel_report.f"
lib_parallel_report()
{
   FILE *fp;
   StoreMakefile(FNAME,SYSTEM_LIBRARY);
   if(LIMIT_FILE == 1) return;
   fp = OpenFileToWrite( FNAME );
   F77("      subroutine time_rep(ifunc,mesg,io_out,isum)\n");
   F77("c\n");
   F77("c--------------------------------------------------------------\n");
   F77("c    Purpose : Report the execution time before MPI_INITIALIZE\n");
   F77("c             \n");
   F77("c      Input : ifunc\n");
   F77("c              mesg\n");
   F77("c              io_out : file number for 'feel_out'\n");
   F77("c--------------------------------------------------------------\n");
   F77("      include 'mpi.incl'\n");
   F77("      implicit real*8 (a-h,o-z)\n");
   F77("c\n");
   F77("      integer iresult\n");
   F77("      character mesg*(*)\n");
   F77("      save  idtime,itotal\n");
   F77("      data itotal/0/\n");
   F77("c\n");
   F77("      if(ifunc.eq.0) then\n");
   F77("         call cjgettmrf (iresult)\n");
   F77("         idtime = iresult\n");
   F77("         return\n");
   F77("      endif\n");
   F77("c\n");
   F77("      call cjgettmrf (iresult)\n");
   F77("      idt =iresult\n");
   F77("      itime = idt-idtime\n");
   F77("      idtime =idt\n");
   F77("      itotal=itotal + itime\n");
   F77("c\n");
   F77("      isum = itotal\n");
   F77("c\n");
   F77("      write(io_out,100) (dble(itotal)/1.d+3),(dble(itime)/1.d+3)\n");
   F77("     $     ,mesg\n");
   F77("100   format(f11.3,1x,'   [',f11.3,'] :  ',a)\n");
   F77("      return\n");
   F77("      end\n");
   F77("c\n");
   F77("      subroutine time_repcj(ifunc,p_rank,npe,mesg,io_out,isum)\n");
   F77("c--------------------------------------------------------------\n");
   F77("c    Purpose : Report the execution time after MPI_INITIALIZE\n");
   F77("c             \n");
   F77("c      Input : ifunc\n");
   F77("c              p_rank : PE number \n");
   F77("c              npe    : Total number of the using PEs\n");
   F77("c              mesg\n");
   F77("c              io_out : file number for 'feel_out'\n");
   F77("c--------------------------------------------------------------\n");
   F77("      include 'mpi.incl'\n");
   F77("      implicit real*8 (a-h,o-z)\n");
   F77("      integer p_rank,size,status(mpi_status_size)\n");
   F77("c     \n");
   F77("      integer iresult\n");
   F77("      character mesg*(*)\n");
   F77("c\n");
   F77("      save  idtime2,itotal2,itotal\n");
   F77("      data itotal2/0/\n");
   F77("c\n");
   F77("      if(ifunc.eq.0) then\n");
   F77("         call cjgettmrf (iresult)\n");
   F77("         idtime2 = iresult\n");
   F77("         return\n");
   F77("      endif\n");
   F77("c\n");
   F77("      call cjgettmrf (iresult)\n");
   F77("      idt =iresult\n");
   F77("      itime = idt-idtime2\n");
   F77("c\n");
   F77("      call mpi_reduce (itime,itime,1,mpi_integer,mpi_sum,\n");
   F77("     $        0,mpi_comm_world,ierror)\n");
   F77("c\n");
   F77("      idtime2=idt\n");
   F77("c\n");
   F77("      itotal2=itotal2+int(dble(itime)/dble(npe))\n");
   F77("*\n");
   F77("      if (p_rank.eq.0) then\n");
   F77("         write (io_out,100) dble(itotal2 + isum)/1.d+3,\n");
   F77("     $        (dble(itime)/(1.d+3*dble(npe)))\n");
   F77("     $        ,mesg\n");
   F77("      end if\n");
   F77("c\n");
   F77("c      \n");
   F77(" 100  format(f11.3,1x,'   [',f11.3,'] :  ',a)\n");
   F77(" 110  format(f11.3,1x,a)\n");
   F77("      return\n");
   F77("      end\n");
   F77("c\n");
   F77("c--------------------------------------------------------------------\n");
   F77("c\n");
   F77("      subroutine rep_head (io_out)\n");
   F77("*\n");
   F77("c --------------------------------------------------------------------\n");
   F77("*\n");
   F77("      write(io_out,800)\n");
   F77(" 800  format('FEEL P2 Parallel Version PROCEDURE REPORT')  \n");
   F77("\n");
   F77("      write(io_out,*)\n");
   F77("      write(io_out,900)\n");
   F77("      write(io_out,910)\n");
   F77("      write(io_out,920)\n");
   F77(" 900  format('Sum-up          Sub-Proc         Proc STATUS')\n");
   F77(" 910  format('Execution time  Execution time   REPORT     ')\n");
   F77(" 920  format('--------------  --------------   -----------')\n");
   F77("      return\n");
   F77("      end\n");
   F77("c\n");
   F77("c--------------------------------------------------------------------\n");
   F77("c\n");
   F77("      subroutine rep_var (npmax,io_out)\n");
   F77("*\n");
   F77("c --------------------------------------------------------------------\n");
   F77("* npmax\n");
   F77("      write(io_out,200) npmax\n");
   F77("*\n");
   F77(" 200  format('                             :  TOTAL NODES ',i9)\n");
   F77("      return\n");
   F77("      end\n");
   F77("c\n");
   F77("c\n");
   F77("      subroutine rep_CG(iter,zansa,io_out)\n");
   F77("c\n");
   F77("      implicit real*8 (a-h,o-z)\n");
   F77("c\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      write(io_out,200) iter \n");
   F77("      write(io_out,210) zansa\n");
   F77("\n");
   F77(" 200  format('                             :  ITERATION ',i8)\n");
   F77(" 210  format('                             :  RESIDUAL  ',E15.7)\n");
   F77("*\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine report\n");
   F77("      return\n");
   F77("      end\n");
 CloseFile(fp);
 return;
}
