/*
   FEEL p2  MAKE FORTRAN LIBRARY   f_alloc
 */

#include <stdio.h>
#include "../feel_def/feel_def.h"
#include "../system/system.h"

#define FNAME "f_alloc.f"
lib_f_alloc()
{
   FILE *fp;
   StoreMakefile(FNAME,SYSTEM_LIBRARY);
   if(LIMIT_FILE == 1) return;
   fp = OpenFileToWrite( FNAME );
   F77("      subroutine f_alloc_init(max_feel)\n");
   F77("*-------------------------------------------------------------------\n");
   F77("*  feelfem P2 Program model System Subroutine f_alloc_init\n");
   F77("*\n");
   F77("*  2000/05/30 (feelfem_stokes version)\n");
   F77("*\n");
   F77("*-------------------------------------------------------------------\n");
   F77("      parameter (MAX_PUSH=32)\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      common /feel_alc/np_work,iptr,np_push(MAX_PUSH),np_heap,max_heap\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      if(max_feel .LT. 1 ) call abortexit(0,'ERR f_alloc_init')\n");
   F77("      np_work  = 1\n");
   F77("      max_heap = 1\n");
   F77("      np_heap  = max_feel\n");
   F77("*\n");
   F77("      return\n");
   F77("*\n");
   F77("      end\n");
   F77("      integer*4 function np_work_get_falloc()\n");
   F77("*-------------------------------------------------------------------\n");
   F77("*  feelfem P2 Program model System function np_work_get_falloc\n");
   F77("*-------------------------------------------------------------------\n");
   F77("      parameter (MAX_PUSH=32)\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      common /feel_alc/np_work,iptr,np_push(MAX_PUSH),np_heap,max_heap\n");
   F77("c --------------------------------------------------------------------\n");
   F77("\n");
   F77("      np_work_get_falloc = np_work\n");
   F77("      \n");
   F77("      return\n");
   F77("*\n");
   F77("      end\n");
   F77("      subroutine f_alloc_get_info(np_work_ret,max_heap_ret)\n");
   F77("*-------------------------------------------------------------------\n");
   F77("*  feelfem P2 Program model System function np_work_set_falloc\n");
   F77("*-------------------------------------------------------------------\n");
   F77("      parameter (MAX_PUSH=32)\n");
   F77("      integer*4 np_work_ret,max_heap_ret\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      common /feel_alc/np_work,iptr,np_push(MAX_PUSH),np_heap,max_heap\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      np_work_ret  = np_work\n");
   F77("      max_heap_ret = max_heap\n");
   F77("* \n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine np_work_set_falloc(np)\n");
   F77("*-------------------------------------------------------------------\n");
   F77("*  feelfem P2 Program model System function np_work_set_falloc\n");
   F77("*-------------------------------------------------------------------\n");
   F77("      parameter (MAX_PUSH=32)\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      common /feel_alc/np_work,iptr,np_push(MAX_PUSH),np_heap,max_heap\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      if(np .GT. np_heap .OR. np .LT. 1) then\n");
   F77("         call abortexit(-1,'np_work_set_err')\n");
   F77("      endif\n");
   F77("*\n");
   F77("      np_work = np\n");
   F77("      if(max_heap .LT. np_work) max_heap = np_work\n");
   F77("*\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine f_alloc(nptr , cha, n , itype, imode)\n");
   F77("*-------------------------------------------------------------------\n");
   F77("*  feelfem P2 Program model System Subroutine f_alloc\n");
   F77("*-------------------------------------------------------------------\n");
   F77("*  Purpose:  Allocate memory\n");
   F77("*\n");
   F77("*   nptr  :out   : allocated address in real*4 feel(*)\n");
   F77("*   cha   :in    : comment for allocation\n");
   F77("*   n     :in    : size (as Fortran array, not word)\n");
   F77("*   itype :in    : 0 4-byte(integer)  1 8-byte(double precision)\n");
   F77("*   imode :in/out: [in] = 0 when error ABORT\n");
   F77("*                       =-1 when error return anyway\n");
   F77("*                  [out]=0 no error\n");
   F77("*                       >0 size of shortage in words\n");
   F77("*-------------------------------------------------------------------\n");
   F77("      parameter (MAX_PUSH=32)\n");
   F77("      character cha*(*)\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      common /feel_alc/np_work,iptr,np_push(MAX_PUSH),np_heap,max_heap\n");
   F77("c --------------------------------------------------------------------\n");
   F77("*\n");
   F77("      nn = 0\n");
   F77("      if(itype .eq. 1) then\n");
   F77("        if((np_work / 2) * 2 .eq. np_work) np_work = np_work+1\n");
   F77("	nn = n * 2\n");
   F77("      endif\n");
   F77("      if(itype .eq. 0) then\n");
   F77("	nn = n\n");
   F77("      endif\n");
   F77("\n");
   F77("      if(nn .eq. 0) then\n");
   F77("	write(*,*) 'in allocate ',cha\n");
   F77("	write(*,*) 'n = ',n,' itype = ',itype\n");
   F77("        call abortexit(-1,'f_alloc itype error')\n");
   F77("      endif\n");
   F77("  \n");
   F77("      np = np_work + nn\n");
   F77("      if(np . gt . np_heap) then\n");
   F77("        if(imode .eq. 0) then\n");
   F77("          write(*,*) 'Cannot allocate array for ',cha \n");
   F77("          write(*,*) 'No space for ',np-np_heap ,' word'\n");
   F77("          call abortexit(-1,'feel: memory allocation')\n");
   F77("        else\n");
   F77("          write(*,*) 'Cannot allocate array for ',cha \n");
   F77("          if(imode .ne. -1) then\n");
   F77("             call abortexit(-1,'and imode error in f_alloc')\n");
   F77("          endif\n");
   F77("          imode = np-np_heap\n");
   F77("        endif\n");
   F77("      endif\n");
   F77("*\n");
   F77("      nptr    = np_work\n");
   F77("      np_work = np\n");
   F77("*\n");
   F77("      if(np_work.gt.max_heap) max_heap = np_work\n");
   F77("      if(imode.eq. -1) imode   = 0\n");
   F77("*\n");
   F77("      return\n");
   F77("*\n");
   F77("      end\n");
   F77("      subroutine f_alloc_push\n");
   F77("*-------------------------------------------------------------------\n");
   F77("*  feelfem P2 Program model System Subroutine f_alloc_push\n");
   F77("*-------------------------------------------------------------------\n");
   F77("      parameter (MAX_PUSH=32)\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      common /feel_alc/np_work,iptr,np_push(MAX_PUSH),np_heap,max_heap\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      data    iptr/0/\n");
   F77("      iptr = iptr + 1\n");
   F77("      if(iptr.GT.MAX_PUSH) then\n");
   F77("         call abortexit(-1,'TOO MANY F_ALLOC PUSH called')\n");
   F77("      endif\n");
   F77("      np_push(iptr) = np_work\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine f_alloc_pop\n");
   F77("*-------------------------------------------------------------------\n");
   F77("*  feelfem P2 Program model System Subroutine f_alloc_pop\n");
   F77("*-------------------------------------------------------------------\n");
   F77("      parameter (MAX_PUSH=32)\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      common /feel_alc/np_work,iptr,np_push(MAX_PUSH),np_heap,max_heap\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      if(iptr .eq. 0) then\n");
   F77("         call abortexit(-1,'TOO MANY F_ALLOC_POP called')\n");
   F77("      endif\n");
   F77("      np_work = np_push(iptr)\n");
   F77("      iptr = iptr - 1\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine f_move(ide,ia, num)\n");
   F77("*-----------------------------------\n");
   F77("* Move array block de ide(*) a ia(*).\n");
   F77("*-----------------------------------\n");
   F77("      integer*4 ide(*),ia(*)\n");
   F77("      do 100 i=1,num\n");
   F77("         ia(i)=ide(i)\n");
   F77(" 100  continue\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine abortexit(myrank,cha)\n");
   F77("*----------------------------------------\n");
   F77("* 2001/01/27\n");
   F77("*----------------------------------------\n");
   F77("      integer myrank \n");
   F77("      character cha*(*)\n");
   F77("*\n");
   F77("      write(*,*) 'Error ',cha\n");
   F77("      call doclosefil(-1)\n");
   F77("*\n");
   F77("      stop 'abort exit'\n");
   F77("      end\n");


 CloseFile(fp);
 return;
}
