module mod_edev1_1
contains

subroutine edev1_1(mypeid,resvec,ipd,enptr,con,nelem,fem_u)
!--------------------------------------------------------
! Generated by  feelfem Copyright(c) 2000 NEC Corporation
!--------------------------------------------------------
! feelfem90/DRAMA Program Model
! 2001/05/08 11:01
!----------------------------------------------------
use numeric
implicit none

integer,intent(in)              :: mypeid
real(kind=REAL8),dimension(:)   :: resvec
integer,dimension(:)            :: ipd
integer,dimension(:,:)          :: enptr,con
integer,intent(in)              :: nelem

real(kind=REAL8),dimension(:),pointer :: fem_u

! auto variables
integer                         :: i,j
integer                         :: ipos_from,ipos_to
integer                         :: nodes
integer                         :: nnd,npe
integer,dimension(3)            :: ienp_u,iedp_u

! data statements
data ienp_u/ 1,2,3/
data iedp_u/ 0,0,0/
!------------------------------------------------------

do i=1,nelem
  ipos_from = enptr(1,i  )
  ipos_to   = enptr(1,i+1)-1
  nodes     = ipos_to-ipos_from+1

 do j=1,3
  nnd = con(1,ipos_from+ienp_u(j)-1)
  npe = con(2,ipos_from+ienp_u(j)-1)
  if(npe .eq. mypeid) then
fem_u(nnd) = resvec(ipd(nnd) + iedp_u(j))
  end if
 end do

end do

end subroutine edev1_1
end module mod_edev1_1
