program feelfem
!--------------------------------------------------------
! Generated by  feelfem Copyright(c) 2000 NEC Corporation
!--------------------------------------------------------
! feelfem90/DRAMA Program Model
! 2001/05/08 11:01
!----------------------------------------------------
! general modules
use preport90
use numeric
use abortmodule
use fileread
use femDataType
use dramaDataModel
use datatrans
use preport90
implicit none
include 'mpif.h'

! Output level
integer(kind=INT4 ),parameter  :: outlevel = 3          ! output level

real(kind=REAL8),dimension(:),pointer :: x,y,z          ! global coordinates
real(kind=REAL8),dimension(:),pointer :: xloc,yloc,zloc ! local coordinates
integer(kind=INT4 )            :: ierror                ! for MPI
integer(kind=INT4 )            :: nprocs,myrank,mypeid  ! MPI parameters
integer(kind=INT4 )            :: nprocs_check

!-----------------------------------------------------------------
! feel_dat fundamental parameters
!-----------------------------------------------------------------
integer(kind=INT4 )            :: ndim        ! space dimension
integer(kind=INT4 )            :: npmax       ! nodes(global/local)
integer(kind=INT4 )            :: npmax_g     ! set in initbcast
integer(kind=INT4 )            :: nelem_g     ! number of region element
integer(kind=INT4 )            :: nedat
integer(kind=INT4 )            :: nnset
integer(kind=INT4 )            :: nnum
integer(kind=INT4 )            :: nip
!
integer(kind=INT4 )            :: mode_ex
integer(kind=INT4 )            :: mode_output
integer(kind=INT4 )            :: nvars_fem,nvars_ewise

! ------------
! Problem data
! ------------
type(meshInformation)          :: meshDat
type(solveInformation)         :: solveDat
type(solveList)                :: solveLst        
! ----
! EDAT
! ----
type(edat), pointer            :: edatData
type(edatList),pointer         :: firstEdatPtr,currentEdatPtr,edatPtr

! ----
! NSET
! ----
type(nset), pointer            :: nsetData
type(nsetList),pointer         :: firstNsetPtr,currentNsetPtr,nsetPtr

! ----
! IP
! ----
type(ipdat),pointer            :: ipData

! -----------------------
! for metis data
! -----------------------
integer,dimension(:),pointer   :: metis

! -----------------------
! DRAMA double index data
! -----------------------
type (dramaEdat), pointer      :: dramaEdatData
type (dramaEdatList),pointer   :: dramaEdatPtr,firstDramaEdatPtr, &
                                  currentDramaEdatPtr
type (dramaNsetList),pointer   :: firstDramaNsetPtr
type (dramaIP),pointer         :: dramaIPData

! ------------------------------
! for Making DRAMA/double index
! ------------------------------       
integer,dimension(:,:),pointer :: loc
integer                        :: mynode,myelem

! ------------------------------
! FEM,EWISE variables
! ------------------------------                             
call MPI_INIT(ierror)
call MPI_COMM_SIZE(MPI_COMM_WORLD,nprocs,ierror)
call MPI_COMM_RANK(MPI_COMM_WORLD,myrank,ierror)


mypeid = myrank

if(myrank == 0) call preport90init(outlevel)
if(myrank == 0) call preport('Start')

!----------------
! MESH DATA READ 
!----------------
if(myrank.eq.0) then

  !---------
  ! solv_dat
  !---------
  call ctrlinp(meshDat,solveLst, ierror)
  if(ierror .eq. Oui) then
    call abortexit(mypeid)
  endif


  !---------
  ! feel_dat
  !---------
  call datinp(ndim,npmax,nelem_g,nedat,nnset,nnum,nip, &
              mode_ex,mode_output,nvars_fem,nvars_ewise,       &
              x,y,z,                                           &
              firstEdatPtr,firstNsetPtr,ipData, ierror           )

  if(ierror .eq. Oui) then
    call abortexit(mypeid)
  endif

  !-----------
  ! metis.bamg
  ! metis.feel
  !-----------
  allocate(metis(nelem_g))
  call read_metis(nprocs,nelem_g,metis,ierror)
  if(ierror .eq. Oui) then
    call abortexit(mypeid)
  endif

  call preport('File READ')
  call preport90FundamentalVars(ndim,npmax,nedat,nnset,nnum,nip)
!
end if
!-----------------------
! Message passing
!-----------------------
call initbcast(myrank,nprocs,                                     &
               ndim,npmax,npmax_g,nelem_g,nedat,nnset,nnum,nip,   &
               mode_ex,mode_output,nvars_fem,nvars_ewise,         &
               x,y,                                               &
               firstEdatPtr,firstNsetPtr,ipData,                  &
               metis                                               )

 if(myrank .eq. 0) call preport('End of TRANSFER,NODE,EDAT')

!---------------------------------
! Make DRAMA double index data
! step 1 LONUMERATE
!---------------------------------
 allocate(loc(2,npmax_g))
 call lonumerate(mypeid,nprocs,  loc,npmax_g, metis,nelem_g,  &
                 firstEdatPtr,   mynode,myelem                )
  if(myrank .eq. 0) call preport('MODULE:lonumerate')

!-----------------------------------
! Make DRAMA double index data
! step 2 Make local coordinate array
!-----------------------------------
 allocate(xloc(mynode),yloc(mynode))
 call mkloccoor(mypeid,nprocs,x,y,loc,npmax_g,xloc,yloc,mynode)
  if(myrank .eq. 0) call preport('MODULE:mkloccoor')

!-------------------------------------------
! Make DRAMA double index data
! step 3 Make local & global enptr/con/matno
!-------------------------------------------

! first, mark isRegion in type edatList

  edatPtr => firstEdatPtr
  region_edat_mark_loop: do
    edatData => edatPtr%edatData
    if(edatData%nelem == nelem_g) then
      edatPtr%isRegion = Oui
    else
      edatPtr%isRegion = Non
    endif
    if(.not.associated(edatPtr%next)) exit region_edat_mark_loop
    edatPtr => edatPtr%next
  end do region_edat_mark_loop

  call mkdramaedats(mypeid,nprocs,loc,npmax_g,metis,nelem_g, &
                    mynode,myelem, firstEdatPtr,firstDramaEdatPtr)

  if(myrank == 0) call preport('MODULE:mkdramaedats')

!-------------------------------------------
! Make DRAMA double index data for NSET
! step 4 Make local & global nset
!-------------------------------------------
  if(associated(firstNsetPtr) ) then
    call mkdramansets(mypeid,nprocs,loc,npmax_g, &
                      firstNsetPtr,firstDramaNsetPtr)
    if(myrank == 0) call preport('MODULE:mkdramansets')
  else
    if(myrank == 0) call preport('      :(No nset data sets)')
  endif

!-------------------------------------------
! Make DRAMA double index data
! step 5 conver ip information
!-------------------------------------------
if(nip > 0) then
  call mkdramaip(mypeid,nprocs,loc,npmax_g, &
                 ipData,dramaIPData         )
else
  nullify(dramaIPData)
endif

!-------------------------------------------
! Make DRAMA double index data
! step 6 deallocation
!-------------------------------------------

deallocate(metis)
deallocate(x,y)
deallocate(loc)

edatPtr => firstEdatPtr
deallocate_edat : do
  edatData => edatPtr%edatData
  deallocate(edatData%ielem)
  deallocate(edatData%matno)
!  deallocate(edatData)
  if(.not.associated(edatPtr%next)) exit deallocate_edat
  edatPtr => edatPtr%next
end do deallocate_edat

if(associated(firstNsetPtr)) then
  nsetPtr => firstNsetPtr
  deallocate_nset : do
    nsetData => nsetPtr%nsetData
    deallocate(nsetData%inset)
!         deallocate(nsetData)
    if(.not.associated(nsetPtr%next)) exit deallocate_nset
    nsetPtr => nsetPtr%next
  end do deallocate_nset
endif

if(myrank == 0) call preport('Deallocation complete')

npmax =  mynode
x     => xloc
y     => yloc

*******************************************************
*** This is temporary func for DoMainRoutineSchemeStart
*******************************************************
********************************************************
*** This is temporary func for DoMainRoutineSchemeFinish
********************************************************
!------------------------------------------------------
!call preportallmem(myrank,nprocs)
!if(myrank.eq.0) call preportfini

call MPI_FINALIZE(ierror)

end program feelfem
