/*
 *  feelfem version 1.0  Copyright(c)  NEC Corporation 1999-2002
 *                       Programmed by Hidehiro  FUJIO
 *
 *  Filename : EcalInfo.hpp
 *  Date     : 2002/02/22
 *  Modified : 
 *  
 *  Purpose  : This class is generated by 
 *             DiscretizedComponent::GenerateEcalInfo();
 *
 *
 *  feelfem2 (modernized/ported)
 *  Copyright (C) 2025-2026 Hidehiro Fujio and contributors
 *  SPDX-License-Identifier: BSD-3-Clause
 *  Repository: https://github.com/oimokoimo/feelfem2
 *
 *
 *  Notes:
 *  
 */

#ifndef FEM_CLASS_ECALINFO
#define FEM_CLASS_ECALINFO

#include "string.hpp"
#include "orderedList.hpp"
#include "ptrList.hpp"
#include "EcalEvalPair.hpp"

class Element;




// EcalInfo class   corresponds each solveNo-elemNo-quadNo
class EcalInfo {
public:
  EcalInfo( );
  ~EcalInfo();

  void SetNumbers(int,int,int);    // used for regional (plural quadratures)
  void SetNumbers(int,int);        // used for boundary (single quadrature)

  void AddUniqTermCommon(char *);
  void AddUniqTermIntegrand(char *);
  void AddUniqEcalEvalPair(Element *, int );
  
  void AddUniqEcalEvalPair_boundary(Element *boundaryElemPtr,int);  // boundary
  
  void SumUpIntegrandTerm( orderedList <string > &);

  orderedList <string> &GetCommonTermLst(void)
  {
    return commonTermLst;
  }

  orderedList <string> &GetIntegrandTermLst(void)
  {
    return integrandTermLst;
  }

  list <Element *> &GetUsedElementPtrLst(void) 
  {
    return usedElementPtrLst;
  }

  ptrList <EcalEvalPair *>&GetEcalEvalPairPtrLst(void)
  {
    return ecalEvalPairPtrLst;
  }


  void SetUseXYZ(int,int,int);
  void SetUseNXNYNZ(int,int,int);

  int IsUseX(void);
  int IsUseY(void);
  int IsUseZ(void);

  int IsUseNX(void);
  int IsUseNY(void);
  int IsUseNZ(void);

private:
  int solveNo;
  int solveElementNo;
  int quadNo;
  
  int ncondNo;

  int useX,useY,useZ;
  int useNX,useNY,useNZ;

  int diffOrder;    // differential order

  int commonTerms;
  orderedList <string>commonTermLst;

  int integrandTerms;
  orderedList <string>integrandTermLst;

  list    <Element      *>usedElementPtrLst ;
  ptrList <EcalEvalPair *>ecalEvalPairPtrLst;   // add 020304 (for eset,,,,

};

#endif
