rm */*.a
rm */core
rm exec/feel
rm exec/feel.contour
rm exec/feel.showvec
rm test/parse
rm mesh_book/*/*.exe
rm mesh_book/*/*.o
rm */*~
rm feelG/*/*.o
rm util/*/*.o
rm util/*/*~
rm util/showdat3/feel.showdat3
rm util/show_dat/feelshowdat
rm */*.o
rm parallel_tool/*/*.o
rm mesh_bamg_util/*/*.o
rm mesh_bamg_util/*/feel.bamg.exe
rm viewmesh/*/*.o
rm viewmesh/exec/feelmesh
rm viewmesh/prog/feel.meshview
rm modulef/*/*.a
rm modulef/*/*.o
rm */*/*~
rm feelG/*/a.out
rm util/xplot/libxplot.a
rm xplot/xplot.a
rm util/metis/BAMG_METIS/*.o
rm util/metis/BAMG_METIS/*~
rm util/metis/BAMG_METIS/bamg.metis.exe
rm util/metis/SHOW_DIVIDE/*.o
rm util/metis/SHOW_DIVIDE/*~
rm util/metis/SHOW_DIVIDE/divideshow


