module mod_pamg81param1_1
contains

subroutine pamg81param1_1(mypeid,nprocs,isumup,      &
      enptr,con,nelem,                         &
      ipf,ipd,npmax,                           &
      enptr_ex,con_ex,nelem_ex,                &
      ndno,peno,ipf_ex,ipd_ex,nouter,          &
      neq,ipd_halo,nhalo,                      &
      iuamg,ipamg,nsys,npts,iscale             )

!--------------------------------------------------------
! Generated by  feelfem Copyright(c) 2000 NEC Corporation
!--------------------------------------------------------
! feelfem90/DRAMA Program Model
! 2001/05/08 11:01
!----------------------------------------------------
use numeric
use subSolveDrama
implicit none

integer,intent(in)              :: mypeid,nprocs
integer,dimension(:)            :: isumup

integer,dimension(:,:)          :: enptr,con
integer,intent(in)              :: nelem

integer,dimension(:)            :: ipf,ipd
integer,intent(in)              :: npmax

integer,dimension(:,:)          :: enptr_ex,con_ex
integer,intent(in)              :: nelem_ex

integer,dimension(:)            :: ndno,peno,ipf_ex,ipd_ex
integer,intent(in)              :: nouter

integer,intent(in)              :: neq,nhalo
integer,dimension(:)            :: ipd_halo

integer,dimension(:),pointer    :: iuamg,ipamg,iscale
integer                         :: nsys,npts
! auto variables
integer                         :: i,j
integer                         :: ipos_from,ipos_to
integer                         :: nodes
integer                         :: ind,ipe
integer                         :: nd

integer,dimension(3)            :: ienp_u,iedp_u

! data statements
data ienp_u/ 1,2,3/
data iedp_u/ 0,0,0/
!------------------------------------------------------
nsys = 1            ! number of physical unknown types
allocate(iscale(nsys))

do i=1,nsys
 iscale(i) = 0
end do

if(nsys == 1) then

  npts = 0    ! do not allocat iuamg,ipamg
  nullify(iuamg)
  nullify(ipamg)
  return

endif

allocate(iuamg(neq+nhalo))
allocate(ipamg(neq+nhalo))

! future extension
do i=1,neq+nhalo
 ipamg(i)=0
end do

do i=1,nelem
  ipos_from = enptr(1,i  )
  ipos_to   = enptr(1,i+1)-1
  nodes     = ipos_to-ipos_from+1

 do j=1,3
  ind = con(1,ipos_from+ienp_u(j)-1)
  ipe = con(2,ipos_from+ienp_u(j)-1)
  if(ipe .eq. mypeid) then
   iuamg(ipd(ind)+iedp_u(j)) = 1

  else

   nd = ndsearch_ex(ind,ipe,ndno,peno,nouter)
   iuamg(ipd_halo(nd)+iedp_u(j) + neq) = 1
  end if
 end do

end do

do i=1,nelem_ex
  ipos_from = enptr_ex(1,i  )
  ipos_to   = enptr_ex(1,i+1)-1
  nodes     = ipos_to-ipos_from+1

 do j=1,3
  ind = con_ex(1,ipos_from+ienp_u(j)-1)
  ipe = con_ex(2,ipos_from+ienp_u(j)-1)
  if(ipe .eq. mypeid) then
   iuamg(ipd(ind)+iedp_u(j)) = 1

  else

   nd = ndsearch_ex(ind,ipe,ndno,peno,nouter)
   iuamg(ipd_halo(nd)+iedp_u(j) + neq) = 1
  end if
 end do

end do

end subroutine pamg81param1_1
end module mod_pamg81param1_1
