# THIS MAKEFILE IS GENERATED BY MAKEMAKE PROGRAM.
# Typical usage of makemake command is as follows.
#
# DIR | makemake execute-filename
#

cc   = cl
f77  = fl32
link = link

proj = feel.Fin
objs = input.obj main.obj output.obj 

all : $(proj).exe

$(proj).exe: $(objs)
	$(link) $(objs) $(f77libs) $(gui_libs) -out:$@ $(lflags) \
           $(lnk_debug) $(guiflags)

input.obj  :   input.f
	$(f77) $(fflags) input.f /c

main.obj  :   main.f
	$(f77) $(fflags) main.f /c

output.obj  :   output.f
	$(f77) $(fflags) output.f /c


clean :
	-del *.obj
	-del *.exe
