CFLAGS =  $(ADDITIONALCFLAGS)
mesh_interface.a :mesh_interface.a(get_face_from_region.o) mesh_interface.a(make_mesh_region.o) mesh_interface.a(make_point_in_face.o) mesh_interface.a(make_region_divide_complete.o) mesh_interface.a(make_region_order.o) mesh_interface.a(mesh_control.o) mesh_interface.a(mesh_generate_main.o) mesh_interface.a(mesh_size.o) mesh_interface.a(remake_face_point.o) 
