/*
 *  feelfem v1.0 NEC Corporation (C) 1999,2000,2001
 *                   Programmed  by  Hidehiro FUJIO
 *
 *  Filename : SL_user_coo.cpp
 *  Date     : 2001/02/06 14:22
 *  Purpose  : Library module generator
 *
 */
#include "SL_LIB_feelfem90SAMG20c.hpp"

static int come_yet_user_coo = 0;


void SL_LIB_feelfem90SAMG20c::SL_user_coo(int makeFlag)
{
  char *sourceName;


  cerr << "NOW default user_coo.f90 generated by feelfem!(-w generator)"
       << "\n";

  if(come_yet_user_coo == 1)  return;
  else                  come_yet_user_coo = 1;

  sourceName = GetSourceName("user_coo");
  OpenSource(sourceName,makeFlag);

  // ORIGINAL SOURCE STARTS-----------------


  writeSource("!........................................................................................");
  writeSource("!     user_coo(i,ndim,x,y,z)");
  writeSource("!........................................................................................");
  writeSource("!........................................................................................");
  com();
  writeSource("      subroutine user_coo(i,ndim,x,y,z)");
  com();
  writeSource("!     Purpose: Provide variable-to-coordinate mapping.");
  com();
  writeSource("!     If no coordinates are available, just return with NDIM=0.");
  com();
  writeSource("!     input:");
  com();
  writeSource("!        i    - number of variable (1<=i<=nnu)");
  com();
  writeSource("!     output:");
  com();
  writeSource("!        ndim  - dimension of current problem (=2 or =3)");
  writeSource("!        x,y,z - coordinates of point where variable i is located");
  writeSource("!                (if ndim=2: z=0.0d0).");
  com();
  writeSource("      implicit none");
  writeSource("      integer i,ndim");
  writeSource("      double precision x,y,z");
  com();
  writeSource("      ndim=0      ! ndim=0 means: no coordinates defined");
  writeSource("      return");
  writeSource("      end subroutine");

  // ORIGINAL SOURCE END-------------------

  CloseSource();

  return;
}
