# THIS MAKEFILE IS GENERATED BY MAKEMAKE PROGRAM.
# Typical usage of makemake command is as follows.
#
# DIR | makemake execute-filename
#

cc   = cl
f77  = fl32
link = link

proj = feel.Mid
objs = input.obj main.obj newpnt.obj nodelm.obj output.obj reelm.obj renode.obj 

all : $(proj).exe

$(proj).exe: $(objs)
	$(link) $(objs) $(f77libs) $(gui_libs) -out:$@ $(lflags) \
           $(lnk_debug) $(guiflags)

input.obj  :   input.f
	$(f77) $(fflags) input.f /c

main.obj  :   main.f
	$(f77) $(fflags) main.f /c

newpnt.obj  :   newpnt.f
	$(f77) $(fflags) newpnt.f /c

nodelm.obj  :   nodelm.f
	$(f77) $(fflags) nodelm.f /c

output.obj  :   output.f
	$(f77) $(fflags) output.f /c

reelm.obj  :   reelm.f
	$(f77) $(fflags) reelm.f /c

renode.obj  :   renode.f
	$(f77) $(fflags) renode.f /c


clean :
	-del *.obj
	-del *.exe
