CFLAGS = $(ADDITIONALCFLAGS)
makefort77.a :makefort77.a(get_new_B_niv.o) makefort77.a(make_feel_fort77_modulef.o) makefort77.a(mf_make_library.o) makefort77.a(mf_make_module_interface.o) makefort77.a(mf_make_scheme.o) makefort77.a(mf_make_scheme_ewisealloc.o) makefort77.a(mf_make_scheme_femalloc.o) makefort77.a(mf_mk_allocfemv.o) makefort77.a(mf_mk_feelmf.o) makefort77.a(mf_mk_feelnopo.o) 
