FFLAGS = -static $(ADDITIONALFFLAGS)
feel.Tri.exe: area.o bndnod.o bougen.o check.o data.o decr.o delaun.o distor.o edge.o fine.o incr.o input.o ipush.o ivert.o laplas.o lawson.o locate.o main.o model.o neibor.o pick.o poly.o remesh.o remove.o renumber.o rough.o search.o subdiv.o swap.o theta.o tria.rev.o
	f77 -o feel.Tri.exe area.o bndnod.o bougen.o check.o data.o decr.o delaun.o distor.o edge.o fine.o incr.o input.o ipush.o ivert.o laplas.o lawson.o locate.o main.o model.o neibor.o pick.o poly.o remesh.o remove.o renumber.o rough.o search.o subdiv.o swap.o theta.o tria.rev.o
