#include <stdio.h>

void lisplib_fs_dep( fp )
     FILE *fp;
{
  LISP_SEND(fp,"(setq *funcs* '(sin cos tan asin acos atan exp log ln lap div rot dx dy\n");
  LISP_SEND(fp,"		dsin dcos dtan dexp dlog ))\n");
  LISP_SEND(fp,"(defun fs-dep (lst)\n");
  LISP_SEND(fp,"  (cond ((atom lst)                  lst)\n");
  LISP_SEND(fp,"	((eq '^  (car lst) )\n");
  LISP_SEND(fp,"	 (if(eq 0 (caddr lst)) 1                 ; 指数が0 の時\n");
  LISP_SEND(fp,"	   (if(eq 1 (caddr lst))    (cadr lst)   ; 指数が1 の時\n");
  LISP_SEND(fp,"	     (if(listp (caddr lst))\n");
  LISP_SEND(fp,"		 (list '^ (cadr lst) (fs (caddr lst))) ;指数が数式の時\n");
  LISP_SEND(fp,"	       lst))))\n");
  LISP_SEND(fp,"	((member (car lst) *funcs*)  lst)\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"	((eq '+  (car lst) ) (fs-dep+ lst))\n");
  LISP_SEND(fp,"	((eq '*  (car lst) ) (fs-dep* lst))\n");
  LISP_SEND(fp,"	(t (format t \"OH MY GOD IN FS-DEP =>~S~%%\" lst))))\n");
  LISP_SEND(fp,"(defun fs-dep+ (lst)\n");
  LISP_SEND(fp,"  (let ((dlst  (mapcar #'fs-dep (cdr lst))))\n");
  LISP_SEND(fp,"    (do* ((rlst  '(+)                 )\n");
  LISP_SEND(fp,"	  (llst  dlst       (cdr llst))\n");
  LISP_SEND(fp,"	  (ptr  (car llst)  (car llst)))\n");
  LISP_SEND(fp,"	 ((null llst) rlst)\n");
  LISP_SEND(fp,"	 (cond \n");
  LISP_SEND(fp,"	  ((atom ptr)        (setq rlst (append rlst (list ptr))))\n");
  LISP_SEND(fp,"	  ((eq '+ (car ptr)) (setq rlst (append rlst\n");
  LISP_SEND(fp,"						(cdr ptr))))\n");
  LISP_SEND(fp,"	  (t (setq rlst (append rlst (list ptr))))))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun fs-dep* (lst)\n");
  LISP_SEND(fp,"  (let* (( tmp   (fs-dep-*x lst nil nil ) )\n");
  LISP_SEND(fp,"	 ( term* (cadr  tmp) )\n");
  LISP_SEND(fp,"	 ( term+ (caddr tmp) )                    )\n");
  LISP_SEND(fp,"    (cond \n");
  LISP_SEND(fp,"     ((null term+) (cons '* term*))\n");
  LISP_SEND(fp,"     ((eq 1 (length term+))\n");
  LISP_SEND(fp,"      (fs-dep*-make-term (mapcar #'list (car term+)) term*))\n");
  LISP_SEND(fp,"     (t (fs-dep*-make-term \n");
  LISP_SEND(fp,"	 (fs-dep-term+ (cons (mapcar #'list (car term+)) (cdr term+)))\n");
  LISP_SEND(fp,"	 term*)))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun fs-dep*-make-term (term+ term*)\n");
  LISP_SEND(fp,"  (cons '+\n");
  LISP_SEND(fp,"	(mapcar #'(lambda (x) (cons '* (append x term*))) \n");
  LISP_SEND(fp,"		(fs-dep*-make-aux term+))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun fs-dep*-make-aux (lst)\n");
  LISP_SEND(fp,"  (cond ((null lst) nil)\n");
  LISP_SEND(fp,"	(t\n");
  LISP_SEND(fp,"	 (cons (fs-dep*-make-aux-2 (car lst)) \n");
  LISP_SEND(fp,"	       (fs-dep*-make-aux (cdr lst))))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun fs-dep*-make-aux-2 (lst)\n");
  LISP_SEND(fp,"  (cond ((atom (car lst)) lst)\n");
  LISP_SEND(fp,"	(t \n");
  LISP_SEND(fp,"	 (do* (( dlst lst (cdr dlst))	       \n");
  LISP_SEND(fp,"	       ( ptr  (car dlst) (car dlst))\n");
  LISP_SEND(fp,"	       ( rlst nil           ))\n");
  LISP_SEND(fp,"	      ((null dlst) rlst)\n");
  LISP_SEND(fp,"	      (cond ((atom ptr) (setq rlst (append rlst\n");
  LISP_SEND(fp,"						    (list ptr))))\n");
  LISP_SEND(fp,"		    ((eq '* (car ptr)) ( setq rlst\n");
  LISP_SEND(fp,"					      (append rlst (cdr ptr))))\n");
  LISP_SEND(fp,"		    (t (setq rlst (append rlst (list ptr)))))))))\n");
  LISP_SEND(fp,"(defun fs-dep-term+ (lst)\n");
  LISP_SEND(fp,"  (if(eq 1 (length lst)) (car lst)\n");
  LISP_SEND(fp,"    (let ((t1  (car  lst)    )\n");
  LISP_SEND(fp,"	  (t2  (cadr lst)    )\n");
  LISP_SEND(fp,"	  (remain (cddr lst) ))\n");
  LISP_SEND(fp,"      (do* ((dlst t2        (cdr dlst))\n");
  LISP_SEND(fp,"	    (ptr (car dlst) (car dlst))\n");
  LISP_SEND(fp,"	    (rlst nil                 ))\n");
  LISP_SEND(fp,"	   ((null dlst) (fs-dep-term+ (cons rlst remain)))\n");
  LISP_SEND(fp,"	   (setq rlst (append rlst\n");
  LISP_SEND(fp,"			      (mapcar #'(lambda (x) (cons ptr x)) t1)))))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun fs-dep-*x (lst lst* lst+)\n");
  LISP_SEND(fp,"  (let (( tmp  nil           ))\n");
  LISP_SEND(fp,"    \n");
  LISP_SEND(fp,"    (cond \n");
  LISP_SEND(fp,"     ((atom lst) (list  nil (cons lst lst*) lst+))\n");
  LISP_SEND(fp,"     ((eq '^ (car lst)) (list  nil (cons lst lst*)  lst+))\n");
  LISP_SEND(fp,"     ((member (car lst) *funcs*) (list nil (cons lst lst*) lst+))\n");
  LISP_SEND(fp,"     ((eq '+ (car lst)) (list  nil \n");
  LISP_SEND(fp,"			       lst*\n");
  LISP_SEND(fp,"			       (cons (cdr (fs-dep lst)) lst+)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"     ((eq '* (car lst))\n");
  LISP_SEND(fp,"      (do* (( dlst    (cdr lst)  (cdr dlst))\n");
  LISP_SEND(fp,"	    ( rlst     nil                 )\n");
  LISP_SEND(fp,"	    ( ptr     (car dlst) (car dlst))\n");
  LISP_SEND(fp,"	    ( get     (fs-dep-*x ptr lst* lst+) (fs-dep-*x ptr lst* lst+)))\n");
  LISP_SEND(fp,"	   ((null dlst) (list nil lst* lst+))\n");
  LISP_SEND(fp,"	   (setq lst* (cadr  get)\n");
  LISP_SEND(fp,"		 lst+ (caddr get)))))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun fs-dep-t (lst)\n");
  LISP_SEND(fp,"  (cond ((atom lst) lst)\n");
  LISP_SEND(fp,"	(t\n");
  LISP_SEND(fp,"	 (let (( rlst  (mapcar #'fs-dep-t lst) )\n");
  LISP_SEND(fp,"	       )\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"	   (cond ((atom rlst) rlst)\n");
  LISP_SEND(fp,"		 ((and (eq (car rlst) '^)(eq 0 (caddr rlst))) 1)\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"		 ((eq (car rlst) '*)\n");
  LISP_SEND(fp,"		  (if(member 0 rlst) 0\n");
  LISP_SEND(fp,"		    (if(member 1 rlst)\n");
  LISP_SEND(fp,"			(if(eq 3 (length rlst))\n");
  LISP_SEND(fp,"			    (if(eq 1 (cadr rlst)) (caddr rlst)(cadr rlst))\n");
  LISP_SEND(fp,"			  (fs-dep-t (list-sub rlst 1)));;in case more 1s in lst\n");
  LISP_SEND(fp,"		      rlst)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"		 ((eq (car rlst) '+)\n");
  LISP_SEND(fp,"		  (if(member 0 rlst)\n");
  LISP_SEND(fp,"		      (if(eq 3 (length rlst))\n");
  LISP_SEND(fp,"			  (if(eq 0 (cadr rlst)) (caddr rlst) (cadr rlst))\n");
  LISP_SEND(fp,"			(fs-dep-t (list-sub rlst 0))) ;; in case more 0s in lst\n");
  LISP_SEND(fp,"		    rlst))\n");
  LISP_SEND(fp,"		 (t rlst))))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun list-sub (lst atm)\n");
  LISP_SEND(fp,"  (cond ((equal atm (car lst)) (cdr lst))\n");
  LISP_SEND(fp,"	(t (cons (car lst) (list-sub (cdr lst) atm)))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun fs-undep (lst)\n");
  LISP_SEND(fp,"  (cond ((atom lst) lst)\n");
  LISP_SEND(fp,"	((eq '^ (car lst)) \n");
  LISP_SEND(fp,"	 (do ((num (caddr lst) (- num 1))\n");
  LISP_SEND(fp,"	      (rlst (list '* (cadr lst))) )\n");
  LISP_SEND(fp,"	     ((eq num 1) rlst)\n");
  LISP_SEND(fp,"	     (setq rlst (append rlst (list (cadr lst))))))\n");
  LISP_SEND(fp,"	(t (cons (fs-undep (car lst)) (fs-undep (cdr lst))))))\n");
}
