module mod_dcond1_1
contains

subroutine dcond1_1(mypeid,nprocs,     &
  nsetno,firstDramaNsetPtr,              &
  isumup,                                &
  enptr,con,nelem,                       &
  x,y,ipf,ipd,npmax,                     &
  enptr_ex,con_ex,nelem_ex,              &
  ndno,peno,x_ex,y_ex,ipf_ex,ipd_ex,nouter        &
,valmat,vfg,indrow,iptrcol,neq,ipd_halo,nhalo)
!--------------------------------------------------------
! Generated by  feelfem Copyright(c) 2000 NEC Corporation
!--------------------------------------------------------
! feelfem90/DRAMA Program Model
! 2001/11/14 11:50
!----------------------------------------------------
! FEM DataType
use femDataType
use dramaDataModel

use subSolveDrama     ! nd_search function
! general modules
use preport90
use numeric
use abortmodule
implicit none

integer,intent(in)           :: mypeid,nprocs
integer,intent(in)           :: nsetno
type(dramaNsetList),pointer  :: firstDramaNsetPtr

integer,dimension(nprocs)    :: isumup
integer,intent(in)           :: neq

integer,dimension(:,:)       :: enptr,con
integer,intent(in)           :: nelem

integer,intent(in)           :: npmax
real(kind=REAL8),dimension(:),pointer :: x,y
integer,dimension(npmax)     :: ipf,ipd

integer,dimension(:,:)       :: enptr_ex,con_ex
integer,intent(in)           :: nelem_ex
integer,intent(in)           :: nouter
integer,dimension(nouter)    :: ndno,peno,ipf_ex,ipd_ex
real(kind=REAL8),dimension(:),pointer :: x_ex,y_ex



integer                                  :: nhalo
integer,dimension(:),pointer             :: ipd_halo
real   (kind=REAL8),dimension(:),pointer :: valmat,vfg
integer,dimension(:)            ,pointer :: indrow,iptrcol

!------------------------------------------------------
!  auto variables for dirichlet
!------------------------------------------------------
integer                        :: i,j,k
integer                        :: nd
integer                        :: ind,ipe
integer                        :: iptf,iptt,iptf2,iptt2
integer                        :: iptf_all,iptt_all
integer                        :: irptr,irptr_local
integer                        :: ieq,jeq
integer                        :: nodes
integer                        :: np
integer,dimension(:,:),pointer :: dcon,dinfo
integer                        :: myeqfrom,myeqto

real(kind=REAL8)               :: x_dpt,y_dpt,u

myeqfrom = 1   ! AMG/CRS Global number for my equation
myeqto   = neq ! AMG/CRS Global number for my equation

call setdramanset(nsetno,firstDramaNsetPtr,nodes,np,dcon,dinfo)
!------------------------------------------------------
do 100 i=1,nodes

  ind = dcon(1,i)
  ipe = dcon(2,i)
!------------------------------------------------------
! If the Dirichlet node is in my PE region, row and column
! If the Dirichlet node is NOT in my PE region,
! and it relates my region, column
!------------------------------------------------------
  if(ipe .NE. mypeid) then
    nd = ndsearch_ex2(ind,ipe,ndno,peno,nouter)
    if(nd .LT. 1) goto 100

    ieq = 0
    jeq = ipd_halo(nd)+dinfo(1,i)+neq      ! PAMG/CRS

    x_dpt = x_ex(nd)
    y_dpt = y_ex(nd)

   else

    ieq = ipd(ind)+dinfo(1,i)
    jeq = ieq                   ! AMG/CRS local eq number for my own

    x_dpt = x(ind)
    y_dpt = y(ind)

  endif

   u = ((x_dpt*x_dpt)*x_dpt)+(y_dpt*y_dpt)

!---------------------------
! ieq local  equation number
! jeq global equation number
!---------------------------

!*********
! row ieq
!*********
   if(ieq .eq. 0) goto  150

   iptf = iptrcol(ieq  )
   iptt = iptrcol(ieq+1)-1

   do j=iptf,iptt
     if(indrow(j) .eq. jeq) then
       valmat(j) = 1.0d0
     else
       valmat(j) = 0.0d0
     endif
   end do   ! j=iptf,iptt
   vfg(ieq) = u

!**********
! column
!**********
 150 continue

  if( ieq  .ne. 0) then
!
! Assume non-zero element is symmetric
!
    iptf = iptrcol(ieq  )
    iptt = iptrcol(ieq+1)-1

    do 160 j=iptf,iptt
      irptr = indrow(j)
      if(irptr .LT. myeqfrom .OR. irptr .GT. myeqto) goto 160
      if(irptr .EQ. jeq ) goto 160

      irptr_local = irptr - myeqfrom+1
      if(irptr_local .LT. 1 .OR. irptr_local .GT. neq) then
        write(*,*) 'irptr_local ERROR ',irptr_local
        call abortexit(mypeid)
      endif

      iptf2 = iptrcol(irptr_local)
      iptt2 = iptrcol(irptr_local+1)-1
      do 165 k=iptf2,iptt2
        if(indrow(k) .eq. jeq) goto 170
 165  continue

!
      write(*,*) 'cannot find in dcond'
      call abortexit(mypeid)
!
 170   continue
      vfg(irptr_local)=vfg(irptr_local)-valmat(k)*u
      valmat(k) = 0.0d0
 160 continue

!
! end of my case
!
    else
!
! now search all!!!!!!!!!!!!!
!
    do 200 j=1,neq
     iptf_all = iptrcol(j)
     iptt_all = iptrcol(j+1)-1
     do 210 k=iptf_all,iptt_all
       if(indrow(k) .eq. jeq ) then
        vfg(j) = vfg(j) - valmat(k)*u
        valmat(k) =0.0d0
        goto 200
       endif
 210 continue
 200 continue
    endif
!
! end of column
!
 100  continue
!------------------------------------------------------

end subroutine dcond1_1
end module mod_dcond1_1
