      subroutine edev1_1(myrank,resvec,ipd,enptr,con,nelem,fem_u)
*------------------------------------------------------------
* Generated by feelfem Copyright(c) 1999-2001 NEC Corporation
*------------------------------------------------------------
* FEEL P2/DRAMA Program Model
* 2001/11/14 11:11
*----------------------------------------------------
      implicit real*8(a-h,o-z)
*------------------------------------------------------------
      integer*4 myrank
      real   *8 resvec(*)
      integer*4 ipd(*)
      integer*4 enptr(2,*)
      integer*4 con  (2,*)
      integer*4 nelem
*
      dimension fem_u(*)
*
      integer*4 ienp_u(3)
      integer*4 iedp_u(3)
*
      data ienp_u/ 1,2,3/
      data iedp_u/ 0,0,0/
*------------------------------------------------------------
      mypeid = myrank
*
      do 100 i=1,nelem
        ipos_from = enptr(1,i  )
        ipos_to   = enptr(1,i+1)-1
        nodes     = ipos_to-ipos_from+1
*
        do 110 j=1,3
        nnd = con(1,ipos_from+ienp_u(j)-1)
        npe = con(2,ipos_from+ienp_u(j)-1)
        if(npe .ne. mypeid) goto 110
        fem_u(nnd) = resvec(ipd(nnd) + iedp_u(j))
110     continue
*
100   continue
*------------------------------------------------------------
      return
      end
