#------------------------------------------------
#  feelfem makefile
#  Date : 2001/11/14 11:50
#
#------------------------------------------------
F90      = f90

LINKER   = $(F90)

FFLAGS   =

LIBDIR =
LIBS   =


.SUFFIXES: .f90 .o

.f90.o:
	$(F90) $(FFLAGS) $(INCLUDES) -c $<



PROGRAM  = feelgo

F90_BASIC_OBJS  =
F90_LIBRARY_OBJS=
F90_MODEL_OBJS  =
F90_PROBLEM_OBJS= elem1.o dcond1_1.o edev1_1.o \
                  mksolve1extdata.o pamg81param1_1.o \
                  solve1.o
F90_MAIN_OBJS   = feelfem.o
F90_MOD_OBJS    = $(F90_BASIC_OBJS) $(F90_LIBRARY_OBJS) \
                  $(F90_MODEL_OBJS) $(F90_PROBLEM_OBJS)


MOD_OBJS        = $(F90_MOD_OBJS)

MAIN_OBJS       = $(F90_MAIN_OBJS)

all  : feelgo

feelgo : $(MOD_OBJS) $(MAIN_OBJS)
	$(LINKER) -o feelgo $(MOD_OBJS) $(MAIN_OBJS) $(LIBDIR) $(LIBS)


clean :
	rm -r *.o feelgo *.mod
