#include <stdio.h>
#include "psplot.h"

ps_header( fp )
     FILE *fp;
{
  double width;
  width = (double)PSplot_linewidth / 10.0;

  fprintf(fp,"%%-------- First font variable ------------------------------\n");
  fprintf(fp,"/Font00 %s findfont %d scalefont def\n",
	     PSplot_font_name,PSplot_font_size[PSplot_font_ptr]);
  fprintf(fp,"%%-------- Default font set ---------------------------------\n");
  fprintf(fp,"Font00 setfont\n");
  fprintf(fp,"%%-------- Default line width--------------------------------\n");
  fprintf(fp,"%4.1lf setlinewidth\n",width);
  fprintf(fp,"%%-------- Define variables ---------------------------------\n");
  fprintf(fp,"/Xpos 0 def   \n");
  fprintf(fp,"/Ypos 0 def\n");
  fprintf(fp,"/Dxpos 0 def\n");
  fprintf(fp,"/Dypos 0 def\n");
  fprintf(fp,"%%-------- Define procedure for saving file size ------------\n");
  fprintf(fp,"/N { newpath } def\n");
  fprintf(fp,"/MT { moveto } def\n");
  fprintf(fp,"/LT { lineto } def\n");
  fprintf(fp,"/ST { stroke } def\n");
  fprintf(fp,"/CP { closepath } def\n");
  fprintf(fp,"/FL { fill      } def\n");
  fprintf(fp,"/SG { setgray   } def\n");
  fprintf(fp,"%%-------- show string migi zume  Tutorial p.42 -------------\n");
  fprintf(fp,"/RightShow\n");
  fprintf(fp,"{ dup stringwidth pop\n");
  fprintf(fp,"  4 -1 roll exch sub \n");
  fprintf(fp,"  3 -1 roll moveto\n");
  fprintf(fp,"  show } def\n");
  fprintf(fp,"/MiddleShow\n");
  fprintf(fp,"{ dup stringwidth pop\n");
  fprintf(fp,"  2 div\n");
  fprintf(fp,"  4 -1 roll exch sub\n");
  fprintf(fp,"  3 -1 roll moveto\n");
  fprintf(fp,"  show } def\n");
  fprintf(fp,"/SupShow\n");
  fprintf(fp,"{ /Fontsize exch def \n");
  fprintf(fp,"  4 -1 roll\n");
  fprintf(fp,"  dup /Xpos exch def\n");
  fprintf(fp,"  4 -1 roll\n");
  fprintf(fp,"  dup /Ypos exch def\n");
  fprintf(fp,"  moveto\n");
  fprintf(fp,"  exch dup stringwidth\n");
  fprintf(fp,"  2 div\n");
  fprintf(fp,"  Ypos add Fontsize 0.8 mul add /Ypos exch def\n");
  fprintf(fp,"  Xpos add /Xpos exch def\n");
  fprintf(fp,"  show\n");
  fprintf(fp,"  Xpos Ypos moveto\n");
  fprintf(fp,"  0.5 0.5 scale show\n");
  fprintf(fp,"  2.0 2.0 scale } def\n");
  fprintf(fp,"\n");
  fprintf(fp,"/SupMiddleShow\n");
  fprintf(fp,"{ /Fontsize exch def\n");
  fprintf(fp,"  4 -1 roll\n");
  fprintf(fp,"  /Xpos exch def\n");
  fprintf(fp,"  3 -1 roll\n");
  fprintf(fp,"  /Ypos exch def\n");
  fprintf(fp,"  exch dup stringwidth\n");
  fprintf(fp,"  /Dypos exch def\n");
  fprintf(fp,"  2 div /Dxpos exch def\n");
  fprintf(fp,"  Xpos Dxpos sub\n");
  fprintf(fp,"  Ypos \n");
  fprintf(fp,"  moveto\n");
  fprintf(fp,"  show\n");
  fprintf(fp,"  Xpos Dxpos add\n");
  fprintf(fp,"  Ypos Dypos add Fontsize 0.8 mul add moveto\n");
  fprintf(fp,"  0.5 0.5 scale show\n");
  fprintf(fp,"  2.0 2.0 scale } def\n");
  fprintf(fp,"\n");
  fprintf(fp,"/SupRightShow\n");
  fprintf(fp,"{ /Fontsize exch def\n");
  fprintf(fp,"  4 -1 roll\n");
  fprintf(fp,"  /Xpos exch def\n");
  fprintf(fp,"  3 -1 roll\n");
  fprintf(fp,"  /Ypos exch def\n");
  fprintf(fp,"  exch dup stringwidth\n");
  fprintf(fp,"  2 div /Dypos exch def\n");
  fprintf(fp,"  /Dxpos exch def\n");
  fprintf(fp,"  Xpos Dxpos sub \n");
  fprintf(fp,"  Ypos moveto\n");
  fprintf(fp,"  show\n");
  fprintf(fp,"  Xpos\n");
  fprintf(fp,"  Ypos Dypos add Fontsize 0.8 mul add\n");
  fprintf(fp,"  moveto\n");
  fprintf(fp,"  0.5 0.5 scale show\n");
  fprintf(fp,"  2.0 2.0 scale } def\n");
  fprintf(fp,"\n");
  fprintf(fp,"%%------------Centered Dash Patterns  CookBook p.141 --------------\n");
  fprintf(fp,"\n");
  fprintf(fp,"/centerdash\n");
  fprintf(fp,"{ /pattern exch def\n");
  fprintf(fp,"  /pathlen pathlength def\n");
  fprintf(fp,"  /patternlength 0 def\n");
  fprintf(fp,"  pattern\n");
  fprintf(fp,"  { patternlength add /patternlength exch def\n");
  fprintf(fp,"  } forall\n");
  fprintf(fp,"\n");
  fprintf(fp,"  pattern length 2 mod 0 ne\n");
  fprintf(fp,"   { /patternlength patternlength 2 mul def } if\n");
  fprintf(fp,"\n");
  fprintf(fp,"   /first pattern 0 get def\n");
  fprintf(fp,"\n");
  fprintf(fp,"   /last patternlength first sub def\n");
  fprintf(fp,"\n");
  fprintf(fp,"   /n pathlen last sub patternlength idiv def\n");
  fprintf(fp,"   /endpart pathlen patternlength n mul sub\n");
  fprintf(fp,"    last sub 2 div def\n");
  fprintf(fp,"\n");
  fprintf(fp,"   /offset first endpart sub def\n");
  fprintf(fp,"\n");
  fprintf(fp,"   pattern offset setdash\n");
  fprintf(fp,"   } def\n");
  fprintf(fp,"\n");
  fprintf(fp,"/pathlength\n");
  fprintf(fp,"{ flattenpath\n");
  fprintf(fp,"  /dist 0 def\n");
  fprintf(fp,"\n");
  fprintf(fp,"  { /yfirst exch def /xfirst exch def\n");
  fprintf(fp,"    /ymoveto yfirst def /xmoveto xfirst def }\n");
  fprintf(fp,"  { /ynext exch def /xnext exch def\n");
  fprintf(fp,"    /dist dist ynext yfirst sub dup mul\n");
  fprintf(fp,"    xnext xfirst sub dup mul add sqrt add def\n");
  fprintf(fp,"    /yfirst  ynext def /xfirst xnext def }\n");
  fprintf(fp,"    {}\n");
  fprintf(fp,"\n");
  fprintf(fp,"   {/ynext ymoveto def /xnext xmoveto def\n");
  fprintf(fp,"    /dist dist ynext yfirst sub dup mul\n");
  fprintf(fp,"      xnext xfirst sub dup mul add sqrt add def\n");
  fprintf(fp,"    /yfirst ynext def /xfirst xnext def}\n");
  fprintf(fp,"    pathforall\n");
  fprintf(fp,"    dist\n");
  fprintf(fp,"   } def\n");
  fprintf(fp,"%%-------- End of Pre definitions ---------------------------  \n");
}
