module mod_dcond1_1
contains

subroutine dcond1_1(nsetno,              &
  firstNsetPtr,              &
  x,y,z,ipf,ipd,ipd_u,npmax           &
,vkgs,vkgd,vkgi,ncof,vfg,kld,kh,neq)
!--------------------------------------------------------
! Generated by feelfem
!--------------------------------------------------------
! feelfem90 Program Model
! 2025/12/23 06:08
!----------------------------------------------------
! FEM DataType
use femDataType
use feelP2data

! general modules
use report90
use numeric
use abortmodule

implicit none


integer,intent(in)                      :: nsetno
type(nsetList),pointer                  :: firstNsetPtr

integer,intent(in)                      :: neq

integer,intent(in)                      :: npmax
real(kind=REAL8),dimension(:)  ,pointer :: x,y,z
integer                                 :: ipf(npmax),ipd(npmax)

integer                                 :: ipd_u(npmax)

real(kind=REAL8),dimension(:)  ,pointer :: vkgs,vkgd,vkgi,vfg
integer,dimension(:)  ,pointer          :: kld,kh
integer                                 :: ncof


!------------------------------------------------------
!  auto variables for dirichlet
!------------------------------------------------------
integer                                 :: nd
integer                                 :: ieq
integer                                 :: nodes
integer                                 :: np
integer,dimension(:,:),pointer          :: inset

real(kind=REAL8)                        :: x_dpt,y_dpt,z_dpt,u

integer                                 :: i,j,lp

call setP2nset(nsetno,firstNsetPtr,nodes,np,inset)
!------------------------------------------------------
do i=1,nodes

  nd  = inset(1,i)

!------------------------------------------------------
! Skip if no d.o.f is assigned at this node.
!------------------------------------------------------
  if(ipd_u(nd) == -1) cycle

  ieq = ipd(nd)+ipd_u(nd)

  x_dpt = x(nd)
  y_dpt = y(nd)
  z_dpt = z(nd)

  u = x_dpt*x_dpt+y_dpt*y_dpt+z_dpt*z_dpt


        do 110 j=1,neq

          if(ieq         .eq.   j) goto 110
          if(j           .gt. ieq) goto 105
          if(ieq-KH(ieq) .gt.   j) goto 110

          lp     = KLD(ieq+1) - ieq + j
          vfg(j) = vfg(j)     - u   * vkgs(lp)
          vkgs(lp)= 0.0d0
          goto 110

 105      if(j - KH(j) .gt. ieq) goto 110
          lp     = KLD(j+1)   - j + ieq
          vfg(j) = vfg(j)     - u * vkgi(lp)
          vkgi(lp)= 0.0d0

 110    continue

        do 120 j=1,neq
          if(ieq .eq. j) goto 121
          if(ieq .gt. j) goto 125

          if(j - KH(j) .gt. ieq) goto 120
          lp = KLD(j+1)-j+ieq
          vkgs(lp) = 0.0d0
          goto 120

 121      vkgd(ieq)  = 1.0d0
          vfg(ieq) = u
          goto 120

 125      if(ieq - KH(ieq) .gt. j) goto 120
          lp = KLD(ieq+1) - ieq + j
          vkgi(lp) = 0.0d0
 120    continue

end do   !(boundary node loop)
!------------------------------------------------------

end subroutine dcond1_1
end module mod_dcond1_1
