module mod_ecal1_1
contains

subroutine ecal1_1(x1,y1,z1,x2,y2,z2,x3,y3,z3,x4,y4,z4,x5,y5 &
,z5,x6,y6,z6,x7,y7,z7,x8,y8,z8,x9,y9,z9,x10,y10,z10)
!--------------------------------------------------------
! Generated by feelfem
!--------------------------------------------------------
! feelfem90 Program Model
! 2025/12/23 06:08
!----------------------------------------------------
! general modules
use report90
use numeric
use abortmodule

implicit none


real(kind=REAL8)                        :: x1,y1,z1
real(kind=REAL8)                        :: x2,y2,z2
real(kind=REAL8)                        :: x3,y3,z3
real(kind=REAL8)                        :: x4,y4,z4
real(kind=REAL8)                        :: x5,y5,z5
real(kind=REAL8)                        :: x6,y6,z6
real(kind=REAL8)                        :: x7,y7,z7
real(kind=REAL8)                        :: x8,y8,z8
real(kind=REAL8)                        :: x9,y9,z9
real(kind=REAL8)                        :: x10,y10,z10



!------------------------------------------------------
! Problem dependent parameters
!------------------------------------------------------
integer,parameter                       :: NDF = 8
integer,parameter                       :: NDP = 10
integer,parameter                       :: NPG1 =  4  ! No.1 [tet2]
!------------------------------------------------------

!------------------------------------------------------
! auto variables
!------------------------------------------------------
integer                                 :: i,j
integer                                 :: itp

real(kind=REAL8)                        :: rj(3,3),rij(3,3)
real(kind=REAL8)                        :: det,wt,val
real(kind=REAL8)                        :: qx,qy,qz

real(kind=REAL8)                        :: ea,eb

!------------------------------------------------------
! Gauss-point terms
!------------------------------------------------------
real(kind=REAL8)                        :: gx_1,gy_1,gz_1,w_1

real(kind=REAL8)                        :: rT1_1_1
real(kind=REAL8)                        :: rT1_1_x_1
real(kind=REAL8)                        :: rT1_1_y_1
real(kind=REAL8)                        :: rT1_1_z_1
real(kind=REAL8)                        :: rT1_2_1
real(kind=REAL8)                        :: rT1_2_x_1
real(kind=REAL8)                        :: rT1_2_y_1
real(kind=REAL8)                        :: rT1_2_z_1
real(kind=REAL8)                        :: rT1_3_1
real(kind=REAL8)                        :: rT1_3_x_1
real(kind=REAL8)                        :: rT1_3_y_1
real(kind=REAL8)                        :: rT1_3_z_1
real(kind=REAL8)                        :: rT1_4_1
real(kind=REAL8)                        :: rT1_4_x_1
real(kind=REAL8)                        :: rT1_4_y_1
real(kind=REAL8)                        :: rT1_4_z_1
real(kind=REAL8)                        :: rT2_10_1
real(kind=REAL8)                        :: rT2_10_x_1
real(kind=REAL8)                        :: rT2_10_y_1
real(kind=REAL8)                        :: rT2_10_z_1
real(kind=REAL8)                        :: rT2_1_1
real(kind=REAL8)                        :: rT2_1_x_1
real(kind=REAL8)                        :: rT2_1_y_1
real(kind=REAL8)                        :: rT2_1_z_1
real(kind=REAL8)                        :: rT2_2_1
real(kind=REAL8)                        :: rT2_2_x_1
real(kind=REAL8)                        :: rT2_2_y_1
real(kind=REAL8)                        :: rT2_2_z_1
real(kind=REAL8)                        :: rT2_3_1
real(kind=REAL8)                        :: rT2_3_x_1
real(kind=REAL8)                        :: rT2_3_y_1
real(kind=REAL8)                        :: rT2_3_z_1
real(kind=REAL8)                        :: rT2_4_1
real(kind=REAL8)                        :: rT2_4_x_1
real(kind=REAL8)                        :: rT2_4_y_1
real(kind=REAL8)                        :: rT2_4_z_1
real(kind=REAL8)                        :: rT2_5_1
real(kind=REAL8)                        :: rT2_5_x_1
real(kind=REAL8)                        :: rT2_5_y_1
real(kind=REAL8)                        :: rT2_5_z_1
real(kind=REAL8)                        :: rT2_6_1
real(kind=REAL8)                        :: rT2_6_x_1
real(kind=REAL8)                        :: rT2_6_y_1
real(kind=REAL8)                        :: rT2_6_z_1
real(kind=REAL8)                        :: rT2_7_1
real(kind=REAL8)                        :: rT2_7_x_1
real(kind=REAL8)                        :: rT2_7_y_1
real(kind=REAL8)                        :: rT2_7_z_1
real(kind=REAL8)                        :: rT2_8_1
real(kind=REAL8)                        :: rT2_8_x_1
real(kind=REAL8)                        :: rT2_8_y_1
real(kind=REAL8)                        :: rT2_8_z_1
real(kind=REAL8)                        :: rT2_9_1
real(kind=REAL8)                        :: rT2_9_x_1
real(kind=REAL8)                        :: rT2_9_y_1
real(kind=REAL8)                        :: rT2_9_z_1
real(kind=REAL8)                        :: rTEST1_1_1
real(kind=REAL8)                        :: rTEST1_1_x_1
real(kind=REAL8)                        :: rTEST1_1_y_1
real(kind=REAL8)                        :: rTEST1_1_z_1
real(kind=REAL8)                        :: rTEST1_2_1
real(kind=REAL8)                        :: rTEST1_2_x_1
real(kind=REAL8)                        :: rTEST1_2_y_1
real(kind=REAL8)                        :: rTEST1_2_z_1
real(kind=REAL8)                        :: rTEST1_3_1
real(kind=REAL8)                        :: rTEST1_3_x_1
real(kind=REAL8)                        :: rTEST1_3_y_1
real(kind=REAL8)                        :: rTEST1_3_z_1
real(kind=REAL8)                        :: rTEST1_4_1
real(kind=REAL8)                        :: rTEST1_4_x_1
real(kind=REAL8)                        :: rTEST1_4_y_1
real(kind=REAL8)                        :: rTEST1_4_z_1


!------------------------------------------------------
! Integrand terms
!------------------------------------------------------
real(kind=REAL8)                        :: qT1_1
real(kind=REAL8)                        :: qT1_1_x
real(kind=REAL8)                        :: qT1_1_y
real(kind=REAL8)                        :: qT1_1_z
real(kind=REAL8)                        :: qT1_2
real(kind=REAL8)                        :: qT1_2_x
real(kind=REAL8)                        :: qT1_2_y
real(kind=REAL8)                        :: qT1_2_z
real(kind=REAL8)                        :: qT1_3
real(kind=REAL8)                        :: qT1_3_x
real(kind=REAL8)                        :: qT1_3_y
real(kind=REAL8)                        :: qT1_3_z
real(kind=REAL8)                        :: qT1_4
real(kind=REAL8)                        :: qT1_4_x
real(kind=REAL8)                        :: qT1_4_y
real(kind=REAL8)                        :: qT1_4_z
real(kind=REAL8)                        :: qTEST1_1
real(kind=REAL8)                        :: qTEST1_1_x
real(kind=REAL8)                        :: qTEST1_1_y
real(kind=REAL8)                        :: qTEST1_1_z
real(kind=REAL8)                        :: qTEST1_2
real(kind=REAL8)                        :: qTEST1_2_x
real(kind=REAL8)                        :: qTEST1_2_y
real(kind=REAL8)                        :: qTEST1_2_z
real(kind=REAL8)                        :: qTEST1_3
real(kind=REAL8)                        :: qTEST1_3_x
real(kind=REAL8)                        :: qTEST1_3_y
real(kind=REAL8)                        :: qTEST1_3_z
real(kind=REAL8)                        :: qTEST1_4
real(kind=REAL8)                        :: qTEST1_4_x
real(kind=REAL8)                        :: qTEST1_4_y
real(kind=REAL8)                        :: qTEST1_4_z

!------------------------------------------------------
! common block for element matrix and load vector
!------------------------------------------------------
common /em1_1/ ea(NDF,NDF),eb(NDF)


!------------------------------------------------------
! common block for quadrature
!------------------------------------------------------
common /em1_1_1/gx_1(NPG1),gy_1(NPG1),gz_1(NPG1),w_1(NPG1) &
,rT1_1_1(NPG1),rT1_1_x_1(NPG1),rT1_1_y_1(NPG1),rT1_1_z_1(NPG1) &
,rT1_2_1(NPG1),rT1_2_x_1(NPG1),rT1_2_y_1(NPG1),rT1_2_z_1(NPG1) &
,rT1_3_1(NPG1),rT1_3_x_1(NPG1),rT1_3_y_1(NPG1),rT1_3_z_1(NPG1) &
,rT1_4_1(NPG1),rT1_4_x_1(NPG1),rT1_4_y_1(NPG1),rT1_4_z_1(NPG1) &
,rT2_10_1(NPG1),rT2_10_x_1(NPG1),rT2_10_y_1(NPG1),rT2_10_z_1 &
(NPG1),rT2_1_1(NPG1),rT2_1_x_1(NPG1),rT2_1_y_1(NPG1),rT2_1_z_1 &
(NPG1),rT2_2_1(NPG1),rT2_2_x_1(NPG1),rT2_2_y_1(NPG1),rT2_2_z_1 &
(NPG1),rT2_3_1(NPG1),rT2_3_x_1(NPG1),rT2_3_y_1(NPG1),rT2_3_z_1 &
(NPG1),rT2_4_1(NPG1),rT2_4_x_1(NPG1),rT2_4_y_1(NPG1),rT2_4_z_1 &
(NPG1),rT2_5_1(NPG1),rT2_5_x_1(NPG1),rT2_5_y_1(NPG1),rT2_5_z_1 &
(NPG1),rT2_6_1(NPG1),rT2_6_x_1(NPG1),rT2_6_y_1(NPG1),rT2_6_z_1 &
(NPG1),rT2_7_1(NPG1),rT2_7_x_1(NPG1),rT2_7_y_1(NPG1),rT2_7_z_1 &
(NPG1),rT2_8_1(NPG1),rT2_8_x_1(NPG1),rT2_8_y_1(NPG1),rT2_8_z_1 &
(NPG1),rT2_9_1(NPG1),rT2_9_x_1(NPG1),rT2_9_y_1(NPG1),rT2_9_z_1 &
(NPG1),rTEST1_1_1(NPG1),rTEST1_1_x_1(NPG1),rTEST1_1_y_1(NPG1) &
,rTEST1_1_z_1(NPG1),rTEST1_2_1(NPG1),rTEST1_2_x_1(NPG1),rTEST1_2_y_1 &
(NPG1),rTEST1_2_z_1(NPG1),rTEST1_3_1(NPG1),rTEST1_3_x_1(NPG1) &
,rTEST1_3_y_1(NPG1),rTEST1_3_z_1(NPG1),rTEST1_4_1(NPG1),rTEST1_4_x_1 &
(NPG1),rTEST1_4_y_1(NPG1),rTEST1_4_z_1(NPG1)

!------------------------------------------------------
do i=1,NDF
 eb(i) = 0.0d0
end do

do j=1,NDF
 do i=1,NDF
  ea(i,j) = 0.0d0
 end do
end do
!------------------------------------------------------
!------------------------------------------------------
! Quadrature No.1
!------------------------------------------------------
do itp=1,NPG1

  rj(1,1) = x1*rT2_1_x_1(itp)+x2*rT2_2_x_1(itp)+x3*rT2_3_x_1 &
(itp)+x4*rT2_4_x_1(itp)+x5*rT2_5_x_1(itp)+x6*rT2_6_x_1(itp)+x7 &
*rT2_7_x_1(itp)+x8*rT2_8_x_1(itp)+x9*rT2_9_x_1(itp)+x10*rT2_10_x_1(itp)
  rj(1,2) = y1*rT2_1_x_1(itp)+y2*rT2_2_x_1(itp)+y3*rT2_3_x_1 &
(itp)+y4*rT2_4_x_1(itp)+y5*rT2_5_x_1(itp)+y6*rT2_6_x_1(itp)+y7 &
*rT2_7_x_1(itp)+y8*rT2_8_x_1(itp)+y9*rT2_9_x_1(itp)+y10*rT2_10_x_1(itp)
  rj(1,3) = z1*rT2_1_x_1(itp)+z2*rT2_2_x_1(itp)+z3*rT2_3_x_1 &
(itp)+z4*rT2_4_x_1(itp)+z5*rT2_5_x_1(itp)+z6*rT2_6_x_1(itp)+z7 &
*rT2_7_x_1(itp)+z8*rT2_8_x_1(itp)+z9*rT2_9_x_1(itp)+z10*rT2_10_x_1(itp)
  rj(2,1) = x1*rT2_1_y_1(itp)+x2*rT2_2_y_1(itp)+x3*rT2_3_y_1 &
(itp)+x4*rT2_4_y_1(itp)+x5*rT2_5_y_1(itp)+x6*rT2_6_y_1(itp)+x7 &
*rT2_7_y_1(itp)+x8*rT2_8_y_1(itp)+x9*rT2_9_y_1(itp)+x10*rT2_10_y_1(itp)
  rj(2,2) = y1*rT2_1_y_1(itp)+y2*rT2_2_y_1(itp)+y3*rT2_3_y_1 &
(itp)+y4*rT2_4_y_1(itp)+y5*rT2_5_y_1(itp)+y6*rT2_6_y_1(itp)+y7 &
*rT2_7_y_1(itp)+y8*rT2_8_y_1(itp)+y9*rT2_9_y_1(itp)+y10*rT2_10_y_1(itp)
  rj(2,3) = z1*rT2_1_y_1(itp)+z2*rT2_2_y_1(itp)+z3*rT2_3_y_1 &
(itp)+z4*rT2_4_y_1(itp)+z5*rT2_5_y_1(itp)+z6*rT2_6_y_1(itp)+z7 &
*rT2_7_y_1(itp)+z8*rT2_8_y_1(itp)+z9*rT2_9_y_1(itp)+z10*rT2_10_y_1(itp)
  rj(3,1) = x1*rT2_1_z_1(itp)+x2*rT2_2_z_1(itp)+x3*rT2_3_z_1 &
(itp)+x4*rT2_4_z_1(itp)+x5*rT2_5_z_1(itp)+x6*rT2_6_z_1(itp)+x7 &
*rT2_7_z_1(itp)+x8*rT2_8_z_1(itp)+x9*rT2_9_z_1(itp)+x10*rT2_10_z_1(itp)
  rj(3,2) = y1*rT2_1_z_1(itp)+y2*rT2_2_z_1(itp)+y3*rT2_3_z_1 &
(itp)+y4*rT2_4_z_1(itp)+y5*rT2_5_z_1(itp)+y6*rT2_6_z_1(itp)+y7 &
*rT2_7_z_1(itp)+y8*rT2_8_z_1(itp)+y9*rT2_9_z_1(itp)+y10*rT2_10_z_1(itp)
  rj(3,3) = z1*rT2_1_z_1(itp)+z2*rT2_2_z_1(itp)+z3*rT2_3_z_1 &
(itp)+z4*rT2_4_z_1(itp)+z5*rT2_5_z_1(itp)+z6*rT2_6_z_1(itp)+z7 &
*rT2_7_z_1(itp)+z8*rT2_8_z_1(itp)+z9*rT2_9_z_1(itp)+z10*rT2_10_z_1(itp)

  det =  rj(1,1)*rj(2,2)*rj(3,3)  &
       + rj(1,2)*rj(2,3)*rj(3,1)  &
       + rj(1,3)*rj(2,1)*rj(3,2)  &
       - rj(1,1)*rj(2,3)*rj(3,2)  &
       - rj(1,2)*rj(2,1)*rj(3,3)  &
       - rj(1,3)*rj(2,2)*rj(3,1)

  rij(1,1)=      (rj(2,2)*rj(3,3)-rj(2,3)*rj(3,2))/det
  rij(1,2)= -1.0*(rj(1,2)*rj(3,3)-rj(1,3)*rj(3,2))/det
  rij(1,3)=      (rj(1,2)*rj(2,3)-rj(1,3)*rj(2,2))/det
  rij(2,1)= -1.0*(rj(2,1)*rj(3,3)-rj(2,3)*rj(3,1))/det
  rij(2,2)=      (rj(1,1)*rj(3,3)-rj(1,3)*rj(3,1))/det
  rij(2,3)= -1.0*(rj(1,1)*rj(2,3)-rj(1,3)*rj(2,1))/det
  rij(3,1)=      (rj(2,1)*rj(3,2)-rj(2,2)*rj(3,1))/det
  rij(3,2)= -1.0*(rj(1,1)*rj(3,2)-rj(1,2)*rj(3,1))/det
  rij(3,3)=      (rj(1,1)*rj(2,2)-rj(1,2)*rj(2,1))/det

  wt = det * w_1(itp)

!------------------------------------------------------
  qT1_1= rT1_1_1(itp)
  qT1_2= rT1_2_1(itp)
  qT1_3= rT1_3_1(itp)
  qT1_4= rT1_4_1(itp)
  qT1_1_x = rT1_1_x_1(itp)*rij(1,1)+rT1_1_y_1(itp)*rij(1,2)+rT1_1_z_1 &
(itp)*rij(1,3)
  qT1_2_x = rT1_2_x_1(itp)*rij(1,1)+rT1_2_y_1(itp)*rij(1,2)+rT1_2_z_1 &
(itp)*rij(1,3)
  qT1_3_x = rT1_3_x_1(itp)*rij(1,1)+rT1_3_y_1(itp)*rij(1,2)+rT1_3_z_1 &
(itp)*rij(1,3)
  qT1_4_x = rT1_4_x_1(itp)*rij(1,1)+rT1_4_y_1(itp)*rij(1,2)+rT1_4_z_1 &
(itp)*rij(1,3)
  qT1_1_y = rT1_1_x_1(itp)*rij(2,1)+rT1_1_y_1(itp)*rij(2,2)+rT1_1_z_1 &
(itp)*rij(2,3)
  qT1_2_y = rT1_2_x_1(itp)*rij(2,1)+rT1_2_y_1(itp)*rij(2,2)+rT1_2_z_1 &
(itp)*rij(2,3)
  qT1_3_y = rT1_3_x_1(itp)*rij(2,1)+rT1_3_y_1(itp)*rij(2,2)+rT1_3_z_1 &
(itp)*rij(2,3)
  qT1_4_y = rT1_4_x_1(itp)*rij(2,1)+rT1_4_y_1(itp)*rij(2,2)+rT1_4_z_1 &
(itp)*rij(2,3)
  qT1_1_z = rT1_1_x_1(itp)*rij(3,1)+rT1_1_y_1(itp)*rij(3,2)+rT1_1_z_1 &
(itp)*rij(3,3)
  qT1_2_z = rT1_2_x_1(itp)*rij(3,1)+rT1_2_y_1(itp)*rij(3,2)+rT1_2_z_1 &
(itp)*rij(3,3)
  qT1_3_z = rT1_3_x_1(itp)*rij(3,1)+rT1_3_y_1(itp)*rij(3,2)+rT1_3_z_1 &
(itp)*rij(3,3)
  qT1_4_z = rT1_4_x_1(itp)*rij(3,1)+rT1_4_y_1(itp)*rij(3,2)+rT1_4_z_1 &
(itp)*rij(3,3)
  qTEST1_1= rTEST1_1_1(itp)
  qTEST1_2= rTEST1_2_1(itp)
  qTEST1_3= rTEST1_3_1(itp)
  qTEST1_4= rTEST1_4_1(itp)
  qTEST1_1_x = rTEST1_1_x_1(itp)*rij(1,1)+rTEST1_1_y_1(itp)*rij &
(1,2)+rTEST1_1_z_1(itp)*rij(1,3)
  qTEST1_2_x = rTEST1_2_x_1(itp)*rij(1,1)+rTEST1_2_y_1(itp)*rij &
(1,2)+rTEST1_2_z_1(itp)*rij(1,3)
  qTEST1_3_x = rTEST1_3_x_1(itp)*rij(1,1)+rTEST1_3_y_1(itp)*rij &
(1,2)+rTEST1_3_z_1(itp)*rij(1,3)
  qTEST1_4_x = rTEST1_4_x_1(itp)*rij(1,1)+rTEST1_4_y_1(itp)*rij &
(1,2)+rTEST1_4_z_1(itp)*rij(1,3)
  qTEST1_1_y = rTEST1_1_x_1(itp)*rij(2,1)+rTEST1_1_y_1(itp)*rij &
(2,2)+rTEST1_1_z_1(itp)*rij(2,3)
  qTEST1_2_y = rTEST1_2_x_1(itp)*rij(2,1)+rTEST1_2_y_1(itp)*rij &
(2,2)+rTEST1_2_z_1(itp)*rij(2,3)
  qTEST1_3_y = rTEST1_3_x_1(itp)*rij(2,1)+rTEST1_3_y_1(itp)*rij &
(2,2)+rTEST1_3_z_1(itp)*rij(2,3)
  qTEST1_4_y = rTEST1_4_x_1(itp)*rij(2,1)+rTEST1_4_y_1(itp)*rij &
(2,2)+rTEST1_4_z_1(itp)*rij(2,3)
  qTEST1_1_z = rTEST1_1_x_1(itp)*rij(3,1)+rTEST1_1_y_1(itp)*rij &
(3,2)+rTEST1_1_z_1(itp)*rij(3,3)
  qTEST1_2_z = rTEST1_2_x_1(itp)*rij(3,1)+rTEST1_2_y_1(itp)*rij &
(3,2)+rTEST1_2_z_1(itp)*rij(3,3)
  qTEST1_3_z = rTEST1_3_x_1(itp)*rij(3,1)+rTEST1_3_y_1(itp)*rij &
(3,2)+rTEST1_3_z_1(itp)*rij(3,3)
  qTEST1_4_z = rTEST1_4_x_1(itp)*rij(3,1)+rTEST1_4_y_1(itp)*rij &
(3,2)+rTEST1_4_z_1(itp)*rij(3,3)
!------------------------------------------------------
!------------------------------------------------------
  ea(1,1)=ea(1,1)+((fem_v_1*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3 &
*qTEST1_3+fem_v_4*qTEST1_4)*qT1_1_x**2+qT1_1_y**2+qT1_1_z**2)*wt

  ea(1,2)=ea(1,2)+((fem_v_1*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3 &
*qTEST1_3+fem_v_4*qTEST1_4)*qT1_1_x*qT1_2_x+qT1_2_y*qT1_1_y+qT1_1_z &
*qT1_2_z)*wt

  ea(1,3)=ea(1,3)+(qT1_1_z*qT1_3_z+(fem_v_1*qTEST1_1+qTEST1_2 &
*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_3_x*qT1_1_x+qT1_3_y &
*qT1_1_y)*wt

  ea(1,4)=ea(1,4)+(qT1_4_y*qT1_1_y+qT1_1_z*qT1_4_z+(fem_v_1*qTEST1_1 &
+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_4_x*qT1_1_x)*wt

  ea(1,5)=ea(1,5)+(qTEST1_1*qT1_1_x*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(1,6)=ea(1,6)+(qTEST1_2*qT1_1_x*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(1,7)=ea(1,7)+(qTEST1_3*qT1_1_x*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(1,8)=ea(1,8)+(qT1_1_x*qTEST1_4*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(2,1)=ea(2,1)+((fem_v_1*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3 &
*qTEST1_3+fem_v_4*qTEST1_4)*qT1_1_x*qT1_2_x+qT1_2_y*qT1_1_y+qT1_1_z &
*qT1_2_z)*wt

  ea(2,2)=ea(2,2)+((fem_v_1*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3 &
*qTEST1_3+fem_v_4*qTEST1_4)*qT1_2_x**2+qT1_2_y**2+qT1_2_z**2)*wt

  ea(2,3)=ea(2,3)+(qT1_2_y*qT1_3_y+(fem_v_1*qTEST1_1+qTEST1_2 &
*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_3_x*qT1_2_x+qT1_2_z &
*qT1_3_z)*wt

  ea(2,4)=ea(2,4)+(qT1_4_y*qT1_2_y+qT1_2_z*qT1_4_z+(fem_v_1*qTEST1_1 &
+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_4_x*qT1_2_x)*wt

  ea(2,5)=ea(2,5)+(qTEST1_1*(fem_u_1*qT1_1_x+fem_u_2*qT1_2_x &
+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3)*qT1_2_x)*wt

  ea(2,6)=ea(2,6)+(qTEST1_2*(fem_u_1*qT1_1_x+fem_u_2*qT1_2_x &
+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3)*qT1_2_x)*wt

  ea(2,7)=ea(2,7)+(qTEST1_3*(fem_u_1*qT1_1_x+fem_u_2*qT1_2_x &
+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3)*qT1_2_x)*wt

  ea(2,8)=ea(2,8)+(qTEST1_4*(fem_u_1*qT1_1_x+fem_u_2*qT1_2_x &
+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3)*qT1_2_x)*wt

  ea(3,1)=ea(3,1)+(qT1_1_z*qT1_3_z+(fem_v_1*qTEST1_1+qTEST1_2 &
*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_3_x*qT1_1_x+qT1_3_y &
*qT1_1_y)*wt

  ea(3,2)=ea(3,2)+(qT1_2_y*qT1_3_y+(fem_v_1*qTEST1_1+qTEST1_2 &
*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_3_x*qT1_2_x+qT1_2_z &
*qT1_3_z)*wt

  ea(3,3)=ea(3,3)+(qT1_3_y**2+qT1_3_z**2+(fem_v_1*qTEST1_1+qTEST1_2 &
*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_3_x**2)*wt

  ea(3,4)=ea(3,4)+((fem_v_1*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3 &
*qTEST1_3+fem_v_4*qTEST1_4)*qT1_3_x*qT1_4_x+qT1_3_z*qT1_4_z+qT1_4_y &
*qT1_3_y)*wt

  ea(3,5)=ea(3,5)+(qTEST1_1*qT1_3_x*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(3,6)=ea(3,6)+(qTEST1_2*qT1_3_x*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(3,7)=ea(3,7)+(qTEST1_3*qT1_3_x*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(3,8)=ea(3,8)+(qT1_3_x*qTEST1_4*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(4,1)=ea(4,1)+(qT1_4_y*qT1_1_y+qT1_1_z*qT1_4_z+(fem_v_1*qTEST1_1 &
+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_4_x*qT1_1_x)*wt

  ea(4,2)=ea(4,2)+(qT1_4_y*qT1_2_y+qT1_2_z*qT1_4_z+(fem_v_1*qTEST1_1 &
+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_4_x*qT1_2_x)*wt

  ea(4,3)=ea(4,3)+((fem_v_1*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3 &
*qTEST1_3+fem_v_4*qTEST1_4)*qT1_3_x*qT1_4_x+qT1_3_z*qT1_4_z+qT1_4_y &
*qT1_3_y)*wt

  ea(4,4)=ea(4,4)+(qT1_4_z**2+(fem_v_1*qTEST1_1+qTEST1_2*fem_v_2 &
+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_4_x**2+qT1_4_y**2)*wt

  ea(4,5)=ea(4,5)+(qTEST1_1*qT1_4_x*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(4,6)=ea(4,6)+(qTEST1_2*qT1_4_x*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(4,7)=ea(4,7)+(qTEST1_3*qT1_4_x*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(4,8)=ea(4,8)+(qT1_4_x*qTEST1_4*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(5,1)=ea(5,1)+(qTEST1_1_y*qT1_1_y+qT1_1_z*qTEST1_1_z+(fem_v_1 &
*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4) &
*qTEST1_1_x*qT1_1_x)*wt

  ea(5,2)=ea(5,2)+(qT1_2_z*qTEST1_1_z+qTEST1_1_y*qT1_2_y+(fem_v_1 &
*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4) &
*qTEST1_1_x*qT1_2_x)*wt

  ea(5,3)=ea(5,3)+(qTEST1_1_z*qT1_3_z+(fem_v_1*qTEST1_1+qTEST1_2 &
*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qTEST1_1_x*qT1_3_x &
+qTEST1_1_y*qT1_3_y)*wt

  ea(5,4)=ea(5,4)+((fem_v_1*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3 &
*qTEST1_3+fem_v_4*qTEST1_4)*qTEST1_1_x*qT1_4_x+qTEST1_1_z*qT1_4_z &
+qT1_4_y*qTEST1_1_y)*wt

  ea(5,5)=ea(5,5)+(qTEST1_1_x*qTEST1_1*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(5,6)=ea(5,6)+(qTEST1_1_x*qTEST1_2*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(5,7)=ea(5,7)+(qTEST1_1_x*qTEST1_3*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(5,8)=ea(5,8)+(qTEST1_1_x*qTEST1_4*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(6,1)=ea(6,1)+(qT1_1_z*qTEST1_2_z+qT1_1_y*qTEST1_2_y+(fem_v_1 &
*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4) &
*qTEST1_2_x*qT1_1_x)*wt

  ea(6,2)=ea(6,2)+(qT1_2_y*qTEST1_2_y+qT1_2_z*qTEST1_2_z+(fem_v_1 &
*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4) &
*qTEST1_2_x*qT1_2_x)*wt

  ea(6,3)=ea(6,3)+(qT1_3_y*qTEST1_2_y+(fem_v_1*qTEST1_1+qTEST1_2 &
*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qTEST1_2_x*qT1_3_x &
+qTEST1_2_z*qT1_3_z)*wt

  ea(6,4)=ea(6,4)+(qTEST1_2_z*qT1_4_z+(fem_v_1*qTEST1_1+qTEST1_2 &
*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qTEST1_2_x*qT1_4_x &
+qT1_4_y*qTEST1_2_y)*wt

  ea(6,5)=ea(6,5)+(qTEST1_2_x*qTEST1_1*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(6,6)=ea(6,6)+(qTEST1_2_x*qTEST1_2*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(6,7)=ea(6,7)+(qTEST1_3*qTEST1_2_x*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(6,8)=ea(6,8)+(qTEST1_2_x*qTEST1_4*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(7,1)=ea(7,1)+(qTEST1_3_x*(fem_v_1*qTEST1_1+qTEST1_2*fem_v_2 &
+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_1_x+qT1_1_z*qTEST1_3_z &
+qTEST1_3_y*qT1_1_y)*wt

  ea(7,2)=ea(7,2)+(qTEST1_3_y*qT1_2_y+qTEST1_3_x*(fem_v_1*qTEST1_1 &
+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_2_x &
+qT1_2_z*qTEST1_3_z)*wt

  ea(7,3)=ea(7,3)+(qTEST1_3_y*qT1_3_y+qTEST1_3_z*qT1_3_z+qTEST1_3_x &
*(fem_v_1*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4 &
*qTEST1_4)*qT1_3_x)*wt

  ea(7,4)=ea(7,4)+(qTEST1_3_z*qT1_4_z+qTEST1_3_x*(fem_v_1*qTEST1_1 &
+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qT1_4_x &
+qTEST1_3_y*qT1_4_y)*wt

  ea(7,5)=ea(7,5)+(qTEST1_3_x*qTEST1_1*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(7,6)=ea(7,6)+(qTEST1_3_x*qTEST1_2*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(7,7)=ea(7,7)+(qTEST1_3_x*qTEST1_3*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(7,8)=ea(7,8)+(qTEST1_3_x*qTEST1_4*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(8,1)=ea(8,1)+((fem_v_1*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3 &
*qTEST1_3+fem_v_4*qTEST1_4)*qTEST1_4_x*qT1_1_x+qT1_1_z*qTEST1_4_z &
+qT1_1_y*qTEST1_4_y)*wt

  ea(8,2)=ea(8,2)+(qT1_2_z*qTEST1_4_z+(fem_v_1*qTEST1_1+qTEST1_2 &
*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qTEST1_4_x*qT1_2_x &
+qT1_2_y*qTEST1_4_y)*wt

  ea(8,3)=ea(8,3)+(qTEST1_4_z*qT1_3_z+(fem_v_1*qTEST1_1+qTEST1_2 &
*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4)*qTEST1_4_x*qT1_3_x &
+qT1_3_y*qTEST1_4_y)*wt

  ea(8,4)=ea(8,4)+(qT1_4_y*qTEST1_4_y+qTEST1_4_z*qT1_4_z+(fem_v_1 &
*qTEST1_1+qTEST1_2*fem_v_2+fem_v_3*qTEST1_3+fem_v_4*qTEST1_4) &
*qTEST1_4_x*qT1_4_x)*wt

  ea(8,5)=ea(8,5)+(qTEST1_4_x*qTEST1_1*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(8,6)=ea(8,6)+(qTEST1_4_x*qTEST1_2*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(8,7)=ea(8,7)+(qTEST1_4_x*qTEST1_3*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt

  ea(8,8)=ea(8,8)+(qTEST1_4_x*qTEST1_4*(fem_u_1*qT1_1_x+fem_u_2 &
*qT1_2_x+fem_u_4*qT1_4_x+qT1_3_x*fem_u_3))*wt


  eb(1)=eb(1)+(-(6.0)*qT1_1)*wt

  eb(2)=eb(2)+(-(6.0)*qT1_2)*wt

  eb(3)=eb(3)+(-(6.0)*qT1_3)*wt

  eb(4)=eb(4)+(-(6.0)*qT1_4)*wt

  eb(5)=eb(5)+(-(6.0)*qT1_4)*wt

  eb(6)=eb(6)+(-(6.0)*qT1_4)*wt

  eb(7)=eb(7)+(-(6.0)*qT1_4)*wt

  eb(8)=eb(8)+(-(6.0)*qT1_4)*wt

!------------------------------------------------------

end do    ! end of Quad. No.1

end subroutine ecal1_1
end module mod_ecal1_1
