module mod_edev1_1
contains

subroutine edev1_1(resvec,ipd,ielem,nelem,np,fem_u,fem_v)
!--------------------------------------------------------
! Generated by feelfem
!--------------------------------------------------------
! feelfem90 Program Model
! 2025/12/23 07:01
!----------------------------------------------------
use numeric
implicit none


real(kind=REAL8),dimension(:)  ,pointer :: resvec
integer,dimension(:)  ,pointer          :: ipd
integer,dimension(:,:),pointer          :: ielem
integer,intent(in)                      :: nelem,np

real(kind=REAL8),dimension(:)  ,pointer :: fem_u
real(kind=REAL8),dimension(:)  ,pointer :: fem_v

! auto variables
integer                                 :: i,j
integer                                 :: nd
integer,dimension(4)                    :: ienp_u,iedp_u
integer,dimension(4)                    :: ienp_v,iedp_v

! data statements
data ienp_u/ 1,2,3,4/
data iedp_u/ 0,0,0,0/
data ienp_v/ 1,2,3,4/
data iedp_v/ 1,1,1,1/
!------------------------------------------------------

do i=1,nelem

 do j=1,4
  nd = ielem(ienp_u(j),i)
  fem_u(nd)= resvec(ipd(nd) + iedp_u(j))
 end do

 do j=1,4
  nd = ielem(ienp_v(j),i)
  fem_v(nd)= resvec(ipd(nd) + iedp_v(j))
 end do

end do

end subroutine edev1_1
end module mod_edev1_1
