module mod_elem1
contains

subroutine elem1(ielem,matno,nelem,np,        &
                 x,y,z,ipf,ipd,npmax           &
     ,vkgs,vkgd,vkgi,ncof,vfg,kld,kh,neq)
!--------------------------------------------------------
! Generated by feelfem
!--------------------------------------------------------
! feelfem90 Program Model
! 2025/12/23 07:01
!----------------------------------------------------
use mod_ecal1_1

use mod_eset1_1_1

! general modules
use report90
use numeric
use abortmodule

implicit none

integer,dimension(:,:),pointer          :: ielem
integer,dimension(:)  ,pointer          :: matno
integer,intent(in)                      :: nelem,np
real(kind=REAL8),dimension(:)  ,pointer :: x,y,z
integer,dimension(:)  ,pointer          :: ipf,ipd
integer,intent(in)                      :: npmax
integer,intent(in)                      :: neq


real(kind=REAL8),dimension(:)  ,pointer :: vkgs,vkgd,vkgi,vfg
integer,dimension(:)  ,pointer          :: kld,kh
integer                                 :: ncof
integer                                 :: ip,jp,kp,lp

!------------------------------------------------------
! Problem dependent parameters
!------------------------------------------------------
integer,parameter                       :: NDF = 8
integer,parameter                       :: NDP = 10
integer,parameter                       :: NPG1 =  4  ! No.1 [tet2]
!------------------------------------------------------

!------------------------------------------------------
! Auto variables
!------------------------------------------------------
integer                                 :: i,j,k,l
real(kind=REAL8)                        :: ex(NDP)
real(kind=REAL8)                        :: ey(NDP)
real(kind=REAL8)                        :: ez(NDP)

integer                                 :: ienp(NDF)
integer                                 :: iedp(NDF)
integer                                 :: ikp(NDF)
real(kind=REAL8)                        :: ea,eb
!------------------------------------------------------
common /em1_1/ ea(NDF,NDF),eb(NDF)
!------------------------------------------------------
data ienp/1,2,3,4,1,2,3,4/
data iedp/0,0,0,0,1,1,1,1/
!------------------------------------------------------
call eset1_1_1
!------------------------------------------------------
do 100 i=1,nelem
! nodes should have ielem(np,nelems

!**** if(ietype .EQ. 1) then
  do j=1,np
    ex(j)=x(ielem(j,i))
    ey(j)=y(ielem(j,i))
    ez(j)=z(ielem(j,i))
  end do

  call ecal1_1(ex(1),ey(1),ez(1),ex(2),ey(2),ez(2),ex(3),ey(3) &
,ez(3),ex(4),ey(4),ez(4),ex(5),ey(5),ez(5),ex(6),ey(6),ez(6) &
,ex(7),ey(7),ez(7),ex(8),ey(8),ez(8),ex(9),ey(9),ez(9),ex(10),ey(10),ez(10))

 do j=1,NDF
   ikp(j) = ipd(ielem(ienp(j),i))+iedp(j)
 end do

   do 300 j=1,NDF
     jp = ikp(j)

     do 400 k=1,NDF
       kp= ikp(k)

       if(kp .EQ. jp) goto 405
       if(kp .GT. jp) goto 410

       lp = KLD(jp+1)-jp+kp
       VKGI(lp) = VKGI(lp) + ea(j,k)
       goto 400

 405   VKGD(jp) = VKGD(jp) + ea(j,j)
       VFG(jp)  = VFG(jp)  + eb(j)
       goto 400

 410   kp = ikp(k)
       lp = KLD(kp+1)-kp+jp
        VKGS(lp) = VKGS(lp) + ea(j,k)

 400   continue

 300  continue

 100  continue

end subroutine elem1
end module mod_elem1
