program feelfem
!--------------------------------------------------------
! Generated by feelfem
!--------------------------------------------------------
! feelfem90 Program Model
! 2025/12/23 06:08
!----------------------------------------------------
! general modules
use report90
use numeric
use abortmodule

use fileread
use femDataType
use report90

use mod_solve1

implicit none

! Output level
integer(kind=INT4 ),parameter  :: outlevel = 3          ! output level

real(kind=REAL8),dimension(:),pointer :: x,y,z          ! global coordinates
real(kind=REAL8),dimension(:),pointer :: xloc,yloc,zloc ! local coordinates
integer(kind=INT4 )            :: ierror                ! for MPI

!-----------------------------------------------------------------
! feel_dat fundamental parameters
!-----------------------------------------------------------------
integer(kind=INT4 )            :: ndim        ! space dimension
integer(kind=INT4 )            :: npmax       ! nodes(global/local)
integer(kind=INT4 )            :: nelem_g     ! number of region element
integer(kind=INT4 )            :: nedat
integer(kind=INT4 )            :: nnset
integer(kind=INT4 )            :: nnum
integer(kind=INT4 )            :: nip
!
integer(kind=INT4 )            :: mode_ex
integer(kind=INT4 )            :: mode_output
integer(kind=INT4 )            :: nvars_fem,nvars_ewise

! ------------
! Problem data
! ------------
type(meshInformation)          :: meshDat
type(solveInformation)         :: solveDat
type(solveList)                :: solveLst        
! ----
! EDAT
! ----
type(edat), pointer            :: edatData
type(edatList),pointer         :: firstEdatPtr,currentEdatPtr,edatPtr

! ----
! NSET
! ----
type(nset), pointer            :: nsetData
type(nsetList),pointer         :: firstNsetPtr,currentNsetPtr,nsetPtr

! ----
! NUM
! ----
type(numdat),pointer           :: numData

! ----
! IP    (Node number information)
! ----
type(ipdat),pointer            :: ipData

! ----
! REGN  (region matno correspondance)
! ----
type(matDat),pointer           :: matData

! ------------------------------
! FEM,EWISE variables
! ------------------------------                             
real(kind=REAL8),dimension(:)  ,pointer :: fem_u
real(kind=REAL8),dimension(:)  ,pointer :: fem_v
real(kind=REAL8),dimension(:)  ,pointer :: ew_a
real(kind=REAL8)                        :: sc_d
real(kind=REAL8)                        :: sc_s

call report90init(outlevel)
call report('Start')

!----------------
! MESH DATA READ 
!----------------

!---------
! solv_dat
!---------
call ctrlinp(meshDat,solveLst, ierror)
if(ierror .eq. Oui) then
  call abortexit('Error return from ctrlinp')
endif


!---------
! feel_dat
!---------
call datinp(ndim,npmax,nelem_g,nedat,nnset,nnum,nip, &
              mode_ex,mode_output,nvars_fem,nvars_ewise,       &
              x,y,z,                                           &
              firstEdatPtr,firstNsetPtr,numData,ipData,matData,&
              ierror   )

if(ierror .eq. Oui) then
  call abortexit('datinp error')
endif

call report('File READ')
call report90FundamentalVars(ndim,npmax,nedat,nnset,nnum,nip)


!------------------------------------------------------
! Variable allocation
!------------------------------------------------------
allocate(fem_u(npmax))
allocate(fem_v(npmax))
allocate(ew_a(nelem_g))


!------------------------------------------------------
! Initial Values
!------------------------------------------------------


!------------------------------------------------------
! Scheme start
!------------------------------------------------------
call solve1(npmax,x,y,z,firstEdatPtr,firstNsetPtr,solveLst &
           ,fem_u,fem_v,sc_d,sc_s)

!------------------------------------------------------
!call reportallmem(0)
!call reportfini

end program feelfem
