module mod_ipdinfo1_1
contains

subroutine ipdinfo1_1(npmax,ielem,nelem,np,ipd_u,ipd_v)
!--------------------------------------------------------
! Generated by feelfem
!--------------------------------------------------------
! feelfem90 Program Model
! 2025/12/23 06:08
!----------------------------------------------------
use numeric
implicit none


integer,intent(in)                      :: npmax
integer,dimension(:,:),pointer          :: ielem
integer,intent(in)                      :: nelem,np

integer,dimension(:)  ,pointer          :: ipd_u
integer,dimension(:)  ,pointer          :: ipd_v

! auto variables
integer                                 :: i,j
integer                                 :: nd
integer,dimension(4)                    :: ienp_u,iedp_u
integer,dimension(4)                    :: ienp_v,iedp_v

! data statements
data ienp_u/ 1,2,3,4/
data iedp_u/ 0,0,0,0/
data ienp_v/ 1,2,3,4/
data iedp_v/ 1,1,1,1/
!------------------------------------------------------

do i=1,npmax

  ipd_u(i) =  -1   ! -1 means no freedom here
  ipd_v(i) =  -1   ! -1 means no freedom here

end do

do i=1,nelem

 do j=1,4
  nd = ielem(ienp_u(j),i)
  ipd_u(nd)= iedp_u(j)
 end do

 do j=1,4
  nd = ielem(ienp_v(j),i)
  ipd_v(nd)= iedp_v(j)
 end do

end do

end subroutine ipdinfo1_1
end module mod_ipdinfo1_1
