module mod_ncond1_1
contains

subroutine ncond1_1(   nbedatno,firstEdatPtr, &
   npmax,x,y,z,ipf,ipd &
   ,fem_u,fem_v,sc_d,sc_s,vkgs,vkgd,vkgi,ncof,vfg,kld,kh,neq)
!--------------------------------------------------------
! Generated by feelfem
!--------------------------------------------------------
! feelfem90 Program Model
! 2025/12/23 06:08
!----------------------------------------------------
! FEM DataType
use femDataType
use feelP2data

! general modules
use report90
use numeric
use abortmodule

implicit none


integer,intent(in)                      :: nbedatno
type(edatList),pointer                  :: firstEdatPtr

integer,intent(in)                      :: neq
integer,intent(in)                      :: npmax
real(kind=REAL8),dimension(:)  ,pointer :: x,y,z
integer                                 :: ipf(npmax),ipd(npmax)

real(kind=REAL8),dimension(:)  ,pointer :: fem_u
real(kind=REAL8),dimension(:)  ,pointer :: fem_v
real(kind=REAL8)                        :: sc_d
real(kind=REAL8)                        :: sc_s

real(kind=REAL8),dimension(:)  ,pointer :: vkgs,vkgd,vkgi,vfg
integer,dimension(:)  ,pointer          :: kld,kh
integer                                 :: ncof
integer                                 :: kp,lp


!------------------------------------------------------
! Neumann parameters (NPG quadrature pts, NDF degree of freedom
!------------------------------------------------------
integer,parameter                       :: NPG = 6
integer,parameter                       :: NDF = 6


!------------------------------------------------------
! auto variables
!------------------------------------------------------
integer                                 :: i,j,k,l
integer                                 :: ip,jp
integer                                 :: itp

integer                                 :: nd
integer                                 :: nbelem,nbp
integer                                 :: netype
integer,dimension(:,:),pointer          :: bielem
integer,dimension(:)  ,pointer          :: bmatno
real(kind=REAL8)                        :: gx(NPG),gy(NPG),w(NPG)
real(kind=REAL8)                        :: dxdr,dxds
real(kind=REAL8)                        :: dydr,dyds
real(kind=REAL8)                        :: dzdr,dzds
real(kind=REAL8)                        :: ds

real(kind=REAL8)                        :: qx
real(kind=REAL8)                        :: qnx,qny,qnz
real(kind=REAL8)                        :: ns
! coordinates
real(kind=REAL8)                        :: x1,x2,x3,x4,x5,x6
real(kind=REAL8)                        :: y1,y2,y3,y4,y5,y6
real(kind=REAL8)                        :: z1,z2,z3,z4,z5,z6

! known variables
real(kind=REAL8)                        :: fem_u_1,fem_u_2,fem_u_3 &
,fem_u_4,fem_u_5,fem_u_6
real(kind=REAL8)                        :: fem_v_1,fem_v_2,fem_v_3 &
,fem_v_4,fem_v_5,fem_v_6


!------------------------------------------------------
! Quadrature terms
!------------------------------------------------------
real(kind=REAL8)                        :: rT1_1(NPG)
real(kind=REAL8)                        :: rT1_2(NPG)
real(kind=REAL8)                        :: rT1_3(NPG)
real(kind=REAL8)                        :: rT2_1(NPG)
real(kind=REAL8)                        :: rT2_1_x(NPG)
real(kind=REAL8)                        :: rT2_1_y(NPG)
real(kind=REAL8)                        :: rT2_1_z(NPG)
real(kind=REAL8)                        :: rT2_2(NPG)
real(kind=REAL8)                        :: rT2_2_x(NPG)
real(kind=REAL8)                        :: rT2_2_y(NPG)
real(kind=REAL8)                        :: rT2_2_z(NPG)
real(kind=REAL8)                        :: rT2_3(NPG)
real(kind=REAL8)                        :: rT2_3_x(NPG)
real(kind=REAL8)                        :: rT2_3_y(NPG)
real(kind=REAL8)                        :: rT2_3_z(NPG)
real(kind=REAL8)                        :: rT2_5(NPG)
real(kind=REAL8)                        :: rT2_5_x(NPG)
real(kind=REAL8)                        :: rT2_5_y(NPG)
real(kind=REAL8)                        :: rT2_5_z(NPG)
real(kind=REAL8)                        :: rT2_6(NPG)
real(kind=REAL8)                        :: rT2_6_x(NPG)
real(kind=REAL8)                        :: rT2_6_y(NPG)
real(kind=REAL8)                        :: rT2_6_z(NPG)
real(kind=REAL8)                        :: rT2_7(NPG)
real(kind=REAL8)                        :: rT2_7_x(NPG)
real(kind=REAL8)                        :: rT2_7_y(NPG)
real(kind=REAL8)                        :: rT2_7_z(NPG)
real(kind=REAL8)                        :: rTEST1_1(NPG)
real(kind=REAL8)                        :: rTEST1_2(NPG)
real(kind=REAL8)                        :: rTEST1_3(NPG)


!------------------------------------------------------
! Integrand terms
!------------------------------------------------------
real(kind=REAL8)                        :: qT1_1
real(kind=REAL8)                        :: qT1_2
real(kind=REAL8)                        :: qT1_3
real(kind=REAL8)                        :: qTEST1_1
real(kind=REAL8)                        :: qTEST1_2
real(kind=REAL8)                        :: qTEST1_3


!------------------------------------------------------
! Boundary element matrix and load vector
!------------------------------------------------------
real(kind=REAL8)                        :: ba(NDF,NDF)
real(kind=REAL8)                        :: bb(NDF)


!------------------------------------------------------
! Information arrays
!------------------------------------------------------
integer                                 :: ikp(NDF)

integer                                 :: ienp(NDF),iedp(NDF)
!------------------------------------------------------
data ienp/1,2,3,1,2,3/
data iedp/0,0,0,1,1,1/
!------------------------------------------------------

!------------------------------------------------------
! get boundary EDAT set
!------------------------------------------------------
call setP2edat(nbedatno,firstEdatPtr,nbelem,nbp,netype,&
               bielem,bmatno                            )


!------------------------------------------------------
! Boundary integration intialize
!------------------------------------------------------
! quadrature method [tri4](6)

gx(1) =4.45948490916d-01
gy(1) =4.45948490916d-01
 w(1) =1.11690794839d-01

gx(2) =1.08103018168d-01
gy(2) =4.45948490916d-01
 w(2) =1.11690794839d-01

gx(3) =4.45948490916d-01
gy(3) =1.08103018168d-01
 w(3) =1.11690794839d-01

gx(4) =9.15762135098d-02
gy(4) =9.15762135098d-02
 w(4) =5.49758718277d-02

gx(5) =8.16847572980d-01
gy(5) =9.15762135098d-02
 w(5) =5.49758718277d-02

gx(6) =9.15762135098d-02
gy(6) =8.16847572980d-01
 w(6) =5.49758718277d-02

!------------------------------------------------------
do itp=1,NPG

  rT2_1(itp)=(1.0-gx(itp)-gy(itp))*(1.0-(2.0)*gx(itp)-(2.0)*gy(itp))
  rT2_2(itp)=(-1.0+(2.0)*gx(itp))*gx(itp)
  rT2_3(itp)=(-1.0+(2.0)*gy(itp))*gy(itp)
  rT2_5(itp)=(4.0)*(1.0-gx(itp)-gy(itp))*gx(itp)
  rT2_6(itp)=(4.0)*gx(itp)*gy(itp)
  rT2_7(itp)=(4.0)*(1.0-gx(itp)-gy(itp))*gy(itp)
  rT2_1_x(itp)=-3.0+(4.0)*gy(itp)+(4.0)*gx(itp)
  rT2_2_x(itp)=-1.0+(4.0)*gx(itp)
  rT2_3_x(itp)=0
  rT2_5_x(itp)=4.0-(4.0)*gy(itp)-(8.0)*gx(itp)
  rT2_6_x(itp)=(4.0)*gy(itp)
  rT2_7_x(itp)=-(4.0)*gy(itp)
  rT2_1_y(itp)=-3.0+(4.0)*gy(itp)+(4.0)*gx(itp)
  rT2_2_y(itp)=0
  rT2_3_y(itp)=-1.0+(4.0)*gy(itp)
  rT2_5_y(itp)=-(4.0)*gx(itp)
  rT2_6_y(itp)=(4.0)*gx(itp)
  rT2_7_y(itp)=4.0-(8.0)*gy(itp)-(4.0)*gx(itp)
  rT2_1_z(itp)=0
  rT2_2_z(itp)=0
  rT2_3_z(itp)=0
  rT2_5_z(itp)=0
  rT2_6_z(itp)=0
  rT2_7_z(itp)=0
  rT1_1(itp)=1.0-gx(itp)-gy(itp)
  rT1_2(itp)=gx(itp)
  rT1_3(itp)=gy(itp)
  rTEST1_1(itp)=1.0-gx(itp)-gy(itp)
  rTEST1_2(itp)=gx(itp)
  rTEST1_3(itp)=gy(itp)

end do

do i=1,nbelem

  x1 = x(bielem(1,i))
  y1 = y(bielem(1,i))
  z1 = z(bielem(1,i))

  x2 = x(bielem(2,i))
  y2 = y(bielem(2,i))
  z2 = z(bielem(2,i))

  x3 = x(bielem(3,i))
  y3 = y(bielem(3,i))
  z3 = z(bielem(3,i))

  x4 = x(bielem(4,i))
  y4 = y(bielem(4,i))
  z4 = z(bielem(4,i))

  x5 = x(bielem(5,i))
  y5 = y(bielem(5,i))
  z5 = z(bielem(5,i))

  x6 = x(bielem(6,i))
  y6 = y(bielem(6,i))
  z6 = z(bielem(6,i))


! known variables
  fem_u_1 = fem_u(bielem(1,i))
  fem_u_2 = fem_u(bielem(2,i))
  fem_u_3 = fem_u(bielem(3,i))

  fem_v_1 = fem_v(bielem(1,i))
  fem_v_2 = fem_v(bielem(2,i))
  fem_v_3 = fem_v(bielem(3,i))


!------------------------------------------------------
  do j=1,NDF
   do k=1,NDF
     ba(j,k)=0.0d0
   end do
  end do

  do j=1,NDF
   bb(j) = 0.0d0
  end do

  do itp =1,NPG

   dxdr=x1*rT2_1_x(itp)+x2*rT2_2_x(itp)+x3*rT2_3_x(itp)+x4*rT2_5_x &
(itp)+x5*rT2_6_x(itp)+x6*rT2_7_x(itp)
   dxds=x1*rT2_1_y(itp)+x2*rT2_2_y(itp)+x3*rT2_3_y(itp)+x4*rT2_5_y &
(itp)+x5*rT2_6_y(itp)+x6*rT2_7_y(itp)

   dydr=y1*rT2_1_x(itp)+y2*rT2_2_x(itp)+y3*rT2_3_x(itp)+y4*rT2_5_x &
(itp)+y5*rT2_6_x(itp)+y6*rT2_7_x(itp)
   dyds=y1*rT2_1_y(itp)+y2*rT2_2_y(itp)+y3*rT2_3_y(itp)+y4*rT2_5_y &
(itp)+y5*rT2_6_y(itp)+y6*rT2_7_y(itp)

   dzdr=z1*rT2_1_x(itp)+z2*rT2_2_x(itp)+z3*rT2_3_x(itp)+z4*rT2_5_x &
(itp)+z5*rT2_6_x(itp)+z6*rT2_7_x(itp)
   dzds=z1*rT2_1_y(itp)+z2*rT2_2_y(itp)+z3*rT2_3_y(itp)+z4*rT2_5_y &
(itp)+z5*rT2_6_y(itp)+z6*rT2_7_y(itp)

   ds  =sqrt((dydr*dzds-dyds*dzdr)**2 +           &
             (dzdr*dxds-dzds*dxdr)**2 +           &
             (dxdr*dyds-dxds*dydr)**2   )*w(itp)

!------------------------------------------------------
   qx=x1*rT2_1(itp)+x2*rT2_2(itp)+x3*rT2_3(itp)+x4*rT2_5(itp) &
+x5*rT2_6(itp)+x6*rT2_7(itp)

   qnx = dydr*dzds-dyds*dzdr
   qny = dzdr*dxds-dzds*dxdr
   qnz = dxdr*dyds-dxds*dydr
   ns  = sqrt(qnx*qnx+qny*qny+qnz*qnz)
   qnx = -qnx/ns
   qny = -qny/ns
   qnz = -qnz/ns

!------------------------------------------------------
   qT1_1= rT1_1(itp)
   qT1_2= rT1_2(itp)
   qT1_3= rT1_3(itp)
   qTEST1_1= rTEST1_1(itp)
   qTEST1_2= rTEST1_2(itp)
   qTEST1_3= rTEST1_3(itp)

   ba(1,1)=ba(1,1)+(sc_s*qT1_1**2)*ds
   ba(1,2)=ba(1,2)+(qT1_2*sc_s*qT1_1)*ds
   ba(1,3)=ba(1,3)+(qT1_3*sc_s*qT1_1)*ds
   ba(1,4)=ba(1,4)+(-sc_s*qT1_1*qnx*sc_d*qTEST1_1*qx)*ds
   ba(1,5)=ba(1,5)+(-sc_s*qT1_1*qTEST1_2*qnx*sc_d*qx)*ds
   ba(1,6)=ba(1,6)+(-sc_s*qT1_1*qTEST1_3*qnx*sc_d*qx)*ds

   ba(2,1)=ba(2,1)+(qT1_2*sc_s*qT1_1)*ds
   ba(2,2)=ba(2,2)+(qT1_2**2*sc_s)*ds
   ba(2,3)=ba(2,3)+(qT1_2*qT1_3*sc_s)*ds
   ba(2,4)=ba(2,4)+(-qT1_2*sc_s*qnx*sc_d*qTEST1_1*qx)*ds
   ba(2,5)=ba(2,5)+(-qT1_2*sc_s*qTEST1_2*qnx*sc_d*qx)*ds
   ba(2,6)=ba(2,6)+(-qT1_2*sc_s*qTEST1_3*qnx*sc_d*qx)*ds

   ba(3,1)=ba(3,1)+(qT1_3*sc_s*qT1_1)*ds
   ba(3,2)=ba(3,2)+(qT1_2*qT1_3*sc_s)*ds
   ba(3,3)=ba(3,3)+(qT1_3**2*sc_s)*ds
   ba(3,4)=ba(3,4)+(-qT1_3*sc_s*qnx*sc_d*qTEST1_1*qx)*ds
   ba(3,5)=ba(3,5)+(-qT1_3*sc_s*qTEST1_2*qnx*sc_d*qx)*ds
   ba(3,6)=ba(3,6)+(-qT1_3*sc_s*qTEST1_3*qnx*sc_d*qx)*ds

   ba(4,1)=ba(4,1)+(qT1_3*sc_s*qT1_1)*ds
   ba(4,2)=ba(4,2)+(qT1_2*qT1_3*sc_s)*ds
   ba(4,3)=ba(4,3)+(qT1_3**2*sc_s)*ds
   ba(4,4)=ba(4,4)+(-qT1_3*sc_s*qnx*sc_d*qTEST1_1*qx)*ds
   ba(4,5)=ba(4,5)+(-qT1_3*sc_s*qTEST1_2*qnx*sc_d*qx)*ds
   ba(4,6)=ba(4,6)+(-qT1_3*sc_s*qTEST1_3*qnx*sc_d*qx)*ds

   ba(5,1)=ba(5,1)+(qT1_3*sc_s*qT1_1)*ds
   ba(5,2)=ba(5,2)+(qT1_2*qT1_3*sc_s)*ds
   ba(5,3)=ba(5,3)+(qT1_3**2*sc_s)*ds
   ba(5,4)=ba(5,4)+(-qT1_3*sc_s*qnx*sc_d*qTEST1_1*qx)*ds
   ba(5,5)=ba(5,5)+(-qT1_3*sc_s*qTEST1_2*qnx*sc_d*qx)*ds
   ba(5,6)=ba(5,6)+(-qT1_3*sc_s*qTEST1_3*qnx*sc_d*qx)*ds

   ba(6,1)=ba(6,1)+(qT1_3*sc_s*qT1_1)*ds
   ba(6,2)=ba(6,2)+(qT1_2*qT1_3*sc_s)*ds
   ba(6,3)=ba(6,3)+(qT1_3**2*sc_s)*ds
   ba(6,4)=ba(6,4)+(-qT1_3*sc_s*qnx*sc_d*qTEST1_1*qx)*ds
   ba(6,5)=ba(6,5)+(-qT1_3*sc_s*qTEST1_2*qnx*sc_d*qx)*ds
   ba(6,6)=ba(6,6)+(-qT1_3*sc_s*qTEST1_3*qnx*sc_d*qx)*ds


!  bb(1) is 0
!  bb(2) is 0
!  bb(3) is 0
!  bb(4) is 0
!  bb(5) is 0
!  bb(6) is 0

  end do    ! itp loop

  do j=1,NDF
    nd     = bielem(ienp(j),i)
    ikp(j) = ipd(nd)+iedp(j)
  end do

  do j=1,NDF
    jp = ikp(j)

    do k=1,NDF
      kp = ikp(k)

      if(kp .EQ. jp) goto 705
      if(kp .GT. jp) goto 710

      lp = KLD(jp+1)-jp+kp
      VKGI(lp) = VKGI(lp) + ba(j,k)
      goto 700

705   VKGD(jp) = VKGD(jp) + ba(j,j)
      goto 700

710   lp = KLD(kp+1)-kp+jp
      VKGS(lp) = VKGS(lp) + ba(j,k)

700 continue
    end do

  end do

  do j=1,NDF
    vfg(ikp(j))=vfg(ikp(j))+bb(j)
  end do
!------------------------------------------------------
 end do


end subroutine ncond1_1

end module mod_ncond1_1
