CFLAGS = $(ADDITIONALCFLAGS)
mesh_comp.a :mesh_comp.a(dimension.o) mesh_comp.a(domain.o) mesh_comp.a(extract_inner_edge_list.o) mesh_comp.a(get_region_area.o) mesh_comp.a(line.o) mesh_comp.a(mesh_names.o) mesh_comp.a(nodes.o) mesh_comp.a(points.o) mesh_comp.a(put_region_point.o) mesh_comp.a(refine.o) mesh_comp.a(region.o) mesh_comp.a(showmesh.o) mesh_comp.a(subdomain.o) 
