#include <stdio.h>

void basic_libraries( fp )
     FILE *fp;
{
  fprintf(fp,"/*  \n");
  fprintf(fp,"    FEEL P2 基本定義集\n");
  fprintf(fp," */\n");
  fprintf(fp,"\n");
  fprintf(fp,"/* 基底関数 */\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*-----------------------------------*/\n");
  fprintf(fp,"/* FEEL-LIB 三角形一次要素  P1[tri]  */\n");
  fprintf(fp,"/*-----------------------------------*/\n");
  fprintf(fp,"element P1[tri] {\n");
  fprintf(fp,"  (0,0): 1-r-s;\n");
  fprintf(fp,"  (1,0): r;\n");
  fprintf(fp,"  (0,1): s;\n");
  fprintf(fp,"}\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*-----------------------------------*/\n");
  fprintf(fp,"/* FEEL-LIB 三角形二次要素  P2[tri]  */\n");
  fprintf(fp,"/*-----------------------------------*/\n");
  fprintf(fp,"element P2[tri] {\n");
  fprintf(fp,"  (0  ,0  ): 1 - 3 * r + 2 * r *r - 3 * s + 4*r * s + 2 * s * s;\n");
  fprintf(fp,"  (1/2,0  ): 4*r - 4 * r * r - 4 * r * s;\n");
  fprintf(fp,"  (1  ,0  ): 2*r*r - r;\n");
  fprintf(fp,"  (1/2,1/2): 4 * r * s;\n");
  fprintf(fp,"  (0  ,1  ): 2*s * s - s;\n");
  fprintf(fp,"  (0  ,1/2): 4*s - 4*r*s - 4*s*s;\n");
  fprintf(fp,"}\n");
  fprintf(fp,"\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*-------------------------------------*/\n");
  fprintf(fp,"/* FEEL-LIB 四辺形双一次要素  Q1[rect] */\n");
  fprintf(fp,"/*-------------------------------------*/\n");
  fprintf(fp,"element Q1[rect] {\n");
  fprintf(fp,"   (-1,-1): (1-r)*(1-s) * 0.25 ;\n");
  fprintf(fp,"   ( 1,-1): (1+r)*(1-s) * 0.25 ;\n");
  fprintf(fp,"   ( 1, 1): (1+r)*(1+s) * 0.25 ;\n");
  fprintf(fp,"   (-1, 1): (1-r)*(1+s) * 0.25 ;\n");
  fprintf(fp,"}\n");
  fprintf(fp,"\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*-----------------------------------------*/\n");
  fprintf(fp,"/* FEEL-LIB Serenpidity ２次要素  Q2[rect] */\n");
  fprintf(fp,"/*-----------------------------------------*/\n");
  fprintf(fp,"element Q2[rect] {\n");
  fprintf(fp,"   (-1,-1):  (r- 1)*(1-s)*(1+s+r)*0.25;\n");
  fprintf(fp,"   ( 0,-1):  (1-r*r)*(1-s)*0.5;\n");
  fprintf(fp,"   ( 1,-1):  (-1-r)*(1-s)*(1-r+s)*0.25;\n");
  fprintf(fp,"   ( 1, 0):  (1+r)*(1-s * s)*0.5;\n");
  fprintf(fp,"   ( 1, 1): -(1+r)*(1+s)*(1-s-r)*0.25;\n");
  fprintf(fp,"   ( 0, 1):  (1- r*r)*(1+s)*0.5;\n");
  fprintf(fp,"   (-1, 1):  (r- 1)*(1+s)*(1+r-s)*0.25;\n");
  fprintf(fp,"   (-1, 0):  (1-r)*(1- s*s)*0.5;\n");
  fprintf(fp,"}\n");
  fprintf(fp,"\n");
  fprintf(fp,"\n");
  fprintf(fp,"/* Serenpidity ３次要素 */\n");
  fprintf(fp," /* 疲れたからやんぴ */\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*---------------------------------------*/\n");
  fprintf(fp,"/* FEEL-LIB 完全四辺形２次要素 Q2A[rect] */\n");
  fprintf(fp,"/*---------------------------------------*/\n");
  fprintf(fp,"element Q2A[rect] {\n");
  fprintf(fp,"   (-1,-1):  (1-r)*(1-s)*r*s*0.25;\n");
  fprintf(fp,"   ( 0,-1): -(1-r*r)*(1-s)*s*0.5;\n");
  fprintf(fp,"   ( 1,-1): -(1+r)*(1-s)*r*s*0.25;\n");
  fprintf(fp,"   ( 1, 0):  (1+r)*(1-s*s)*r *0.5 ;\n");
  fprintf(fp,"   ( 1, 1):  (1+r)*(1+s)*r*s*0.25;\n");
  fprintf(fp,"   ( 0, 1):  (1-r*r)*(1+s)*s*0.5;\n");
  fprintf(fp,"   (-1, 1):  -(1-r)*(1+s)*r*s*0.25;\n");
  fprintf(fp,"   (-1, 0): -(1-r)*(1-s*s)*r*0.5;\n");
  fprintf(fp,"   ( 0, 0):  (1-r*r)*(1-s*s);\n");
  fprintf(fp,"}\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"/* FEEL-LIB ガウス数値積分法 gauss2x2[rect] */\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"quadrature gauss2x2[rect] {\n");
  fprintf(fp,"    const p =  0.577350269189626;\n");
  fprintf(fp,"    const pm= -0.577350269189626;\n");
  fprintf(fp,"   ( p, p): 1;\n");
  fprintf(fp,"   ( p,pm): 1;\n");
  fprintf(fp,"   (pm, p): 1;\n");
  fprintf(fp,"   (pm,pm): 1;\n");
  fprintf(fp,"}\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"/* FEEL-LIB ガウス数値積分法 gauss3x3[rect] */\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"quadrature gauss3x3[rect] {\n");
  fprintf(fp,"    const p =  sqrt(3.0d0/5.0d0);\n");
  fprintf(fp,"    const w1 = 8.0d0/9.0d0;\n");
  fprintf(fp,"    const w2 = 5.0d0/9.0d0;\n");
  fprintf(fp,"\n");
  fprintf(fp,"    (0,p) : w1 * w2;\n");
  fprintf(fp,"    (0,-p): w1 * w2;\n");
  fprintf(fp,"    (0,0) : w1 * w1;\n");
  fprintf(fp,"    (p,p) : w2 * w2;\n");
  fprintf(fp,"    (p,0) : w2 * w1;\n");
  fprintf(fp,"    (p,-p): w2 * w2;\n");
  fprintf(fp,"    (-p,-p): w2 * w2;\n");
  fprintf(fp,"    (-p,0) : w2 * w1;\n");
  fprintf(fp,"    (-p,p) : w2 * w2;\n");
  fprintf(fp,"}\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*------------------------------------------*/\n");
  fprintf(fp,"/* FEEL-LIB  ガウス数値積分法gauss4x4[rect] */\n");
  fprintf(fp,"/*------------------------------------------*/\n");
  fprintf(fp,"quadrature gauss4x4[rect] {\n");
  fprintf(fp,"const p1 =  0.339981043584856;\n");
  fprintf(fp,"const p2 =  0.861136311594053;\n");
  fprintf(fp,"const w1 =  0.652145154862546;\n");
  fprintf(fp,"const w2 =  0.347854845137454;\n");
  fprintf(fp,"\n");
  fprintf(fp,"(p1,p1)  : w1*w1;\n");
  fprintf(fp,"(p1,-p1) : w1*w1;\n");
  fprintf(fp,"(p1,p2)  : w1*w2;\n");
  fprintf(fp,"(p1,-p2) : w1*w2;\n");
  fprintf(fp,"\n");
  fprintf(fp,"(-p1,p1) : w1*w1;\n");
  fprintf(fp,"(-p1,-p1): w1*w1;\n");
  fprintf(fp,"(-p1,p2) : w1*w2;\n");
  fprintf(fp,"(-p1,-p2): w1*w2;\n");
  fprintf(fp,"\n");
  fprintf(fp,"(p2,p1)  : w1*w1;\n");
  fprintf(fp,"(p2,-p1) : w1*w1;\n");
  fprintf(fp,"(p2,p2)  : w1*w2;\n");
  fprintf(fp,"(p2,-p2) : w1*w2;\n");
  fprintf(fp,"\n");
  fprintf(fp,"(-p2,p1) : w1*w1;\n");
  fprintf(fp,"(-p2,-p1): w1*w1;\n");
  fprintf(fp,"(-p2,p2) : w1*w2;\n");
  fprintf(fp,"(-p2,-p2): w1*w2;\n");
  fprintf(fp,"}\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"/* FEEL-LIB 直接数値積分法 rec2a[rect]      */\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"quadrature rec2a[rect] {\n");
  fprintf(fp,"    const px0 = sqrt(2.0d0/3.0d0);\n");
  fprintf(fp,"    const py0 = 0;\n");
  fprintf(fp,"    const px1 = -1.0d0/sqrt(6.0d0);\n");
  fprintf(fp,"    const py1 =  1.0d0/sqrt(2.0d0);\n");
  fprintf(fp,"\n");
  fprintf(fp,"    (px0,py0): 4.0d0/3.0d0;\n");
  fprintf(fp,"    (px1,py1): 4.0d0/3.0d0;\n");
  fprintf(fp,"    (px1,-py1): 4.0d0/3.0d0;\n");
  fprintf(fp,"}\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"/* FEEL-LIB 直接数値積分法 rec2b[rect]      */\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"quadrature rec2b[rect] {\n");
  fprintf(fp,"    (1   ,1)   :   4.0d0/7.0d0;\n");
  fprintf(fp,"    (-5/9,2/9) : 27.0d0/14.0d0;\n");
  fprintf(fp,"    (1/3,-2/3) :   3.0d0*0.5;\n");
  fprintf(fp,"}\n");
  fprintf(fp,"\n");
  fprintf(fp,"\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"/* FEEL-LIB 直接数値積分法 tri2[tri]      */\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"quadrature tri2[tri] {\n");
  fprintf(fp," (1/2,1/2) : 1.0d0/6.0d0;\n");
  fprintf(fp," ( 0, 1/2) : 1.0d0/6.0d0;\n");
  fprintf(fp," (1/2, 0 ) : 1.0d0/6.0d0;\n");
  fprintf(fp,"}\n");
  fprintf(fp,"\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"/* FEEL-LIB 直接数値積分法 tri2a[tri]      */\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"quadrature tri2a[tri] {\n");
  fprintf(fp," (1/6,1/6) : 1.0d0/6.0d0;\n");
  fprintf(fp," (2/3,1/6) : 1.0d0/6.0d0;\n");
  fprintf(fp," (1/6,2/3) : 1.0d0/6.0d0;\n");
  fprintf(fp,"\n");
  fprintf(fp,"}\n");
  fprintf(fp,"\n");
  fprintf(fp,"\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"/* FEEL-LIB 直接数値積分法 tri4[tri]      */\n");
  fprintf(fp,"/*------------------------------------------*/  \n");
  fprintf(fp,"quadrature tri4[tri] {\n");
  fprintf(fp," const a = 0.445948490915965;\n");
  fprintf(fp," const b = 0.091576213509771;\n");
  fprintf(fp,"\n");
  fprintf(fp,"  (a    ,a) : 0.111690794839005;\n");
  fprintf(fp,"  (1- 2*a,a) : 0.111690794839005;\n");
  fprintf(fp,"  (a,1- 2*a) : 0.111690794839005;\n");
  fprintf(fp,"\n");
  fprintf(fp,"  (b    ,b) : 0.054975871827661;\n");
  fprintf(fp,"  (1- 2*b,b) : 0.054975871827661;\n");
  fprintf(fp,"  (b,1- 2*b) : 0.054975871827661;\n");
  fprintf(fp,"\n");
  fprintf(fp,"}\n");
}
