CFLAGS =  $(ADDITIONALCFLAGS)
solve_comp.a :solve_comp.a(dbg_show_elem_dat.o) solve_comp.a(edat_make.o) solve_comp.a(elem_dat_make.o) solve_comp.a(element_node.o) solve_comp.a(get_femvarinfo.o) solve_comp.a(make_fem_varinfo.o) solve_comp.a(make_mesh_ctrl_data.o) solve_comp.a(make_subdomain_info.o) solve_comp.a(set_boundary_no.o) solve_comp.a(solve.o) solve_comp.a(solve_dat_make.o) 
