      SUBROUTINE HAJIME (MANOD,NMAX,NNODE,NSKAI,NSUU,NWORK,
     $     NSETU,NTRIA,NGL,IL,NRIL,NRGL,NBB,NZOKU,NGRU,LG,JA)
*
      IMPLICIT REAL*8 (A-H,O-Z)
*
      DIMENSION NWORK(0:NMAX,20)
      DIMENSION JA(0:MANOD*NSUU) 
*
      DIMENSION IL(0:MANOD),NGL(NMAX),NRIL(0:MANOD),NRGL(NMAX)
      DIMENSION NBB(0:2**NSKAI,0:NSKAI)
      DIMENSION NZOKU(MANOD),LG(MANOD,2**(NSKAI-3))
      DIMENSION NGRU(MANOD)
*
*   --- Let's make the Data "NGL(I)" and "IL(I)" ----
*
      CALL RENKE (MANOD,NMAX,NSUU,NWORK(1,1),NSETU,NNODE,
     $     NWORK(1,2),NTRIA,NGL,IL,JA)
      PAI=DATAN(1.D0)*4.D0
*
*
*     
      CALL SYOKI (MANOD,NNODE,NMAX,NSKAI,IL,NGL,NRIL,NRGL,NBB,
     $     NZOKU,NGRU,LG)
*
      RETURN
      END




