      SUBROUTINE SYOKI (MANOD,NNODE,NMAX,NSKAI,IL,NGL,NRIL,NRGL,NBB,
     $     NZOKU,NGRU,LG)
*
      IMPLICIT REAL*8 (A-H,O-Z)
*
      DIMENSION IL(0:MANOD),NGL(NMAX),NRIL(0:MANOD),NRGL(NMAX)
      DIMENSION NBB(0:2**NSKAI,0:NSKAI)
      DIMENSION NZOKU(MANOD),LG(MANOD,2**(NSKAI-3))
      DIMENSION NGRU(MANOD)
*     
      DO 190 I=0,NNODE
         NRIL(I)=IL(I)
 190  CONTINUE
      DO 193 I=1,NNODE
         DO 194 L=IL(I-1),IL(I)-1
            NRGL(L)=NGL(L)
 194     CONTINUE
 193  CONTINUE
      NBB(0,0)=0
      NBB(1,0)=NNODE
      DO 812 I=1,NNODE
         NZOKU(I)=1
         NGRU(I)=I
         LG(I,1)=I
 812  CONTINUE
*
      RETURN 
      END
