/*
 *  feelfem version 1.0  Copyright(c)  NEC Corporation 1999
 *                       Programmed by Hidehiro  FUJIO
 *
 *  Filename : Name.hpp
 *  Date     : 1999/07/22
 *  Modified : 1999/07/22
 *  
 *  Purpose  : Name class.  Generally it is a string class but
 *             it has some output operation definitions.
 */

#ifndef Name_h
#define Name_h  1

#include <assert.h>
#include <stream.h>
#include <string.h>

