nkf -s <..\check\avs_check.c >ooo.tmp
copy ooo.tmp ..\check\avs_check.c
nkf -s <..\check\check.c >ooo.tmp
copy ooo.tmp ..\check\check.c
nkf -s <..\check\duplicate_check.c >ooo.tmp
copy ooo.tmp ..\check\duplicate_check.c
nkf -s <..\check\element_check.c >ooo.tmp
copy ooo.tmp ..\check\element_check.c
nkf -s <..\check\element_chk_pretoinf.c >ooo.tmp
copy ooo.tmp ..\check\element_chk_pretoinf.c
nkf -s <..\check\etype_dimension.c >ooo.tmp
copy ooo.tmp ..\check\etype_dimension.c
nkf -s <..\check\ewise_var_check.c >ooo.tmp
copy ooo.tmp ..\check\ewise_var_check.c
nkf -s <..\check\fem_var_element_check.c >ooo.tmp
copy ooo.tmp ..\check\fem_var_element_check.c
nkf -s <..\check\is_expr_eq.c >ooo.tmp
copy ooo.tmp ..\check\is_expr_eq.c
nkf -s <..\check\point_check.c >ooo.tmp
copy ooo.tmp ..\check\point_check.c
nkf -s <..\check\quad_check.c >ooo.tmp
copy ooo.tmp ..\check\quad_check.c
nkf -s <..\check\refine_check.c >ooo.tmp
copy ooo.tmp ..\check\refine_check.c
nkf -s <..\check\region_domain_check.c >ooo.tmp
copy ooo.tmp ..\check\region_domain_check.c
nkf -s <..\check\region_subdomain_check.c >ooo.tmp
copy ooo.tmp ..\check\region_subdomain_check.c
nkf -s <..\check\scheme_adaptmesh_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_adaptmesh_check.c
nkf -s <..\check\scheme_contour_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_contour_check.c
nkf -s <..\check\scheme_displacement_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_displacement_check.c
nkf -s <..\check\scheme_gotolabel_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_gotolabel_check.c
nkf -s <..\check\scheme_if_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_if_check.c
nkf -s <..\check\scheme_let_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_let_check.c
nkf -s <..\check\scheme_norm_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_norm_check.c
nkf -s <..\check\scheme_perspect_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_perspect_check.c
nkf -s <..\check\scheme_plot_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_plot_check.c
nkf -s <..\check\scheme_rw_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_rw_check.c
nkf -s <..\check\scheme_showvec_check.c >ooo.tmp
copy ooo.tmp ..\check\scheme_showvec_check.c
nkf -s <..\check\solve_check_main.c >ooo.tmp
copy ooo.tmp ..\check\solve_check_main.c
nkf -s <..\check\solve_chk_DirichletData.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_DirichletData.c
nkf -s <..\check\solve_chk_EigenProblem.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_EigenProblem.c
nkf -s <..\check\solve_chk_NeumannData.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_NeumannData.c
nkf -s <..\check\solve_chk_bd_var.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_bd_var.c
nkf -s <..\check\solve_chk_boundary.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_boundary.c
nkf -s <..\check\solve_chk_initial.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_initial.c
nkf -s <..\check\solve_chk_only_neumann.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_only_neumann.c
nkf -s <..\check\solve_chk_quad_method.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_quad_method.c
nkf -s <..\check\solve_chk_shape_function.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_shape_function.c
nkf -s <..\check\solve_chk_test_function.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_test_function.c
nkf -s <..\check\solve_chk_var.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_var.c
nkf -s <..\check\solve_chk_var_vs_domain.c >ooo.tmp
copy ooo.tmp ..\check\solve_chk_var_vs_domain.c
nkf -s <..\check\var_check.c >ooo.tmp
copy ooo.tmp ..\check\var_check.c
nkf -s <..\check\var_const_pretoinf.c >ooo.tmp
copy ooo.tmp ..\check\var_const_pretoinf.c
nkf -s <..\check\var_fem_ewise_datmake.c >ooo.tmp
copy ooo.tmp ..\check\var_fem_ewise_datmake.c
nkf -s <..\eigen_fort77\elem77_main_sk.c >ooo.tmp
copy ooo.tmp ..\eigen_fort77\elem77_main_sk.c
nkf -s <..\eigen_fort77\make_ctrl77_sk.c >ooo.tmp
copy ooo.tmp ..\eigen_fort77\make_ctrl77_sk.c
nkf -s <..\eigen_fort77\make_dcond_sk.c >ooo.tmp
copy ooo.tmp ..\eigen_fort77\make_dcond_sk.c
nkf -s <..\eigen_fort77\make_ncond_skyline.c >ooo.tmp
copy ooo.tmp ..\eigen_fort77\make_ncond_skyline.c
nkf -s <..\element\cordinate_check.c >ooo.tmp
copy ooo.tmp ..\element\cordinate_check.c
nkf -s <..\element\element_order.c >ooo.tmp
copy ooo.tmp ..\element\element_order.c
nkf -s <..\element\element_parse.c >ooo.tmp
copy ooo.tmp ..\element\element_parse.c
nkf -s <..\element\get_etype_no.c >ooo.tmp
copy ooo.tmp ..\element\get_etype_no.c
nkf -s <..\element\get_freedom_by_element_name.c >ooo.tmp
copy ooo.tmp ..\element\get_freedom_by_element_name.c
nkf -s <..\exec\StrEq.c >ooo.tmp
copy ooo.tmp ..\exec\StrEq.c
nkf -s <..\exec\basic_libraries.c >ooo.tmp
copy ooo.tmp ..\exec\basic_libraries.c
nkf -s <..\exec\feel.c >ooo.tmp
copy ooo.tmp ..\exec\feel.c
nkf -s <..\exec\strindex.c >ooo.tmp
copy ooo.tmp ..\exec\strindex.c
nkf -s <..\f77_lib\MSFortran_erapse_time.c >ooo.tmp
copy ooo.tmp ..\f77_lib\MSFortran_erapse_time.c
nkf -s <..\f77_lib\alpha_erapse_time.c >ooo.tmp
copy ooo.tmp ..\f77_lib\alpha_erapse_time.c
nkf -s <..\f77_lib\diskio.c >ooo.tmp
copy ooo.tmp ..\f77_lib\diskio.c
nkf -s <..\f77_lib\make_cfile.c >ooo.tmp
copy ooo.tmp ..\f77_lib\make_cfile.c
nkf -s <..\f77_lib\mpi_util.c >ooo.tmp
copy ooo.tmp ..\f77_lib\mpi_util.c
nkf -s <..\feel_lib\basic_libraries.c >ooo.tmp
copy ooo.tmp ..\feel_lib\basic_libraries.c
nkf -s <..\feel_lib\make_c.c >ooo.tmp
copy ooo.tmp ..\feel_lib\make_c.c
nkf -s <..\feel_util\maxfeel.c >ooo.tmp
copy ooo.tmp ..\feel_util\maxfeel.c
nkf -s <..\fort77lib\MSFortran_erapse_time.c >ooo.tmp
copy ooo.tmp ..\fort77lib\MSFortran_erapse_time.c
nkf -s <..\fort77lib\alpha_erapse_time.c >ooo.tmp
copy ooo.tmp ..\fort77lib\alpha_erapse_time.c
nkf -s <..\fort77lib\cal_ht.c >ooo.tmp
copy ooo.tmp ..\fort77lib\cal_ht.c
nkf -s <..\fort77lib\closefil.c >ooo.tmp
copy ooo.tmp ..\fort77lib\closefil.c
nkf -s <..\fort77lib\convex_erapse_time.c >ooo.tmp
copy ooo.tmp ..\fort77lib\convex_erapse_time.c
nkf -s <..\fort77lib\diskio.c >ooo.tmp
copy ooo.tmp ..\fort77lib\diskio.c
nkf -s <..\fort77lib\edatrange.c >ooo.tmp
copy ooo.tmp ..\fort77lib\edatrange.c
nkf -s <..\fort77lib\ews4800_erapse_time.c >ooo.tmp
copy ooo.tmp ..\fort77lib\ews4800_erapse_time.c
nkf -s <..\fort77lib\f_alloc.c >ooo.tmp
copy ooo.tmp ..\fort77lib\f_alloc.c
nkf -s <..\fort77lib\f_free.c >ooo.tmp
copy ooo.tmp ..\fort77lib\f_free.c
nkf -s <..\fort77lib\fort77lib_make.c >ooo.tmp
copy ooo.tmp ..\fort77lib\fort77lib_make.c
nkf -s <..\fort77lib\get_ielem.c >ooo.tmp
copy ooo.tmp ..\fort77lib\get_ielem.c
nkf -s <..\fort77lib\get_inset.c >ooo.tmp
copy ooo.tmp ..\fort77lib\get_inset.c
nkf -s <..\fort77lib\inpdat_wrt.c >ooo.tmp
copy ooo.tmp ..\fort77lib\inpdat_wrt.c
nkf -s <..\fort77lib\ipd_make.c >ooo.tmp
copy ooo.tmp ..\fort77lib\ipd_make.c
nkf -s <..\fort77lib\ipd_nonode.c >ooo.tmp
copy ooo.tmp ..\fort77lib\ipd_nonode.c
nkf -s <..\fort77lib\ipf_nfree.c >ooo.tmp
copy ooo.tmp ..\fort77lib\ipf_nfree.c
nkf -s <..\fort77lib\lib_iris_cptime.c >ooo.tmp
copy ooo.tmp ..\fort77lib\lib_iris_cptime.c
nkf -s <..\fort77lib\make_KLD.c >ooo.tmp
copy ooo.tmp ..\fort77lib\make_KLD.c
nkf -s <..\fort77lib\mk_subdomain_edat.c >ooo.tmp
copy ooo.tmp ..\fort77lib\mk_subdomain_edat.c
nkf -s <..\fort77lib\mk_subdomain_nset.c >ooo.tmp
copy ooo.tmp ..\fort77lib\mk_subdomain_nset.c
nkf -s <..\fort77lib\mpi_util.c >ooo.tmp
copy ooo.tmp ..\fort77lib\mpi_util.c
nkf -s <..\fort77lib\report.c >ooo.tmp
copy ooo.tmp ..\fort77lib\report.c
nkf -s <..\fort77lib\scal.c >ooo.tmp
copy ooo.tmp ..\fort77lib\scal.c
nkf -s <..\fort77lib\set.c >ooo.tmp
copy ooo.tmp ..\fort77lib\set.c
nkf -s <..\fort77lib\sol.c >ooo.tmp
copy ooo.tmp ..\fort77lib\sol.c
nkf -s <..\fort77lib\sparc_erapse_time.c >ooo.tmp
copy ooo.tmp ..\fort77lib\sparc_erapse_time.c
nkf -s <..\fort77lib\zero.c >ooo.tmp
copy ooo.tmp ..\fort77lib\zero.c
nkf -s <..\geom2d\get_polygon_area.c >ooo.tmp
copy ooo.tmp ..\geom2d\get_polygon_area.c
nkf -s <..\let\adaptmesh_fort77.c >ooo.tmp
copy ooo.tmp ..\let\adaptmesh_fort77.c
nkf -s <..\let\get_let_fp.c >ooo.tmp
copy ooo.tmp ..\let\get_let_fp.c
nkf -s <..\let\let_ewise_ewise.c >ooo.tmp
copy ooo.tmp ..\let\let_ewise_ewise.c
nkf -s <..\let\let_ewise_sc.c >ooo.tmp
copy ooo.tmp ..\let\let_ewise_sc.c
nkf -s <..\let\let_fem_fem.c >ooo.tmp
copy ooo.tmp ..\let\let_fem_fem.c
nkf -s <..\let\let_fort77.c >ooo.tmp
copy ooo.tmp ..\let\let_fort77.c
nkf -s <..\let\let_sc_sc.c >ooo.tmp
copy ooo.tmp ..\let\let_sc_sc.c
nkf -s <..\let\make_adapt_called.c >ooo.tmp
copy ooo.tmp ..\let\make_adapt_called.c
nkf -s <..\let\make_adapt_called_dim.c >ooo.tmp
copy ooo.tmp ..\let\make_adapt_called_dim.c
nkf -s <..\let\make_called.c >ooo.tmp
copy ooo.tmp ..\let\make_called.c
nkf -s <..\let\make_called_dim.c >ooo.tmp
copy ooo.tmp ..\let\make_called_dim.c
nkf -s <..\let\make_main_adapt_call.c >ooo.tmp
copy ooo.tmp ..\let\make_main_adapt_call.c
nkf -s <..\let\make_main_let_call.c >ooo.tmp
copy ooo.tmp ..\let\make_main_let_call.c
nkf -s <..\let\make_main_norm_call.c >ooo.tmp
copy ooo.tmp ..\let\make_main_norm_call.c
nkf -s <..\let\make_norm_called.c >ooo.tmp
copy ooo.tmp ..\let\make_norm_called.c
nkf -s <..\let\make_norm_called_dim.c >ooo.tmp
copy ooo.tmp ..\let\make_norm_called_dim.c
nkf -s <..\let\norm_fort77.c >ooo.tmp
copy ooo.tmp ..\let\norm_fort77.c
nkf -s <..\lisp_c\lisp_exp_print.c >ooo.tmp
copy ooo.tmp ..\lisp_c\lisp_exp_print.c
nkf -s <..\lisp_lib\diff.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\diff.c
nkf -s <..\lisp_lib\diff_fmla_m.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\diff_fmla_m.c
nkf -s <..\lisp_lib\do_d_formula.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\do_d_formula.c
nkf -s <..\lisp_lib\exp_print.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\exp_print.c
nkf -s <..\lisp_lib\expand.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\expand.c
nkf -s <..\lisp_lib\fs.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\fs.c
nkf -s <..\lisp_lib\fs_dep.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\fs_dep.c
nkf -s <..\lisp_lib\fs_sort.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\fs_sort.c
nkf -s <..\lisp_lib\fs_term_bind.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\fs_term_bind.c
nkf -s <..\lisp_lib\lisp_package.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\lisp_package.c
nkf -s <..\lisp_lib\make_fem_term_list.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\make_fem_term_list.c
nkf -s <..\lisp_lib\make_linear_integrand.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\make_linear_integrand.c
nkf -s <..\lisp_lib\make_linear_weak.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\make_linear_weak.c
nkf -s <..\lisp_lib\make_load_integrand.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\make_load_integrand.c
nkf -s <..\lisp_lib\make_num_int.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\make_num_int.c
nkf -s <..\lisp_lib\make_num_int_matrix_dat.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\make_num_int_matrix_dat.c
nkf -s <..\lisp_lib\make_num_int_term.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\make_num_int_term.c
nkf -s <..\lisp_lib\minus_convert.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\minus_convert.c
nkf -s <..\lisp_lib\replace_string.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\replace_string.c
nkf -s <..\lisp_lib\replace_test_func.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\replace_test_func.c
nkf -s <..\lisp_lib\symbol_eval_replace.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\symbol_eval_replace.c
nkf -s <..\lisp_lib\trans_num_int_integrand.c >ooo.tmp
copy ooo.tmp ..\lisp_lib\trans_num_int_integrand.c
nkf -s <..\lisp_util\pre_to_inf.c >ooo.tmp
copy ooo.tmp ..\lisp_util\pre_to_inf.c
nkf -s <..\main\data_number.c >ooo.tmp
copy ooo.tmp ..\main\data_number.c
nkf -s <..\main\debug.c >ooo.tmp
copy ooo.tmp ..\main\debug.c
nkf -s <..\main\feel_exec_main.c >ooo.tmp
copy ooo.tmp ..\main\feel_exec_main.c
nkf -s <..\main\feel_terminate.c >ooo.tmp
copy ooo.tmp ..\main\feel_terminate.c
nkf -s <..\main\make_parallel_data.c >ooo.tmp
copy ooo.tmp ..\main\make_parallel_data.c
nkf -s <..\makefort77\CommonBlock.c >ooo.tmp
copy ooo.tmp ..\makefort77\CommonBlock.c
nkf -s <..\makefort77\CopyRight.c >ooo.tmp
copy ooo.tmp ..\makefort77\CopyRight.c
nkf -s <..\makefort77\TimeStamp.c >ooo.tmp
copy ooo.tmp ..\makefort77\TimeStamp.c
nkf -s <..\makefort77\WriteWinsiz.c >ooo.tmp
copy ooo.tmp ..\makefort77\WriteWinsiz.c
nkf -s <..\makefort77\close_file.c >ooo.tmp
copy ooo.tmp ..\makefort77\close_file.c
nkf -s <..\makefort77\comments.c >ooo.tmp
copy ooo.tmp ..\makefort77\comments.c
nkf -s <..\makefort77\contour_file_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\contour_file_fort77.c
nkf -s <..\makefort77\contour_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\contour_fort77.c
nkf -s <..\makefort77\data_init.c >ooo.tmp
copy ooo.tmp ..\makefort77\data_init.c
nkf -s <..\makefort77\datinp.c >ooo.tmp
copy ooo.tmp ..\makefort77\datinp.c
nkf -s <..\makefort77\displacement_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\displacement_fort77.c
nkf -s <..\makefort77\filset.c >ooo.tmp
copy ooo.tmp ..\makefort77\filset.c
nkf -s <..\makefort77\get_feel_array_size.c >ooo.tmp
copy ooo.tmp ..\makefort77\get_feel_array_size.c
nkf -s <..\makefort77\goto_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\goto_fort77.c
nkf -s <..\makefort77\if_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\if_fort77.c
nkf -s <..\makefort77\label_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\label_fort77.c
nkf -s <..\makefort77\main_const_let.c >ooo.tmp
copy ooo.tmp ..\makefort77\main_const_let.c
nkf -s <..\makefort77\main_declare.c >ooo.tmp
copy ooo.tmp ..\makefort77\main_declare.c
nkf -s <..\makefort77\main_declare_scalar.c >ooo.tmp
copy ooo.tmp ..\makefort77\main_declare_scalar.c
nkf -s <..\makefort77\main_prepare.c >ooo.tmp
copy ooo.tmp ..\makefort77\main_prepare.c
nkf -s <..\makefort77\main_scheme.c >ooo.tmp
copy ooo.tmp ..\makefort77\main_scheme.c
nkf -s <..\makefort77\main_subdomain.c >ooo.tmp
copy ooo.tmp ..\makefort77\main_subdomain.c
nkf -s <..\makefort77\main_variable.c >ooo.tmp
copy ooo.tmp ..\makefort77\main_variable.c
nkf -s <..\makefort77\make_avs_coroutine.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_avs_coroutine.c
nkf -s <..\makefort77\make_avs_def_file.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_avs_def_file.c
nkf -s <..\makefort77\make_avs_interface_routine.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_avs_interface_routine.c
nkf -s <..\makefort77\make_avs_output_routine.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_avs_output_routine.c
nkf -s <..\makefort77\make_feel_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_feel_fort77.c
nkf -s <..\makefort77\make_inp_edat.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_inp_edat.c
nkf -s <..\makefort77\make_inp_ip.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_inp_ip.c
nkf -s <..\makefort77\make_inp_node.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_inp_node.c
nkf -s <..\makefort77\make_inp_nodeset.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_inp_nodeset.c
nkf -s <..\makefort77\make_inp_num.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_inp_num.c
nkf -s <..\makefort77\make_main.c >ooo.tmp
copy ooo.tmp ..\makefort77\make_main.c
nkf -s <..\makefort77\para_make_main.c >ooo.tmp
copy ooo.tmp ..\makefort77\para_make_main.c
nkf -s <..\makefort77\perspect_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\perspect_fort77.c
nkf -s <..\makefort77\plot_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\plot_fort77.c
nkf -s <..\makefort77\read_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\read_fort77.c
nkf -s <..\makefort77\real8.c >ooo.tmp
copy ooo.tmp ..\makefort77\real8.c
nkf -s <..\makefort77\report.c >ooo.tmp
copy ooo.tmp ..\makefort77\report.c
nkf -s <..\makefort77\showvec_file_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\showvec_file_fort77.c
nkf -s <..\makefort77\showvec_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\showvec_fort77.c
nkf -s <..\makefort77\solve_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\solve_fort77.c
nkf -s <..\makefort77\time_plot_file_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\time_plot_file_fort77.c
nkf -s <..\makefort77\write_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\write_fort77.c
nkf -s <..\makefort77\xplot_fort77.c >ooo.tmp
copy ooo.tmp ..\makefort77\xplot_fort77.c
nkf -s <..\mesh_bamg_exec\make_MESH_REF_bamg.c >ooo.tmp
copy ooo.tmp ..\mesh_bamg_exec\make_MESH_REF_bamg.c
nkf -s <..\mesh_bamg_exec\make_bamg_info.c >ooo.tmp
copy ooo.tmp ..\mesh_bamg_exec\make_bamg_info.c
nkf -s <..\mesh_bamg_exec\make_boundary_data_bamg.c >ooo.tmp
copy ooo.tmp ..\mesh_bamg_exec\make_boundary_data_bamg.c
nkf -s <..\mesh_bamg_exec\make_feel_data_file_bamg.c >ooo.tmp
copy ooo.tmp ..\mesh_bamg_exec\make_feel_data_file_bamg.c
nkf -s <..\mesh_bamg_exec\mesh_bamg_exec.c >ooo.tmp
copy ooo.tmp ..\mesh_bamg_exec\mesh_bamg_exec.c
nkf -s <..\mesh_bamg_exec\push_boundary_edat_bamg.c >ooo.tmp
copy ooo.tmp ..\mesh_bamg_exec\push_boundary_edat_bamg.c
nkf -s <..\mesh_bamg_exec\push_boundary_nset_bamg.c >ooo.tmp
copy ooo.tmp ..\mesh_bamg_exec\push_boundary_nset_bamg.c
nkf -s <..\mesh_bamg_exec\push_boundary_plot_data_bamg.c >ooo.tmp
copy ooo.tmp ..\mesh_bamg_exec\push_boundary_plot_data_bamg.c
nkf -s <..\mesh_bamg_util\read_bamg_mesh.c >ooo.tmp
copy ooo.tmp ..\mesh_bamg_util\read_bamg_mesh.c
nkf -s <..\mesh_comp\dimension.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\dimension.c
nkf -s <..\mesh_comp\domain.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\domain.c
nkf -s <..\mesh_comp\extract_inner_edge_list.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\extract_inner_edge_list.c
nkf -s <..\mesh_comp\get_region_area.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\get_region_area.c
nkf -s <..\mesh_comp\line.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\line.c
nkf -s <..\mesh_comp\mesh_names.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\mesh_names.c
nkf -s <..\mesh_comp\nodes.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\nodes.c
nkf -s <..\mesh_comp\points.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\points.c
nkf -s <..\mesh_comp\put_region_point.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\put_region_point.c
nkf -s <..\mesh_comp\refine.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\refine.c
nkf -s <..\mesh_comp\region.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\region.c
nkf -s <..\mesh_comp\showmesh.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\showmesh.c
nkf -s <..\mesh_comp\subdomain.c >ooo.tmp
copy ooo.tmp ..\mesh_comp\subdomain.c
nkf -s <..\mesh_exec\boundary_data.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\boundary_data.c
nkf -s <..\mesh_exec\get_mesh_data.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\get_mesh_data.c
nkf -s <..\mesh_exec\get_midpoints.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\get_midpoints.c
nkf -s <..\mesh_exec\make_MESH_REF.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\make_MESH_REF.c
nkf -s <..\mesh_exec\make_boundary_edat.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\make_boundary_edat.c
nkf -s <..\mesh_exec\make_boundary_nset.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\make_boundary_nset.c
nkf -s <..\mesh_exec\make_boundary_plot_data.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\make_boundary_plot_data.c
nkf -s <..\mesh_exec\make_feel_data_file.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\make_feel_data_file.c
nkf -s <..\mesh_exec\make_ip_data.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\make_ip_data.c
nkf -s <..\mesh_exec\mesh_book_exec.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\mesh_book_exec.c
nkf -s <..\mesh_exec\mesh_info_for_meshbook.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\mesh_info_for_meshbook.c
nkf -s <..\mesh_exec\mid_info_for_meshbook.c >ooo.tmp
copy ooo.tmp ..\mesh_exec\mid_info_for_meshbook.c
nkf -s <..\mesh_exec_1D\make_feel_data_file_1D.c >ooo.tmp
copy ooo.tmp ..\mesh_exec_1D\make_feel_data_file_1D.c
nkf -s <..\mesh_exec_1D\mesh_exec_1D.c >ooo.tmp
copy ooo.tmp ..\mesh_exec_1D\mesh_exec_1D.c
nkf -s <..\mesh_interface\get_face_from_region.c >ooo.tmp
copy ooo.tmp ..\mesh_interface\get_face_from_region.c
nkf -s <..\mesh_interface\make_mesh_region.c >ooo.tmp
copy ooo.tmp ..\mesh_interface\make_mesh_region.c
nkf -s <..\mesh_interface\make_point_in_face.c >ooo.tmp
copy ooo.tmp ..\mesh_interface\make_point_in_face.c
nkf -s <..\mesh_interface\make_region_divide_complete.c >ooo.tmp
copy ooo.tmp ..\mesh_interface\make_region_divide_complete.c
nkf -s <..\mesh_interface\make_region_order.c >ooo.tmp
copy ooo.tmp ..\mesh_interface\make_region_order.c
nkf -s <..\mesh_interface\mesh_control.c >ooo.tmp
copy ooo.tmp ..\mesh_interface\mesh_control.c
nkf -s <..\mesh_interface\mesh_generate_main.c >ooo.tmp
copy ooo.tmp ..\mesh_interface\mesh_generate_main.c
nkf -s <..\mesh_interface\mesh_size.c >ooo.tmp
copy ooo.tmp ..\mesh_interface\mesh_size.c
nkf -s <..\mesh_interface\region_data.c >ooo.tmp
copy ooo.tmp ..\mesh_interface\region_data.c
nkf -s <..\mesh_interface\remake_face_point.c >ooo.tmp
copy ooo.tmp ..\mesh_interface\remake_face_point.c
nkf -s <..\parallel\para_block_data.c >ooo.tmp
copy ooo.tmp ..\parallel\para_block_data.c
nkf -s <..\parallel_lib\data_nodsub.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\data_nodsub.c
nkf -s <..\parallel_lib\data_plus.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\data_plus.c
nkf -s <..\parallel_lib\p_calc_eqno.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_calc_eqno.c
nkf -s <..\parallel_lib\p_close_file.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_close_file.c
nkf -s <..\parallel_lib\p_get_band.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_get_band.c
nkf -s <..\parallel_lib\p_make_eqno.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_make_eqno.c
nkf -s <..\parallel_lib\p_make_srbuff.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_make_srbuff.c
;nkf -s <..\parallel_lib\p_make_sreq.c >ooo.tmp
;copy ooo.tmp ..\parallel_lib\p_make_sreq.c
nkf -s <..\parallel_lib\p_memory_move.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_memory_move.c
nkf -s <..\parallel_lib\p_msbicg_stab.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_msbicg_stab.c
nkf -s <..\parallel_lib\p_read_d_nset.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_read_d_nset.c
nkf -s <..\parallel_lib\p_read_n_edat.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_read_n_edat.c
nkf -s <..\parallel_lib\p_read_ndat.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_read_ndat.c
nkf -s <..\parallel_lib\p_read_pedatA.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_read_pedatA.c
nkf -s <..\parallel_lib\p_read_pedatB.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_read_pedatB.c
nkf -s <..\parallel_lib\p_read_pedatC.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_read_pedatC.c
nkf -s <..\parallel_lib\p_read_prdat.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_read_prdat.c
nkf -s <..\parallel_lib\p_read_rdat.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_read_rdat.c
nkf -s <..\parallel_lib\p_read_sdat.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_read_sdat.c
nkf -s <..\parallel_lib\p_set_MJ.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_set_MJ.c
nkf -s <..\parallel_lib\p_solve_plset.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_solve_plset.c
nkf -s <..\parallel_lib\p_solve_pmset.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_solve_pmset.c
nkf -s <..\parallel_lib\p_unsym_mscg.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\p_unsym_mscg.c
nkf -s <..\parallel_lib\parallel_lib_make.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\parallel_lib_make.c
nkf -s <..\parallel_lib\parallel_report.c >ooo.tmp
copy ooo.tmp ..\parallel_lib\parallel_report.c
nkf -s <..\quadrature\get_quad_nodes_by_name.c >ooo.tmp
copy ooo.tmp ..\quadrature\get_quad_nodes_by_name.c
nkf -s <..\quadrature\quadrature.c >ooo.tmp
copy ooo.tmp ..\quadrature\quadrature.c
nkf -s <..\scheme_comp\AVScontour.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\AVScontour.c
nkf -s <..\scheme_comp\AVSoutput.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\AVSoutput.c
nkf -s <..\scheme_comp\adaptmesh.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\adaptmesh.c
nkf -s <..\scheme_comp\contour.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\contour.c
nkf -s <..\scheme_comp\contour_file.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\contour_file.c
nkf -s <..\scheme_comp\displacement.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\displacement.c
nkf -s <..\scheme_comp\goto.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\goto.c
nkf -s <..\scheme_comp\if.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\if.c
nkf -s <..\scheme_comp\label.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\label.c
nkf -s <..\scheme_comp\let.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\let.c
nkf -s <..\scheme_comp\norm.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\norm.c
nkf -s <..\scheme_comp\perspect.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\perspect.c
nkf -s <..\scheme_comp\plot.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\plot.c
nkf -s <..\scheme_comp\read.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\read.c
nkf -s <..\scheme_comp\scheme_block.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\scheme_block.c
nkf -s <..\scheme_comp\showvec.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\showvec.c
nkf -s <..\scheme_comp\showvec_file.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\showvec_file.c
nkf -s <..\scheme_comp\write.c >ooo.tmp
copy ooo.tmp ..\scheme_comp\write.c
nkf -s <..\solve_comp\dbg_show_elem_dat.c >ooo.tmp
copy ooo.tmp ..\solve_comp\dbg_show_elem_dat.c
nkf -s <..\solve_comp\edat_make.c >ooo.tmp
copy ooo.tmp ..\solve_comp\edat_make.c
nkf -s <..\solve_comp\elem_dat_make.c >ooo.tmp
copy ooo.tmp ..\solve_comp\elem_dat_make.c
nkf -s <..\solve_comp\element_node.c >ooo.tmp
copy ooo.tmp ..\solve_comp\element_node.c
nkf -s <..\solve_comp\get_femvarinfo.c >ooo.tmp
copy ooo.tmp ..\solve_comp\get_femvarinfo.c
nkf -s <..\solve_comp\make_fem_varinfo.c >ooo.tmp
copy ooo.tmp ..\solve_comp\make_fem_varinfo.c
nkf -s <..\solve_comp\make_mesh_ctrl_data.c >ooo.tmp
copy ooo.tmp ..\solve_comp\make_mesh_ctrl_data.c
nkf -s <..\solve_comp\make_subdomain_info.c >ooo.tmp
copy ooo.tmp ..\solve_comp\make_subdomain_info.c
nkf -s <..\solve_comp\set_boundary_no.c >ooo.tmp
copy ooo.tmp ..\solve_comp\set_boundary_no.c
nkf -s <..\solve_comp\solve.c >ooo.tmp
copy ooo.tmp ..\solve_comp\solve.c
nkf -s <..\solve_comp\solve_dat_make.c >ooo.tmp
copy ooo.tmp ..\solve_comp\solve_dat_make.c
nkf -s <..\solve_fort77\MakeEdgeBasis_IEDPIENP.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\MakeEdgeBasis_IEDPIENP.c
nkf -s <..\solve_fort77\call_LISP_procedure_WEQ.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\call_LISP_procedure_WEQ.c
nkf -s <..\solve_fort77\ctrl77_subdomain.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\ctrl77_subdomain.c
nkf -s <..\solve_fort77\elem77_main_CG.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\elem77_main_CG.c
nkf -s <..\solve_fort77\elem77_main_CG_non.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\elem77_main_CG_non.c
nkf -s <..\solve_fort77\elem77_main_MPPSCG.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\elem77_main_MPPSCG.c
nkf -s <..\solve_fort77\elem77_main_sk.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\elem77_main_sk.c
nkf -s <..\solve_fort77\elem77_main_sk_non.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\elem77_main_sk_non.c
nkf -s <..\solve_fort77\gauss_quad.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\gauss_quad.c
nkf -s <..\solve_fort77\get_femvarinfo_ptr_by_name.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\get_femvarinfo_ptr_by_name.c
nkf -s <..\solve_fort77\make_coff_vect.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_coff_vect.c
nkf -s <..\solve_fort77\make_collec_sol.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_collec_sol.c
nkf -s <..\solve_fort77\make_ctrl77_CG.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ctrl77_CG.c
nkf -s <..\solve_fort77\make_ctrl77_CG_non.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ctrl77_CG_non.c
nkf -s <..\solve_fort77\make_ctrl77_MPPSCG.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ctrl77_MPPSCG.c
nkf -s <..\solve_fort77\make_ctrl77_sk.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ctrl77_sk.c
nkf -s <..\solve_fort77\make_ctrl77_sk_non.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ctrl77_sk_non.c
nkf -s <..\solve_fort77\make_dcond_CG.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_dcond_CG.c
nkf -s <..\solve_fort77\make_dcond_CG_nonlinear.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_dcond_CG_nonlinear.c
nkf -s <..\solve_fort77\make_dcond_MPPSCG.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_dcond_MPPSCG.c
nkf -s <..\solve_fort77\make_dcond_sk.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_dcond_sk.c
nkf -s <..\solve_fort77\make_dcond_sk_non.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_dcond_sk_non.c
nkf -s <..\solve_fort77\make_ecal.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ecal.c
nkf -s <..\solve_fort77\make_ecal_analytic.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ecal_analytic.c
nkf -s <..\solve_fort77\make_ecal_elem_div.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ecal_elem_div.c
nkf -s <..\solve_fort77\make_ecal_num.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ecal_num.c
nkf -s <..\solve_fort77\make_ecal_num_non.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ecal_num_non.c
nkf -s <..\solve_fort77\make_edev.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_edev.c
nkf -s <..\solve_fort77\make_edge_basis.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_edge_basis.c
nkf -s <..\solve_fort77\make_elem_commons.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_elem_commons.c
nkf -s <..\solve_fort77\make_elem_lisp.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_elem_lisp.c
nkf -s <..\solve_fort77\make_eset.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_eset.c
nkf -s <..\solve_fort77\make_fem_funcs_bound.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_fem_funcs_bound.c
nkf -s <..\solve_fort77\make_known_eval_var.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_known_eval_var.c
nkf -s <..\solve_fort77\make_ncond_CG.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ncond_CG.c
nkf -s <..\solve_fort77\make_ncond_MPPSCG.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ncond_MPPSCG.c
nkf -s <..\solve_fort77\make_ncond_lisp.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ncond_lisp.c
nkf -s <..\solve_fort77\make_ncond_skyline.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_ncond_skyline.c
nkf -s <..\solve_fort77\make_nedev.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_nedev.c
nkf -s <..\solve_fort77\make_solve77_data.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_solve77_data.c
nkf -s <..\solve_fort77\make_solve_fort77.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_solve_fort77.c
nkf -s <..\solve_fort77\make_solve_lisp.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_solve_lisp.c
nkf -s <..\solve_fort77\make_test_funcs_vect.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_test_funcs_vect.c
nkf -s <..\solve_fort77\make_unknown_eval_var.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_unknown_eval_var.c
nkf -s <..\solve_fort77\make_weak_eq_WEQ.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\make_weak_eq_WEQ.c
nkf -s <..\solve_fort77\ncond_element_parameter.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\ncond_element_parameter.c
nkf -s <..\solve_fort77\read_LISP_procedure.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\read_LISP_procedure.c
nkf -s <..\solve_fort77\solve_lisp_exec.c >ooo.tmp
copy ooo.tmp ..\solve_fort77\solve_lisp_exec.c
nkf -s <..\sys_lib\sys_lib.c >ooo.tmp
copy ooo.tmp ..\sys_lib\sys_lib.c
nkf -s <..\system\CloseFile.c >ooo.tmp
copy ooo.tmp ..\system\CloseFile.c
nkf -s <..\system\ClosePipe.c >ooo.tmp
copy ooo.tmp ..\system\ClosePipe.c
nkf -s <..\system\DangerCode.c >ooo.tmp
copy ooo.tmp ..\system\DangerCode.c
nkf -s <..\system\EraseTemporaryFiles.c >ooo.tmp
copy ooo.tmp ..\system\EraseTemporaryFiles.c
nkf -s <..\system\ErrorMessage.c >ooo.tmp
copy ooo.tmp ..\system\ErrorMessage.c
nkf -s <..\system\FEEL_FreeMemory.c >ooo.tmp
copy ooo.tmp ..\system\FEEL_FreeMemory.c
nkf -s <..\system\FEEL_GetMemory.c >ooo.tmp
copy ooo.tmp ..\system\FEEL_GetMemory.c
nkf -s <..\system\File.c >ooo.tmp
copy ooo.tmp ..\system\File.c
nkf -s <..\system\FreeString.c >ooo.tmp
copy ooo.tmp ..\system\FreeString.c
nkf -s <..\system\GetMaxInteger.c >ooo.tmp
copy ooo.tmp ..\system\GetMaxInteger.c
nkf -s <..\system\LISP_SEND.c >ooo.tmp
copy ooo.tmp ..\system\LISP_SEND.c
nkf -s <..\system\MakeDeletefile.c >ooo.tmp
copy ooo.tmp ..\system\MakeDeletefile.c
nkf -s <..\system\MakeFORTsrc.c >ooo.tmp
copy ooo.tmp ..\system\MakeFORTsrc.c
nkf -s <..\system\MakeMakefile.c >ooo.tmp
copy ooo.tmp ..\system\MakeMakefile.c
nkf -s <..\system\MakeMemoryCopy.c >ooo.tmp
copy ooo.tmp ..\system\MakeMemoryCopy.c
nkf -s <..\system\MakeStringCopy.c >ooo.tmp
copy ooo.tmp ..\system\MakeStringCopy.c
nkf -s <..\system\NotImplementMessage.c >ooo.tmp
copy ooo.tmp ..\system\NotImplementMessage.c
nkf -s <..\system\OpenFile.c >ooo.tmp
copy ooo.tmp ..\system\OpenFile.c
nkf -s <..\system\OpenPipe.c >ooo.tmp
copy ooo.tmp ..\system\OpenPipe.c
nkf -s <..\system\Pop.c >ooo.tmp
copy ooo.tmp ..\system\Pop.c
nkf -s <..\system\ReverseDoubleArray.c >ooo.tmp
copy ooo.tmp ..\system\ReverseDoubleArray.c
nkf -s <..\system\ReverseIntArray.c >ooo.tmp
copy ooo.tmp ..\system\ReverseIntArray.c
nkf -s <..\system\ReverseStringArray.c >ooo.tmp
copy ooo.tmp ..\system\ReverseStringArray.c
nkf -s <..\system\StrEq.c >ooo.tmp
copy ooo.tmp ..\system\StrEq.c
nkf -s <..\system\SystemMessage.c >ooo.tmp
copy ooo.tmp ..\system\SystemMessage.c
nkf -s <..\system\TEST_term_convert.c >ooo.tmp
copy ooo.tmp ..\system\TEST_term_convert.c
nkf -s <..\system\XYZ_dimension.c >ooo.tmp
copy ooo.tmp ..\system\XYZ_dimension.c
nkf -s <..\system\basic_type_functions.c >ooo.tmp
copy ooo.tmp ..\system\basic_type_functions.c
nkf -s <..\system\cpu_time.c >ooo.tmp
copy ooo.tmp ..\system\cpu_time.c
nkf -s <..\system\f77src.c >ooo.tmp
copy ooo.tmp ..\system\f77src.c
nkf -s <..\system\get.c >ooo.tmp
copy ooo.tmp ..\system\get.c
nkf -s <..\system\get_user_info.c >ooo.tmp
copy ooo.tmp ..\system\get_user_info.c
nkf -s <..\system\is_member.c >ooo.tmp
copy ooo.tmp ..\system\is_member.c
nkf -s <..\system\make_list_st.c >ooo.tmp
copy ooo.tmp ..\system\make_list_st.c
nkf -s <..\system\myatof.c >ooo.tmp
copy ooo.tmp ..\system\myatof.c
nkf -s <..\system\reverse_code_convert.c >ooo.tmp
copy ooo.tmp ..\system\reverse_code_convert.c
nkf -s <..\system\show_basic_struct.c >ooo.tmp
copy ooo.tmp ..\system\show_basic_struct.c
nkf -s <..\system\sort.c >ooo.tmp
copy ooo.tmp ..\system\sort.c
nkf -s <..\system\strindex.c >ooo.tmp
copy ooo.tmp ..\system\strindex.c
nkf -s <..\system\term_convert.c >ooo.tmp
copy ooo.tmp ..\system\term_convert.c
nkf -s <..\system\term_convert_scalar.c >ooo.tmp
copy ooo.tmp ..\system\term_convert_scalar.c
nkf -s <..\system\tolower.c >ooo.tmp
copy ooo.tmp ..\system\tolower.c
nkf -s <..\system\uniq_list.c >ooo.tmp
copy ooo.tmp ..\system\uniq_list.c
nkf -s <..\test\debug_start.c >ooo.tmp
copy ooo.tmp ..\test\debug_start.c
nkf -s <..\test\o.c >ooo.tmp
copy ooo.tmp ..\test\o.c
nkf -s <..\test\xplotv.c >ooo.tmp
copy ooo.tmp ..\test\xplotv.c
nkf -s <..\tmp\make_ecal_numintegral2D.c >ooo.tmp
copy ooo.tmp ..\tmp\make_ecal_numintegral2D.c
nkf -s <..\var_comp\ewise_info.c >ooo.tmp
copy ooo.tmp ..\var_comp\ewise_info.c
nkf -s <..\var_comp\get_elem_name_by_ND.c >ooo.tmp
copy ooo.tmp ..\var_comp\get_elem_name_by_ND.c
nkf -s <..\var_comp\get_fem_var_freedom_by_ND.c >ooo.tmp
copy ooo.tmp ..\var_comp\get_fem_var_freedom_by_ND.c
nkf -s <..\var_comp\is_number_string.c >ooo.tmp
copy ooo.tmp ..\var_comp\is_number_string.c
nkf -s <..\var_comp\var_comp.c >ooo.tmp
copy ooo.tmp ..\var_comp\var_comp.c
nkf -s <..\var_comp\var_init.c >ooo.tmp
copy ooo.tmp ..\var_comp\var_init.c
nkf -s <..\win32tool\makenmakesub.c >ooo.tmp
copy ooo.tmp ..\win32tool\makenmakesub.c
nkf -s <..\win32tool\makesjisbat.c >ooo.tmp
copy ooo.tmp ..\win32tool\makesjisbat.c
nkf -s <..\yacc\YaccExpression.c >ooo.tmp
copy ooo.tmp ..\yacc\YaccExpression.c
nkf -s <..\yacc\YaccMain.c >ooo.tmp
copy ooo.tmp ..\yacc\YaccMain.c
nkf -s <..\yacc\expression_term.c >ooo.tmp
copy ooo.tmp ..\yacc\expression_term.c
nkf -s <..\yacc\lex.yy.c >ooo.tmp
copy ooo.tmp ..\yacc\lex.yy.c
nkf -s <..\yacc\y.tab.c >ooo.tmp
copy ooo.tmp ..\yacc\y.tab.c
nkf -s <..\feel_def\feel_def.h >ooo.tmp
copy ooo.tmp ..\feel_def\feel_def.h 
