# THIS MAKEFILE IS GENERATED BY MAKEMAKE PROGRAM.
# Typical usage of makemake command is as follows.
#
# DIR | makemake execute-filename
#

cc   = cl
f77  = fl32
link = link

proj = feel.Div
objs = bndnod.obj input.obj main.obj output.obj renum4.obj rmkjac.obj 

all : $(proj).exe

$(proj).exe: $(objs)
	$(link) $(objs) $(f77libs) $(gui_libs) -out:$@ $(lflags) \
           $(lnk_debug) $(guiflags)

bndnod.obj  :   bndnod.f
	$(f77) $(fflags) bndnod.f /c

input.obj  :   input.f
	$(f77) $(fflags) input.f /c

main.obj  :   main.f
	$(f77) $(fflags) main.f /c

output.obj  :   output.f
	$(f77) $(fflags) output.f /c

renum4.obj  :   renum4.f
	$(f77) $(fflags) renum4.f /c

rmkjac.obj  :   rmkjac.f
	$(f77) $(fflags) rmkjac.f /c


clean :
	-del *.obj
	-del *.exe
