#include <stdio.h>

lisp_exp_print( fp )
     FILE *fp;
{
  fprintf(fp,";----------------------------------------------------------------------------\n");
  fprintf(fp,";  FESL Finite Element Simulation Language FORTRAN77 Code Generator\n");
  fprintf(fp,";\n");
  fprintf(fp,";  Sub-program\n");
  fprintf(fp,";\n");
  fprintf(fp,";  Made      1992/02/24\n");
  fprintf(fp,";----------------------------------------------------------------------------\n");
  fprintf(fp,";----------------------------------------------------------------------------\n");
  fprintf(fp,";  補助関数  リスプ形式の接頭記法から挿入記法への変換\n");
  fprintf(fp,";         培風館 『LISP』より引用\n");
  fprintf(fp,";----------------------------------------------------------------------------\n");
  fprintf(fp,"(defun exp-print (lst)\n");
  fprintf(fp,"  (list-print-x (pre-to-inf lst) t))\n");
  fprintf(fp,"\n");
  fprintf(fp,"(defun exp-print-fp (lst fp)\n");
  fprintf(fp,"  (list-print-x (pre-to-inf lst) fp))\n");
  fprintf(fp,"\n");
  fprintf(fp,"(defun pre-to-inf (l)\n");
  fprintf(fp,"  (cond ((null l) nil)\n");
  fprintf(fp,"	((atom l)  l )\n");
  fprintf(fp,"	((null (member (car l) '( + - * / ^))) \n");
  fprintf(fp,"	 (cons (car l) (mapcar #'pre-to-inf (cdr l))))\n");
  fprintf(fp,"	(t (pre-to-inf-aux  (mapcar #'pre-to-inf (cdr l)) (car l)))))\n");
  fprintf(fp,"\n");
  fprintf(fp,"(defun pre-to-inf-aux  (lst smbl)\n");
  fprintf(fp,"  (cdr (pre-to-inf-aux2 lst smbl)))\n");
  fprintf(fp,"		 \n");
  fprintf(fp,"(defun pre-to-inf-aux2 ( lst  smbl)\n");
  fprintf(fp,"  (cond ((null lst) nil)\n");
  fprintf(fp,"	(t (append (list smbl (car lst)) (pre-to-inf-aux2 (cdr lst) smbl)))))\n");
  fprintf(fp,";--------------------------------------------------------------------------\n");
  fprintf(fp,"; LIST-PRINT\n");
  fprintf(fp,"; Made      1992/01/30\n");
  fprintf(fp,"; Modified  1992/02/18\n");
  fprintf(fp,"; Modified  1993/11/18\n");
  fprintf(fp,";--------------------------------------------------------------------------\n");
  fprintf(fp,"(defun list-print-x (lst FP)\n");
  fprintf(fp,"  (PROGN  (list-print lst FP)(format FP \"~%%\")))\n");
  fprintf(fp,"(defun list-print (lst FP)\n");
  fprintf(fp,"  (cond ((floatp  lst) (FORMAT FP \"~A\"   lst ))\n");
  fprintf(fp,"	((numberp lst) (FORMAT FP \"~A\" lst ))\n");
  fprintf(fp,"	((atom lst)    (FORMAT FP \"~S\"     lst ))\n");
  fprintf(fp,"	((is-function-exp lst) \n");
  fprintf(fp,"	 (do ((dlst (cdr lst)                    (cdr dlst))\n");
  fprintf(fp,"	      (num       0                       (+ 1 num) )\n");
  fprintf(fp,"	      (func (format fp \"~S(\" (car lst))            ))\n");
  fprintf(fp,"	     ((null dlst) (format fp \")\"))\n");
  fprintf(fp,"	     (progn (cond \n");
  fprintf(fp,"		     ((floatp  (car dlst)) (FORMAT FP \"~A\" (car dlst)))\n");
  fprintf(fp,"		     ((numberp (car dlst)) (FORMAT FP \"~A\" (car dlst)))\n");
  fprintf(fp,"		     ((atom    (car dlst)) (FORMAT FP \"~A\"   (car dlst)))\n");
  fprintf(fp,"		     (t \n");
  fprintf(fp,"		      (progn (format fp \"(\")\n");
  fprintf(fp,"			     (list-print (car dlst) FP)\n");
  fprintf(fp,"			     (FORMAT FP \")\"))))\n");
  fprintf(fp,"		    (if(eq 0 num) t\n");
  fprintf(fp,"		      (format fp \",\")))))\n");
  fprintf(fp,"	(t\n");
  fprintf(fp,"	 (do ((dlst (FORT77-CONVERT lst) (cdr dlst)))\n");
  fprintf(fp,"	     ((null dlst) t )\n");
  fprintf(fp,"	     (cond \n");
  fprintf(fp,"		   ((floatp  (car dlst)) (FORMAT FP \"~A\" (car dlst)))\n");
  fprintf(fp,"		   ((numberp (car dlst)) (FORMAT FP \"~A\" (car dlst)))\n");
  fprintf(fp,"		   ((atom    (car dlst)) (FORMAT FP \"~A\" (car dlst)))\n");
  fprintf(fp,"		   (t (progn(FORMAT FP \"(\")\n");
  fprintf(fp,"			    (list-print (car dlst) FP)\n");
  fprintf(fp,"			    (FORMAT FP \")\"))))))))\n");
  fprintf(fp,"\n");
  fprintf(fp,";--------------------------------------------------------------------------\n");
  fprintf(fp,"; FORT77-CONVERT\n");
  fprintf(fp,";\n");
  fprintf(fp,";--------------------------------------------------------------------------\n");
  fprintf(fp,"(defun FORT77-CONVERT (LST)\n");
  fprintf(fp,"  (COND ((EQ LST '^) '**)\n");
  fprintf(fp,"	((ATOM LST ) LST)\n");
  fprintf(fp,"	(T (CONS (FORT77-CONVERT (CAR LST))\n");
  fprintf(fp,"		 (FORT77-CONVERT (CDR LST))))))\n");
  fprintf(fp,";--------------------------------------------------------------------------\n");
  fprintf(fp,"; funtion test\n");
  fprintf(fp,";--------------------------------------------------------------------------\n");
  fprintf(fp,"(defun is-function-exp ( lst )\n");
  fprintf(fp,"  (cond ((member '+ lst) nil)\n");
  fprintf(fp,"	((member '- lst) nil)\n");
  fprintf(fp,"	((member '* lst) nil)\n");
  fprintf(fp,"	((member '/ lst) nil)\n");
  fprintf(fp,"	((member '^ lst) nil)\n");
  fprintf(fp,"	((member '** lst) nil)\n");
  fprintf(fp,"	(t t)))\n");
  fprintf(fp,"\n");
  fprintf(fp,"	 \n");
  fprintf(fp,"\n");
  fprintf(fp,"\n");
  fprintf(fp,"\n");
  fprintf(fp,"\n");
}
