feel.data : data_main.o read_data.o read_data2.o read_mesh.o read_node.o f_alloc.o data_num0.o data_eq1.o data_wrt.o data_sdrv.o data_aiin.o data_prod.o data_ncond1.o  data_dcond1.o 
	f77 -o feel.data data_main.o read_data.o read_data2.o read_mesh.o read_node.o f_alloc.o data_num0.o data_eq1.o data_wrt.o data_sdrv.o data_aiin.o data_prod.o data_ncond1.o data_dcond1.o 
data_main.o : data_main.f
	f77 -c -O  data_main.f
read_data.o : read_data.f
	f77 -c -O  read_data.f
read_data2.o : read_data2.f
	f77 -c -O read_data2.f         
read_mesh.o : read_mesh.f
	f77 -c -O  read_mesh.f         
read_node.o : read_node.f
	f77 -c -O  read_node.f         
f_alloc.o : f_alloc.f
	f77 -c -O  f_alloc.f         
data_num0.o :  data_num0.f
	f77 -c -O  data_num0.f
data_eq1.o : data_eq1.f
	f77 -c -O  data_eq1.f
data_wrt.o : data_wrt.f
	f77 -c -O  data_wrt.f
data_sdrv.o : data_sdrv.f	
	f77 -c -O  data_sdrv.f
data_aiin.o : data_aiin.f
	f77 -c -O  data_aiin.f	
data_prod.o : data_prod.f
	f77 -c -O  data_prod.f
data_ncond1.o : data_ncond1.f
	f77 -c -O  data_ncond1.f
data_dcond1.o : data_dcond1.f
	f77 -c -O  data_dcond1.f
