cd ../yacc           ; ../win32tool/makenmakefile.bat yacc
cd ../element        ; ../win32tool/makenmakefile.bat element
cd ../mesh_comp      ; ../win32tool/makenmakefile.bat mesh_comp
cd ../var_comp       ; ../win32tool/makenmakefile.bat var_comp
cd ../system         ; ../win32tool/makenmakefile.bat system
cd ../main           ; ../win32tool/makenmakefile.bat main
cd ../makefort77     ; ../win32tool/makenmakefile.bat makefort77
cd ../parallel       ; ../win32tool/makenmakefile.bat parallel
cd ../check          ; ../win32tool/makenmakefile.bat check
cd ../fort77lib      ; ../win32tool/makenmakefile.bat fort77lib
cd ../scheme_comp    ; ../win32tool/makenmakefile.bat scheme_comp
cd ../solve_comp     ; ../win32tool/makenmakefile.bat solve_comp
cd ../solve_fort77   ; ../win32tool/makenmakefile.bat solve_fort77
cd ../lisp_util      ; ../win32tool/makenmakefile.bat lisp_util
cd ../lisp_c         ; ../win32tool/makenmakefile.bat lisp_c
cd ../mesh_exec      ; ../win32tool/makenmakefile.bat mesh_exec
cd ../mesh_bamg_exec ; ../win32tool/makenmakefile.bat mesh_bamg_exec
cd ../mesh_exec_1D   ; ../win32tool/makenmakefile.bat mesh_exec_1D
cd ../quadrature     ; ../win32tool/makenmakefile.bat quadrature
cd ../lisp_lib       ; ../win32tool/makenmakefile.bat lisp_lib
cd ../let            ; ../win32tool/makenmakefile.bat let
cd ../geom2d         ; ../win32tool/makenmakefile.bat geom2d
cd ../parallel_lib   ; ../win32tool/makenmakefile.bat parallel_lib
