/*
 *   feel p2  Finite Element Equation Language Prototype Version 2
 *            ~      ~       ~        ~
 *      File:   bamg_geometric_edge.c
 *      Date:   1997/06/13
 *  Modified:   1997/07/22
 *   
 *   Purpose:   read geometric edge information
 *   Functions: 
 *              
 *              
 */

#include <stdio.h>
#include "edat.h"

static int  edges;
static int *edge_node_ptr;



/*
 *  Caution  These vertices number is not in bamg.geom 
 *           But current version of bamg must be same.....
 *
 */


void bamg_geometric_edge_read(fp)
     FILE *fp;
{
  int i;
  
  fscanf(fp,"%d",&edges);

  edge_node_ptr = (int *)malloc(sizeof(int)*2*edges);
  if(edge_node_ptr == NULL) {
    fprintf(stderr,"cannot allocate edge_node_ptr\n");
    exit(1);
  }

  for(i=0;i<edges;i++) {
    fscanf(fp,"%d %d",edge_node_ptr+i*2+0,edge_node_ptr+i*2+1);
  }

  return;
}

void make_bamg_boundary2D(edat_ptr,edge_2d_ptr,edge_nodes)
     FEM_edat *edat_ptr;
     EDGE_2d  *edge_2d_ptr;
     int       edge_nodes;     /* mid nodes on edge */
{
  int i,j,k;

  int  edgeno;
  int  from,to;

  /*------------------*/
  /* for vertex array */
  /*------------------*/
  int     vno_idx;   /* vertex number index for one Geometrical Edge */
  int     vno_max;   /* Maximum vertex number on one Geometrical Edge */
  int    *vno_ptr;   /* Number pointer */
  double *pos_ptr;   /* position index pointer */
  
  VonGEdge *vongedge_ptr,*get_vongedge_ptr();
  int       nvongedge;

  int       sort_flag;  /* sort flag for mid point on geometrical
                           edge added for rect in 99/04/30        */
  int       sort_idx_from;
  int       sort_idx_to;

  /*------------------*/
  /* for edge array   */
  /*------------------*/
  int *edgeno_ptr;    /* Edge number pointer */
  int *inverse_flag;  /* Inverse flag        */

  int  max_neg_pn;
  int *neg_pn;
  int *egno_tbl_en;
  int *eg_nnos;

  int  c_edges;       /* connecting edges      */
  int  can_edgeno;    /* candidate edge number */
  int  find_flag;


  /*------------------------*/
  /* for final vertex array */
  /*------------------------*/
  int  nod_max;   /* Estimated maximum nodes on one geometrical edges */
  int  nnodes;    /* Number of nodes on each Geometric edges */
  int  nod_idx;   /* work index     */
  int *nod_ptr;   /* Memory pointer */
  int *edge_node_no;  /* edge node number for mid points on edges */

  int *push_ptr;  /* Node number array for push */



  nvongedge    = how_many_verticesOnGEdge();
  vongedge_ptr = get_vongedge_ptr();


  /*-------------------------------------*/
  /* Allocation of each temporary arrays */
  /*-------------------------------------*/
  /* nvongedge +2 must be enough for vno_max estimation */
  /*-------------------------------------*/
  /*==*/
  vno_max      = nvongedge + 2;
  vno_ptr      = (int *)   malloc(sizeof(int)*vno_max);
  pos_ptr      = (double *)malloc(sizeof(double)*vno_max);
  if(vno_ptr == NULL || pos_ptr == NULL) {
    fprintf(stderr,"Cannot allocate memory for vno_ptr\n");
    exit(1);
  }

  /*==*/
  edgeno_ptr   = (int *)malloc(sizeof(int)*vno_max);
  inverse_flag = (int *)malloc(sizeof(int)*vno_max);
  if(edgeno_ptr == NULL || inverse_flag == NULL) {
    fprintf(stderr,"Cannot allocate memory for edgeno_ptr,inverse_flag\n");
    exit(1);
  }

  /*==*/
  nod_max = vno_max*(edge_nodes+1)+1;
  nod_ptr = (int *)malloc(sizeof(int)*nod_max);
  if(nod_ptr == NULL) {
    fprintf(stderr,"Cannot allocate memory for nod_ptr\n");
    exit(1);
  }
  
  /* Loop for edge for geometry file */
  for(i=0;i<edges;i++) {


    edgeno  = i+1;
    from    = *(edge_node_ptr+i*2+0);
    to      = *(edge_node_ptr+i*2+1);
    vno_idx =   0;

#ifdef DBG
    fprintf(stderr,"DDD: i= %d\n",i);
    fprintf(stderr,"DDD: from = %d\n",from);
    fprintf(stderr,"DDD: to   = %d\n",to);
    fprintf(stderr,"DDD: nvongedge= %d\n",nvongedge);
    fprintf(stderr,"---\n");
#endif
    

    /*----------------------------------------------------
     *  First make array for vertices (without mid points) 
     *  in geometrical edge                               
     *----------------------------------------------------*/

    /* starting point */
    *(vno_ptr+vno_idx) = from;
    *(pos_ptr+vno_idx) = 0.0;
    sort_idx_from = vno_idx;
    vno_idx++;

    /* mid point generated by bamg in geometrical edge */
    
    /* 99/04/30  rect IMPORTANT */

    /* BAMG for rectangulars cause the ordering violation.
     * For every geometrical edge, the mid point list is
     * sorted, but for rectangular, not sorted.
     */
    
    sort_flag = 0; 

    for(j=0;j<nvongedge;j++) {
      if((vongedge_ptr+j)->edge_no == edgeno) {
	*(vno_ptr+vno_idx) = (vongedge_ptr+j)->node_no;
	*(pos_ptr+vno_idx) = (vongedge_ptr+j)->pos;

	if(*(pos_ptr+vno_idx) < *(pos_ptr+vno_idx-1)) {
          sort_flag = 1;

#ifdef DBG
          fprintf(stderr,"j=%d\n",j);
          fprintf(stderr," %lf < %lf\n",*(pos_ptr+vno_idx),
                                        *(pos_ptr+vno_idx-1));
	  fprintf(stderr,"Inconsistent VertexOnGeometricEdge data\n");
	  fprintf(stderr,"BAMG may be version uped.....\n");
	  fprintf(stderr,"Fatal error in bamg_geometric_edge\n");
#endif

	}

	vno_idx++;  /* Caution, not to erase this line */
      }

    }  /* end of VertexOnGeometricEdge */
    /* ending point */
    *(vno_ptr+vno_idx) = to;
    *(pos_ptr+vno_idx) = 1.0;
    sort_idx_to = vno_idx;
    vno_idx++;

    if(sort_flag == 1) {  /* NEED TO SORT */
      void sort_midpoints_on_gedge();

      sort_midpoints_on_gedge(vno_ptr,pos_ptr,sort_idx_from,
                                              sort_idx_to   );
    
    }




    /* debug */
    /*
    for(j=0;j<vno_idx;j++) {
      fprintf(stderr,
	      "%d : %d  %d  %lf\n",edgeno,j+1,*(vno_ptr+j),*(pos_ptr+j));
    }
    fprintf(stderr,"-------\n");
    */
    
    /*---------------------------------------------
     *  Secondary, make edge array 
     *---------------------------------------------*/
    max_neg_pn   = edge_2d_ptr->max_neg_pn;
    neg_pn       = edge_2d_ptr->neg_pn;
    egno_tbl_en  = edge_2d_ptr->egno_tbl_en;
    eg_nnos      = edge_2d_ptr->eg_nnos;


    for(j=0;j<vno_idx-1;j++) {  /* sub-edge loop */
      
      from = *(vno_ptr+j);
      to   = *(vno_ptr+j+1);
      find_flag = NO;

      /*--------------------------*/
      /* search edge no (from,to) */
      /*--------------------------*/
      c_edges = *(neg_pn+(from-1));
      for(k=0;k<c_edges;k++) {
	can_edgeno = *(egno_tbl_en+(from-1)*max_neg_pn+k);
	
	if(from == *(eg_nnos+(can_edgeno-1)*2+0) &&
	   to   == *(eg_nnos+(can_edgeno-1)*2+1)    ) {
	  find_flag = YES;
	  *(edgeno_ptr+j) = can_edgeno;
	  *(inverse_flag+j) = NO;
	}

	if(from == *(eg_nnos+(can_edgeno-1)*2+1) &&
	   to   == *(eg_nnos+(can_edgeno-1)*2+0)    ) {
	  find_flag = YES;
	  *(edgeno_ptr+j) = can_edgeno;
	  *(inverse_flag+j) = YES;
	}
      }
      if(find_flag == NO) {
	fprintf(stderr,"Can't find correspoinding edge.  This must be BUG!\n");
	exit(1);
      }
    }


    /* DBG WRITE */
    /*    for(j=0;j<vno_idx-1;j++) {  
      fprintf(stderr,"Edge [%d] (%d-%d)(%d-%d)%d\n",*(edgeno_ptr+j),
	      *(vno_ptr+j),*(vno_ptr+j+1),
	      *(eg_nnos+(*(edgeno_ptr+j)-1)*2+0),
	      *(eg_nnos+(*(edgeno_ptr+j)-1)*2+1),*(inverse_flag+j));
    } */


    /*---------------------------------------------
     *  Push nodes in initial edge 
     *---------------------------------------------*/
    nnodes = (1+edge_nodes)*(vno_idx-1)+1;
    edge_node_no = edge_2d_ptr->edge_node_no;

    nod_idx = 0;
    for(j=0;j<vno_idx-1;j++) {  
      *(nod_ptr+nod_idx)=*(vno_ptr+j);
      nod_idx++;

      if(edge_nodes >0) {
	for(k=0;k<edge_nodes;k++) {
	  if(*(inverse_flag+j) == NO) {
	    *(nod_ptr+nod_idx) =
	      *(edge_node_no+edge_nodes*(*(edgeno_ptr+j)-1)+k);
	    nod_idx++;
	  }
	  else {
	    *(nod_ptr+nod_idx) =
	      *(edge_node_no+edge_nodes*(*(edgeno_ptr+j))-k-1);
	    nod_idx++;
	  }
	}
      }
    }
    *(nod_ptr+nod_idx) = *(vno_ptr+vno_idx-1);
    nod_idx++;
    if(nnodes != nod_idx) {
      fprintf(stderr,"There is bug in bamg_geometric edge.c\n");
      exit(1);
    }
    
    push_ptr = (int *)malloc(sizeof(int)*nod_idx);
    for(j=0;j<nod_idx;j++) {
      *(push_ptr+j) = *(nod_ptr+j);
    }
    /* Caution, In current version, *(nod_ptr) means from !!! */
    store_boundary_data_bamg(*(nod_ptr),*(nod_ptr+nod_idx-1),
			     nod_idx,-999,push_ptr);
    
  }

}


/* sort for VertexOnGeometricEdge */
void sort_midpoints_on_gedge(vno_ptr,pos_ptr,sort_idx_from,
                                             sort_idx_to   )
int    *vno_ptr;
double *pos_ptr;
int     sort_idx_from;
int     sort_idx_to;
{
      int i;

      int points;
      int *sortbuf,*numbuf;
      void voge_sort();
 
      points = sort_idx_to - sort_idx_from + 1;

      sortbuf = (int *)malloc(sizeof(int)*points);
      numbuf  = (int *)malloc(sizeof(int)*points);
      if(sortbuf == NULL || numbuf == NULL) {
        fprintf(stderr,"VertexOnGeometricEdge need to be sorted, but cannot allocate work memory\n");
        exit(1);
      }

      voge_sort(points,sortbuf,pos_ptr+sort_idx_from);

      for(i=0;i<points;i++) {
        *(numbuf +i) = *(vno_ptr + sort_idx_from + *(sortbuf+i));
      }
      for(i=0;i<points;i++) {
        *(vno_ptr + sort_idx_from + i) = *(numbuf+i);
      }  
      
      free(sortbuf);
      free(numbuf);


#ifdef DBG
      for(i=0;i<points;i++) {
	fprintf(stderr,"%d  %d  %lf\n",i+1,*(vno_ptr+sort_idx_from+i),
                                           *(pos_ptr+sort_idx_from+i));
      }
#endif 

}

void voge_sort(points,ptr,dptr)
int     points;
int    *ptr;
double *dptr;
{
   int i,j;
   int    iswap;
   double dswap;

   if(points <= 1) {
     fprintf(stderr,"DATA ERR in voge_sort\n");
     exit(1);
   }

   for(i=0;i<points;i++) {
     *(ptr+i) = i;
   }
   
   for(i=0;i<points-1;i++) {
    for(j=i+1;j<points;j++) {

      if(*(dptr+i) > *(dptr+j) ) {
         iswap = *(ptr +j);
         dswap = *(dptr+j);

         *(ptr + j) = *(ptr + i);
         *(dptr+ j) = *(dptr+ i);
         *(ptr + i) = iswap;
         *(dptr+ i) = dswap;
      }
    }
   }
   return;
}
       

