# THIS MAKEFILE IS GENERATED BY MAKEMAKE PROGRAM.
# Typical usage of makemake command is as follows.
#
# DIR | makemake execute-filename
#

cc   = cl /c  /DMSDOS
f77  = fl32
link = link

proj = feel.bamg
objs = StrEq.obj bamg_btof.obj bamg_feel_dat_header.obj bamg_feel_dat_ip.obj bamg_feel_dat_node.obj bamg_feel_dat_region_edat.obj bamg_geometric_edge.obj make_boundary_edat_bamg.obj make_boundary_nset_bamg.obj make_edge_info.obj make_element_ordering.obj make_feel2bamg_file.obj make_feel_dat_bamg.obj make_new_edat.obj make_plot_nset_bamg.obj read_bamg_mesh.obj read_bc_info.obj strindex.obj 

all : $(proj).exe

$(proj).exe: $(objs)
	$(link) $(objs) $(f77libs) $(gui_libs) -out:$@ $(lflags) \
           $(lnk_debug) $(guiflags)

StrEq.obj  :   StrEq.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) StrEq.c

bamg_btof.obj  :   bamg_btof.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) bamg_btof.c

bamg_feel_dat_header.obj  :   bamg_feel_dat_header.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) bamg_feel_dat_header.c

bamg_feel_dat_ip.obj  :   bamg_feel_dat_ip.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) bamg_feel_dat_ip.c

bamg_feel_dat_node.obj  :   bamg_feel_dat_node.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) bamg_feel_dat_node.c

bamg_feel_dat_region_edat.obj  :   bamg_feel_dat_region_edat.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) bamg_feel_dat_region_edat.c

bamg_geometric_edge.obj  :   bamg_geometric_edge.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) bamg_geometric_edge.c

dbg_xplot.obj  :   dbg_xplot.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) dbg_xplot.c

make_boundary_edat_bamg.obj  :   make_boundary_edat_bamg.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) make_boundary_edat_bamg.c

make_boundary_nset_bamg.obj  :   make_boundary_nset_bamg.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) make_boundary_nset_bamg.c

make_edge_info.obj  :   make_edge_info.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) make_edge_info.c

make_element_ordering.obj  :   make_element_ordering.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) make_element_ordering.c

make_feel2bamg_file.obj  :   make_feel2bamg_file.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) make_feel2bamg_file.c

make_feel_dat_bamg.obj  :   make_feel_dat_bamg.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) make_feel_dat_bamg.c

make_new_edat.obj  :   make_new_edat.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) make_new_edat.c

make_plot_nset_bamg.obj  :   make_plot_nset_bamg.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) make_plot_nset_bamg.c

read_bamg_mesh.obj  :   read_bamg_mesh.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) read_bamg_mesh.c

read_bc_info.obj  :   read_bc_info.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) read_bc_info.c

strindex.obj  :   strindex.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) strindex.c

xplotv.obj  :   xplotv.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) xplotv.c


clean :
	-del *.obj
	-del *.exe
