C*********************************************************************
C
C     CREATE MID POINTS         main.f
C
C*********************************************************************
      PROGRAM MIDPNT
C
      IMPLICIT REAL*8( A-H,O-Z )
C
      PARAMETER( KTJ = 10000 )
      PARAMETER( KTE = 10000 )
      PARAMETER( KTB = 100 )
      PARAMETER( KTC = 2000 )
C
      DIMENSION PXY( KTJ*10,2 ),INE( KTJ*10,40 ),JNE( KTJ*10 )
      DIMENSION MTJ( KTE,4 ),JAC( KTE,4 ),IDM( KTE )
      DIMENSION JNT(KTJ*10),INV(KTJ*10),IEDG(KTB,6),IBND(KTB,KTC)
      DIMENSION VMP1( 10 ),VMP2( 16,2 ),IORD( KTE )
      DIMENSION MTJ1( KTE,4,10 ),MTJ2( KTE,16 )
C
      CALL INPUT( NODE,NELM,MTJ,JAC,IDM,PXY,KTJ,KTE,
     &     NEDG,IEDG,IBND,KTB,KTC,NMP1,VMP1,NMP2,VMP2 )
C
      IF ( NMP1.EQ.0 .AND. NMP2.EQ.0 ) THEN
         NNOD = NODE
         DO 10 I=1,NODE
            JNT(I) = I
            INV(I) = I
 10      CONTINUE
         GOTO 1000
      ENDIF
C
      CALL NEWPNT( NODE,NELM,MTJ,JAC,PXY,KTJ,KTE,
     &     NMP1,VMP1,NMP2,VMP2,MTJ1,MTJ2,NNOD )
C
      CALL REELM( NELM,JAC,IORD,KTJ,KTE )
C
      CALL RENODE( NNOD,NELM,MTJ,JAC,NMP1,NMP2,MTJ1,MTJ2,IORD,
     &     JNT,INV,KTJ,KTE )
C
 1000 CONTINUE
C
      CALL NODELM( NELM,NODE,MTJ,JAC,INE,JNE,KTJ,KTE )
C
      CALL OUTPUT( NNOD,NELM,MTJ,JAC,IDM,NMP1,NMP2,MTJ1,MTJ2,
     &     PXY,INE,JNE,JNT,INV,KTJ,KTE,NEDG,IEDG,IBND,KTB,KTC )
C
      STOP
      E N D
