# THIS MAKEFILE IS GENERATED BY MAKEMAKE PROGRAM.
# Typical usage of makemake command is as follows.
#
# DIR | makemake execute-filename
#

cc   = cl /DMSDOS /c
f77  = fl32
link = link

proj = feel
objs = feel.obj basic_libraries.obj StrEq.obj strindex.obj

all : $(proj).exe

$(proj).exe: $(objs)
	$(link) $(objs) $(f77libs) $(gui_libs) -out:$@ $(lflags) \
           $(lnk_debug) $(guiflags)

feel.obj  :   feel.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) feel.c

basic_libraries.obj  :   basic_libraries.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) basic_libraries.c

StrEq.obj  :   StrEq.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) StrEq.c

strindex.obj  :   strindex.c
	$(cc) $(cflags) $(cdefs) $(cvars) $(cdebug) strindex.c

clean :
	-del *.obj
	-del *.exe
