/*
   FEEL p2  MAKE FORTRAN LIBRARY   mk_subdomain_edat
 */

#include <stdio.h>
#include "../feel_def/feel_def.h"
#include "../system/system.h"

#define FNAME "mk_subdomain_edat.f"
void lib_mk_subdomain_edat()
{
   FILE *fp;
   StoreMakefile(FNAME,SYSTEM_LIBRARY);
   if(LIMIT_FILE == 1) return;
   fp = OpenFileToWrite( FNAME );
   F77("      subroutine mk_subdomain_edat(feel,ieg,neg,mats,matnos)\n");
   F77("*-------------------------------------------------------------------\n");
   F77("*  FEEL P2 System Subroutine\n");
   F77("*-------------------------------------------------------------------\n");
   F77("*  Purpose: show input data\n");
   F77("*  \n");
   F77("*  Caution:\n");
   F77("*\n");
   F77("*-------------------------------------------------------------------\n");
   F77("      real*4    feel(*)\n");
   F77("      dimension matnos(*)\n");
   F77("*--------------------------------------------------------------------\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      parameter (MAX_FEEL = 2000000)\n");
   F77("      parameter (MAX_DOMAIN = 10)\n");
   F77("      parameter (MAX_EDATSET = 38)\n");
   F77("      parameter (MAX_NODESET = 20)\n");
   F77("      parameter (MAX_NUMSET = 20)\n");
   F77("      parameter (MAX_EWISE  = 20)\n");
   F77("      parameter (MAX_IP    = 8)\n");
   F77("      parameter (MAX_SOLVE = 11)\n");
   F77("c --------------------------------------------------------------------\n");
   F77("      dimension ipattern(MAX_EDATSET,2)\n");
   F77("c --------------------------------------------------------------------\n");
   common_parameters(fp);
   COM;
   CommonBlock(fp);
   comment1(fp);
   F77("c --------------------------------------------------------------------\n");
   F77("      data    icounter/0/ \n");
   F77("*--------------------------------------------------------------------\n");
   F77("      save    icounter,ipattern\n");
   F77("*--------------------------------------------------------------------\n");
   F77("*      np_push = np_work  OLD F_ALLOC \n");
   F77("      call f_alloc_push\n");
   F77("*--------------------------------------------------------\n");
   F77("      do 1 i=1,icounter\n");
   F77("	if(ipattern(i,1) .eq. ieg   .and.\n");
   F77("     $     ipattern(i,2) .eq. neg         ) return\n");
   F77("1     continue\n");
   F77("*--------------------------------------------------------------------\n");
   F77("      icounter = icounter + 1\n");
   F77("      ipattern(i,1) = ieg\n");
   F77("      ipattern(i,2) = neg\n");
   F77("*--------------------------------------------------------------------\n");
   F77("*--------------------------------------------------------------------\n");
   F77("      if(neg .gt. MAX_EDATSET) then\n");
   F77("        stop 'Error: Required edat no is too big in mk_subdom_edat'\n");
   F77("      endif\n");
   F77("*--------------------------------------------------------\n");
   F77("      neelem = n_edat(ieg,1)\n");
   F77("      nenode = n_edat(ieg,2)\n");
   F77("      call f_alloc(np_ielem,'sub_region',neelem*nenode,0)\n");
   F77("      call f_alloc(np_matno,'sub_region',neelem       ,0)\n");
   F77("      iunit = ieg + io_edat -1\n");
   F77("      call get_ielem(iunit,feel(np_ielem),feel(np_matno),\n");
   F77("     $               neelem,nenode                       )\n");
   F77("*--------------------------------------------------------\n");
   F77("      call sd_count(feel(np_ielem),feel(np_matno),\n");
   F77("     $     neelem,nenode,mats,matnos,neelem_new)\n");
   F77("*--------------------------------------------------------\n");
   F77("      n_edat(neg,1) = neelem_new\n");
   F77("      n_edat(neg,2) = nenode\n");
   F77("*--------------------------------------------------------\n");
   F77("      call f_alloc(np_ielem_new,'sub_reg2',neelem_new*nenode,0)\n");
   F77("      call f_alloc(np_matno_new,'sub_reg2',neelem_new       ,0)\n");
   F77("*--------------------------------------------------------\n");
   F77("      iunit = io_edat + neg -1\n");
   F77("      call sd_wrt_edat(iunit,mats,matnos,\n");
   F77("     $     feel(np_ielem),feel(np_matno),neelem,nenode,\n");
   F77("     $     feel(np_ielem_new),feel(np_matno_new),neelem_new)\n");
   F77("*--------------------------------------------------------\n");
   F77("*      np_work=np_push   OLD F_ALLOC\n");
   F77("      call f_alloc_pop\n");
   F77("      return\n");
   F77("*--------------------------------------------------------\n");
   F77("      end\n");
   F77("      subroutine sd_wrt_edat(iunit,mats,matnos,\n");
   F77("     $                             ielem,matno,neelem,nenode,\n");
   F77("     $                             ielem_n,matno_n,neelem_n )\n");
   F77("*-----------------------------------------------------------\n");
   F77("*     SUB-SUBROUTINE [sd_wrt_edat] make sub region EDAT data\n");
   F77("*     ****************************\n");
   F77("*-----------------------------------------------------------\n");
   F77("      dimension matnos(neelem)\n");
   F77("      dimension ielem(nenode,neelem),    matno  (neelem)\n");
   F77("      dimension ielem_n(nenode,neelem_n),matno_n(neelem_n)\n");
   F77("*-----------------------------------------------------------\n");
   F77("      ino = 0\n");
   F77("      do 100 i=1,mats\n");
   F77("         mno = matnos(i)\n");
   F77("*-----------------------------------------------------------\n");
   F77("         do 200 j=1,neelem\n");
   F77("*\n");
   F77("            if(matno(j).eq.mno) then\n");
   F77("               ino = ino + 1\n");
   F77("*\n");
   F77("               do 300 k=1,nenode\n");
   F77("                  ielem_n(k,ino) = ielem(k,j)\n");
   F77(" 300           continue\n");
   F77("*\n");
   F77("               matno_n(ino) = matno(j)\n");
   F77("            endif\n");
   F77("*\n");
   F77(" 200     continue\n");
   F77(" 100  continue\n");
   F77("*\n");
   F77("*-----------------------------------------------------------\n");
   F77("      if(ino .ne. neelem_n) stop 'Error@sub_region(sd_wrt_edat)'\n");
   F77("*-----------------------------------------------------------\n");
   F77("      open(unit = iunit, status='scratch',form='unformatted')\n");
   F77("*\n");
   F77("      write(iunit) neelem_n,nenode\n");
   F77("      write(iunit) ((ielem_n(i,j),i=1,nenode),j=1,neelem_n)\n");
   F77("      write(iunit) (matno_n(i),i=1,neelem_n)\n");
   F77("*\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine sd_count(ielem,matno,neelem,    nenode,\n");
   F77("     $                    mats,matnos,neelem_new         )\n");
   F77("*----------------------------------------------------------\n");
   F77("*     SUB-SUBROUTINE: [sd_count]   Count subregion elements\n");
   F77("*----------------------------------------------------------\n");
   F77("      dimension ielem(nenode,neelem),matno(neelem)\n");
   F77("      dimension matnos(mats)\n");
   F77("*--------------------------------------------------------\n");
   F77("      neelem_new = 0\n");
   F77("*--------------------------------------------------------\n");
   F77("      do 100 i=1,mats\n");
   F77("*\n");
   F77("         mno = matnos(i)\n");
   F77("*\n");
   F77("         do 101 ii=1,i-1\n");
   F77("            if(mno .eq. matnos(ii)) stop 'matnos ERROR @sub_region'\n");
   F77(" 101     continue\n");
   F77("*\n");
   F77("         do 200 j=1,neelem\n");
   F77("            if(matno(j) .eq. mno) neelem_new = neelem_new + 1\n");
   F77(" 200     continue\n");
   F77("*\n");
   F77(" 100  continue\n");
   F77("      if(neelem_new .eq. 0) stop 'neelem_new=0 error @sub_region(count)'\n");
   F77("     $\n");
   F77("*\n");
   F77("\n");
   F77("*      write(*,*) 'count: mats       ',mats\n");
   F77("*      write(*,*) 'count: matnos(1)  ',matnos(1)\n");
   F77("*      write(*,*) 'count: neelem     ',neelem\n");
   F77("*      write(*,*) 'count: nenode     ',nenode\n");
   F77("*      write(*,*) 'count: neelem_new ',neelem_new\n");
   F77("\n");
   F77("      return\n");
   F77("      end\n");
 CloseFile(fp);
 return;
}
