/*
   FEEL p2  MAKE FORTRAN LIBRARY   sol
 */

#include <stdio.h>
#include "../feel_def/feel_def.h"
#include "../system/system.h"

#define FNAME "sol.f"
void lib_sol()
{
   FILE *fp;
   StoreMakefile(FNAME,SYSTEM_LIBRARY);
   if(LIMIT_FILE == 1) return;
   fp = OpenFileToWrite( FNAME );
   F77("      SUBROUTINE SOL(VKGS,VKGD,VKGI,VFG,KLD,NEQ,MP,IFAC,ISOL,NSYM,ENERG)\n");
   F77("C***********************************************************\n");
   F77("C     SUBROUTINE SOL(VKGS,VKGD,VKGI,VFG,KLD,NEQ,MP,IFAC,ISOL,NSYM,ENERG)\n");
   F77("C\n");
   F77("C                                               sol.f\n");
   F77("C\n");
   F77("C     input      VKGS,VKGD,VKGI\n");
   F77("C                VFG\n");
   F77("C                KLD\n");
   F77("C                NEQ\n");
   F77("C                MP\n");
   F77("C                IFAC\n");
   F77("C                ISOL\n");
   F77("C                NSYM\n");
   F77("C     output     VKGS,VKGI,VKGD\n");
   F77("C                VFG\n");
   F77("C                ENERG\n");
   F77("*\n");
   F77("*\n");
   F77("*\n");
   F77("*\n");
   F77("C************************************************************\n");
   F77("      IMPLICIT REAL*8(A-H,O-Z)\n");
   F77("      DIMENSION VKGS(1),VKGD(1),VKGI(1),VFG(1),KLD(1)\n");
   F77("      DATA ZERO/0.0D0/\n");
   F77("C\n");
   F77("      IK = 1\n");
   F77("      IF( VKGD(1).NE.ZERO ) GOTO 10\n");
   F77("      WRITE( MP,2000 ) IK\n");
   F77("      STOP\n");
   F77(" 10   ENERG = ZERO\n");
   F77("C\n");
   F77("C---\n");
   F77("C\n");
   F77("      JHK = 1\n");
   F77("      DO 100 IK = 2, NEQ\n");
   F77("\n");
   F77("         JHK1 = KLD( IK + 1 )\n");
   F77("\n");
   F77("         LHK = JHK1 - JHK\n");
   F77("         LHK1 = LHK - 1\n");
   F77("C\n");
   F77("         IMIN  = IK - LHK1\n");
   F77("         IMIN1 = IMIN - 1\n");
   F77("C\n");
   F77("         IMAX = IK - 1\n");
   F77("\n");
   F77("         IF( LHK1.LT.0 ) GOTO 100\n");
   F77("         IF( IFAC.NE.1 ) GOTO 90\n");
   F77("         IF( NSYM.EQ.1 ) VKGI( JHK ) = VKGI( JHK ) / VKGD( IMIN1 )\n");
   F77("         IF( LHK1.EQ.0 ) GOTO 40\n");
   F77("C\n");
   F77("C\n");
   F77("         JCK = JHK + 1\n");
   F77("         JHJ = KLD( IMIN )\n");
   F77("C\n");
   F77("         DO 30 IJ = IMIN,IMAX\n");
   F77("            JHJ1 = KLD( IJ + 1 )\n");
   F77("\n");
   F77("            IC = MIN0( JCK - JHK , JHJ1 - JHJ )\n");
   F77("\n");
   F77("            IF( ( IC.LE.0 ).AND.( NSYM.EQ.0 ) ) GOTO 20\n");
   F77("            C1 = ZERO\n");
   F77("            IF( IC.LE.0 ) GOTO 17\n");
   F77("            J1 = JHJ1 - IC\n");
   F77("            J2 = JCK - IC\n");
   F77("            IF( NSYM.EQ.1 ) GOTO 15\n");
   F77("            VKGS(JCK)=VKGS(JCK)-SCAL(VKGS(J1),VKGS(J2),IC)\n");
   F77("            GOTO 20\n");
   F77(" 15         VKGS(JCK)=VKGS(JCK)-SCAL(VKGI(J1),VKGS(J2),IC)\n");
   F77("            C1 = SCAL( VKGS( J1 ), VKGI( J2 ), IC )\n");
   F77(" 17         VKGI( JCK ) = (VKGI(JCK)-C1) / VKGD( IJ )\n");
   F77(" 20         JCK = JCK + 1\n");
   F77(" 30      JHJ = JHJ1\n");
   F77("C\n");
   F77("C\n");
   F77(" 40      JCK = JHK\n");
   F77("         CDIAG = ZERO\n");
   F77("         DO 70 IJ = IMIN1,IMAX\n");
   F77("            C1 = VKGS( JCK )\n");
   F77("            IF( NSYM.EQ.1 ) GOTO 50\n");
   F77("            C2 = C1 / VKGD( IJ )\n");
   F77("            VKGS( JCK ) = C2\n");
   F77("            GOTO 60\n");
   F77("C\n");
   F77(" 50         C2 = VKGI( JCK )\n");
   F77(" 60         CDIAG = CDIAG + C1 * C2\n");
   F77(" 70      JCK = JCK + 1\n");
   F77("         VKGD( IK ) = VKGD( IK ) - CDIAG\n");
   F77("         IF( VKGD( IK ) ) 90,80,90\n");
   F77("C\n");
   F77(" 80      WRITE( MP,2000 ) IK\n");
   F77(" 2000    FORMAT(' *** ERROR,ZERO PIVOT EQUATION ',I5 )\n");
   F77("         STOP\n");
   F77("C\n");
   F77("C\n");
   F77(" 90      IF( ISOL.NE.1 ) GOTO 100\n");
   F77("         IF( NSYM.NE.1 ) VFG( IK ) = VFG( IK ) - SCAL( VKGS( JHK ),\n");
   F77("     $                                  VFG( IMIN1 ) , LHK )\n");
   F77("         IF( NSYM.EQ.1 ) VFG( IK ) = VFG( IK ) - SCAL( VKGI( JHK ),\n");
   F77("     $                                  VFG( IMIN1 ),LHK )\n");
   F77("C\n");
   F77(" 100  JHK = JHK1\n");
   F77("C\n");
   F77("      IF( ISOL.NE.1 ) RETURN\n");
   F77("C\n");
   F77("      IF( NSYM.EQ.1 ) GOTO 120\n");
   F77("      DO 110 IK = 1,NEQ\n");
   F77("         C1 = VKGD( IK )\n");
   F77("         C2 = VFG( IK ) / C1\n");
   F77("         VFG( IK ) = C2\n");
   F77("         ENERG = ENERG + C1 * C2 * C2\n");
   F77(" 110  CONTINUE\n");
   F77("C\n");
   F77("C\n");
   F77(" 120  IK = NEQ + 1\n");
   F77("      JHK1 = KLD( IK )\n");
   F77("C\n");
   F77(" 130  IK = IK - 1\n");
   F77("      IF( NSYM.EQ.1 ) VFG( IK ) = VFG( IK ) / VKGD( IK )\n");
   F77("      IF( IK.EQ.1 ) RETURN\n");
   F77("      C1 = VFG( IK )\n");
   F77("      JHK = KLD( IK )\n");
   F77("      JBK = JHK1 - 1\n");
   F77("      IF( JHK.GT.JBK ) GOTO 150\n");
   F77("      IJ = IK - JBK + JHK - 1\n");
   F77("      DO 140 JCK = JHK,JBK\n");
   F77("         VFG( IJ ) = VFG( IJ ) - VKGS( JCK ) * C1\n");
   F77(" 140     IJ = IJ + 1\n");
   F77("C\n");
   F77(" 150  JHK1 = JHK\n");
   F77("      GOTO 130\n");
   F77("C\n");
   F77("      END\n");
 CloseFile(fp);
 return;
}
