# THIS MAKEFILE IS GENERATED BY MAKEMAKE PROGRAM.
# Typical usage of makemake command is as follows.
#
# DIR | makemake execute-filename
#

cc   = cl
f77  = fl32
link = link

proj = feel.Tri
objs = area.obj bndnod.obj bougen.obj check.obj data.obj decr.obj delaun.obj distor.obj edge.obj fine.obj incr.obj input.obj ipush.obj ivert.obj laplas.obj lawson.obj locate.obj main.obj model.obj neibor.obj pick.obj poly.obj remesh.obj remove.obj renumber.obj rough.obj search.obj subdiv.obj swap.obj theta.obj 

all : $(proj).exe

$(proj).exe: $(objs)
	$(link) $(objs) $(f77libs) $(gui_libs) -out:$@ $(lflags) \
           $(lnk_debug) $(guiflags)

area.obj  :   area.f
	$(f77) $(fflags) area.f /c

bndnod.obj  :   bndnod.f
	$(f77) $(fflags) bndnod.f /c

bougen.obj  :   bougen.f
	$(f77) $(fflags) bougen.f /c

check.obj  :   check.f
	$(f77) $(fflags) check.f /c

data.obj  :   data.f
	$(f77) $(fflags) data.f /c

decr.obj  :   decr.f
	$(f77) $(fflags) decr.f /c

delaun.obj  :   delaun.f
	$(f77) $(fflags) delaun.f /c

distor.obj  :   distor.f
	$(f77) $(fflags) distor.f /c

edge.obj  :   edge.f
	$(f77) $(fflags) edge.f /c

fine.obj  :   fine.f
	$(f77) $(fflags) fine.f /c

incr.obj  :   incr.f
	$(f77) $(fflags) incr.f /c

input.obj  :   input.f
	$(f77) $(fflags) input.f /c

ipush.obj  :   ipush.f
	$(f77) $(fflags) ipush.f /c

ivert.obj  :   ivert.f
	$(f77) $(fflags) ivert.f /c

laplas.obj  :   laplas.f
	$(f77) $(fflags) laplas.f /c

lawson.obj  :   lawson.f
	$(f77) $(fflags) lawson.f /c

locate.obj  :   locate.f
	$(f77) $(fflags) locate.f /c

main.obj  :   main.f
	$(f77) $(fflags) main.f /c

model.obj  :   model.f
	$(f77) $(fflags) model.f /c

neibor.obj  :   neibor.f
	$(f77) $(fflags) neibor.f /c

pick.obj  :   pick.f
	$(f77) $(fflags) pick.f /c

poly.obj  :   poly.f
	$(f77) $(fflags) poly.f /c

remesh.obj  :   remesh.f
	$(f77) $(fflags) remesh.f /c

remove.obj  :   remove.f
	$(f77) $(fflags) remove.f /c

renumber.obj  :   renumber.f
	$(f77) $(fflags) renumber.f /c

rough.obj  :   rough.f
	$(f77) $(fflags) rough.f /c

search.obj  :   search.f
	$(f77) $(fflags) search.f /c

subdiv.obj  :   subdiv.f
	$(f77) $(fflags) subdiv.f /c

swap.obj  :   swap.f
	$(f77) $(fflags) swap.f /c

theta.obj  :   theta.f
	$(f77) $(fflags) theta.f /c


clean :
	-del *.obj
	-del *.exe
