#include <stdio.h>

void lisplib_exp_print( fp )
     FILE *fp;
{
  LISP_SEND(fp,"(defun exp-print (lst)\n");
  LISP_SEND(fp,"  (list-print-x (pre-to-inf (beki-fix lst)) t))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun exp-print-fp (lst fp)\n");
  LISP_SEND(fp,"  (list-print-x (pre-to-inf (beki-fix lst)) fp))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun pre-to-inf (l)\n");
  LISP_SEND(fp,"  (cond ((null l) nil)\n");
  LISP_SEND(fp,"	((atom l)  l )\n");
  LISP_SEND(fp,"	((null (member (car l) '( + - * / ^))) \n");
  LISP_SEND(fp,"	 (cons (car l) (mapcar #'pre-to-inf (cdr l))))\n");
  LISP_SEND(fp,"	(t (pre-to-inf-aux  (mapcar #'pre-to-inf (cdr l)) (car l)))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun pre-to-inf-aux  (lst smbl)\n");
  LISP_SEND(fp,"  (cdr (pre-to-inf-aux2 lst smbl)))\n");
  LISP_SEND(fp,"		 \n");
  LISP_SEND(fp,"(defun pre-to-inf-aux2 ( lst  smbl)\n");
  LISP_SEND(fp,"  (cond ((null lst) nil)\n");
  LISP_SEND(fp,"	(t (append (list smbl (car lst)) (pre-to-inf-aux2 (cdr lst) smbl)))))\n");
  LISP_SEND(fp,"(defun list-print-x (lst FP)\n");
  LISP_SEND(fp,"  (PROGN  (list-print lst FP)(format FP \"~%%\")))\n");
  LISP_SEND(fp,"(defun list-print (lst FP)\n");
  LISP_SEND(fp,"  (cond ((floatp  lst) (FORMAT FP \"~Ad0\"   lst ))\n");
  LISP_SEND(fp,"	((numberp lst) (FORMAT FP \"~A.0d0\" lst ))\n");
  LISP_SEND(fp,"	((atom lst)    (FORMAT FP \"~S\"     lst ))\n");
  LISP_SEND(fp,"	((is-function-exp lst) \n");
  LISP_SEND(fp,"	 (do ((dlst (cdr lst)                    (cdr dlst))\n");
  LISP_SEND(fp,"	      (num       0                       (+ 1 num) )\n");
  LISP_SEND(fp,"	      (func (format fp \"~S(\" (car lst))            ))\n");
  LISP_SEND(fp,"	     ((null dlst) (format fp \")\"))\n");
  LISP_SEND(fp,"	     (progn (cond \n");
  LISP_SEND(fp,"		     ((floatp  (car dlst)) (FORMAT FP \"~Ad0\" (car dlst)))\n");
  LISP_SEND(fp,"		     ((numberp (car dlst)) (FORMAT FP \"~A.0d0\" (car dlst)))\n");
  LISP_SEND(fp,"		     ((atom    (car dlst)) (FORMAT FP \"~A\"   (car dlst)))\n");
  LISP_SEND(fp,"		     (t \n");
  LISP_SEND(fp,"		      (progn (format fp \"(\")\n");
  LISP_SEND(fp,"			     (list-print (car dlst) FP)\n");
  LISP_SEND(fp,"			     (FORMAT FP \")\"))))\n");
  LISP_SEND(fp,"		    (if(eq 0 num) t\n");
  LISP_SEND(fp,"		      (format fp \",\")))))\n");
  LISP_SEND(fp,"	(t\n");
  LISP_SEND(fp,"	 (do ((dlst (FORT77-CONVERT lst) (cdr dlst)))\n");
  LISP_SEND(fp,"	     ((null dlst) t )\n");
  LISP_SEND(fp,"	     (cond \n");
  LISP_SEND(fp,"		   ((floatp  (car dlst)) (FORMAT FP \"~Ad0\" (car dlst)))\n");
  LISP_SEND(fp,"		   ((numberp (car dlst)) (FORMAT FP \"~A.0d0\" (car dlst)))\n");
  LISP_SEND(fp,"		   ((atom    (car dlst)) (FORMAT FP \"~A\" (car dlst)))\n");
  LISP_SEND(fp,"		   (t (progn(FORMAT FP \"(\")\n");
  LISP_SEND(fp,"			    (list-print (car dlst) FP)\n");
  LISP_SEND(fp,"			    (FORMAT FP \")\"))))))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun FORT77-CONVERT (LST)\n");
  LISP_SEND(fp,"  (COND ((EQ LST '^) '**)\n");
  LISP_SEND(fp,"	((ATOM LST ) LST)\n");
  LISP_SEND(fp,"	(T (CONS (FORT77-CONVERT (CAR LST))\n");
  LISP_SEND(fp,"		 (FORT77-CONVERT (CDR LST))))))\n");
  LISP_SEND(fp,"(defun is-function-exp ( lst )\n");
  LISP_SEND(fp,"  (cond ((member '+ lst) nil)\n");
  LISP_SEND(fp,"	((member '- lst) nil)\n");
  LISP_SEND(fp,"	((member '* lst) nil)\n");
  LISP_SEND(fp,"	((member '/ lst) nil)\n");
  LISP_SEND(fp,"	((member '^ lst) nil)\n");
  LISP_SEND(fp,"	((member '** lst) nil)\n");
  LISP_SEND(fp,"	(t t)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun beki-fix ( lst )\n");
  LISP_SEND(fp,"  (cond ((atom lst) lst)\n");
  LISP_SEND(fp,"	((and (eq '^ (car lst)) (integerp (caddr lst)))\n");
  LISP_SEND(fp,"	 (cond ((= 0 (caddr lst))   1)\n");
  LISP_SEND(fp,"	       ((> 0 (caddr lst)) lst)\n");
  LISP_SEND(fp,"	       (t\n");
  LISP_SEND(fp,"		(do* ((expr (list (cadr  lst))          )\n");
  LISP_SEND(fp,"		      (num  (caddr lst)        (- num 1))\n");
  LISP_SEND(fp,"		      (dlst '(* )                       ))\n");
  LISP_SEND(fp,"		     ((= 0 num) dlst )\n");
  LISP_SEND(fp,"		     (setq dlst  (append dlst expr))))))\n");
  LISP_SEND(fp,"	(t (cons (car lst)\n");
  LISP_SEND(fp,"		 (mapcar #'beki-fix (cdr lst))))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"	       \n");
  LISP_SEND(fp,"\n");
}
