#include <stdio.h>

void lisplib_diff( fp )
     FILE *fp;
{
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun diff-fmla (fmla var)\n");
  LISP_SEND(fp,"  (cond \n");
  LISP_SEND(fp,"   ((numberp fmla) 0)                        ; 定数？\n");
  LISP_SEND(fp,"   ((symbolp fmla)                           ; 変数\n");
  LISP_SEND(fp,"    (if (eq fmla var)\n");
  LISP_SEND(fp,"	1                                    ; dx/dx = 1\n");
  LISP_SEND(fp,"      (if(member fmla *fem-funcs*)           ; xの関数の場合\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"	  (if(member fmla *eval-smbl*)       ; シンボルを評価した後微分処理\n");
  LISP_SEND(fp,"	      (diff-fmla (eval fmla) var)\n");
  LISP_SEND(fp,"	    \n");
  LISP_SEND(fp,"	    (case  var                       ; (dx なにがし)の形で出力\n");
  LISP_SEND(fp,"		   (x (list 'dx fmla))\n");
  LISP_SEND(fp,"		   (y (list 'dy fmla))\n");
  LISP_SEND(fp,"		   (z (list 'dz fmla))\n");
  LISP_SEND(fp,"		   (t (format t \"Inner error in fmla\"))))\n");
  LISP_SEND(fp,"	0)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"   (t (case (car fmla)           ; リストの場合\n");
  LISP_SEND(fp,"	    \n");
  LISP_SEND(fp,"	    (+ (cons '+          ; 和の微分法\n");
  LISP_SEND(fp,"		     (mapcar #'(lambda (f) (diff-fmla f var))\n");
  LISP_SEND(fp,"			     (cdr fmla))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"            (- (list '-          ; 差の微分法\n");
  LISP_SEND(fp,"		     (mapcar #'(lambda (f) (diff-fmla f var))\n");
  LISP_SEND(fp,"			     (cdr fmla))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"	    (* (cons '+          ; 積の微分法\n");
  LISP_SEND(fp,"		     (mapcar #'(lambda (fmlas) (cons '* fmlas))\n");
  LISP_SEND(fp,"			     (diff-*-args (cdr fmla) var))))\n");
  LISP_SEND(fp,"	    \n");
  LISP_SEND(fp,"	    (^ (if (numberp (caddr fmla))\n");
  LISP_SEND(fp,"		   (list '*          ; 指数の微分法\n");
  LISP_SEND(fp,"			 (caddr fmla)\n");
  LISP_SEND(fp,"			 (list '^ (cadr fmla) (1- (caddr fmla)))\n");
  LISP_SEND(fp,"			 (diff-fmla (cadr fmla) var)))\n");
  LISP_SEND(fp,"	       (format t \"階乗の微分で指数が数字ではありません。\"))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"                                 ; 指数関数\n");
  LISP_SEND(fp,"	    (exp (list '*  fmla (diff-fmla (cadr fmla) var)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"                                 ; 三角関数\n");
  LISP_SEND(fp,"	    (sin (list '* \n");
  LISP_SEND(fp,"		       (append (list 'cos) (cdr fmla)) \n");
  LISP_SEND(fp,"		       (diff-fmla (cadr fmla) var)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"	    (cos (list '*\n");
  LISP_SEND(fp,"		       (list '- (append '(sin) (cdr fmla)))\n");
  LISP_SEND(fp,"		       (diff-fmla (cadr fmla) var)))\n");
  LISP_SEND(fp,"	    )\n");
  LISP_SEND(fp,"      )\n");
  LISP_SEND(fp,"   )\n");
  LISP_SEND(fp,")\n");
  LISP_SEND(fp,"(defun diff-*-args (fmlas var)\n");
  LISP_SEND(fp,"  (if (null fmlas)\n");
  LISP_SEND(fp,"      nil\n");
  LISP_SEND(fp,"    (cons (cons  (diff-fmla (car fmlas ) var)\n");
  LISP_SEND(fp,"		(cdr fmlas))\n");
  LISP_SEND(fp,"	  (mapcar #'(lambda (fs)\n");
  LISP_SEND(fp,"		      (cons (car fmlas) fs))\n");
  LISP_SEND(fp,"		  (diff-*-args (cdr fmlas) var)))))\n");
  LISP_SEND(fp,"(defun dx (lst)\n");
  LISP_SEND(fp,"  (diff-fmla lst 'x))\n");
  LISP_SEND(fp,"(defun dy (lst)\n");
  LISP_SEND(fp,"  (diff-fmla lst 'y))\n");
  LISP_SEND(fp,"(defun dz (lst)\n");
  LISP_SEND(fp,"  (diff-fmla lst 'z))\n");
  LISP_SEND(fp,"(defun d-formula (lst)\n");
  LISP_SEND(fp,"  (cond ((null lst) nil)\n");
  LISP_SEND(fp,"	((atom lst) lst)\n");
  LISP_SEND(fp,"	((atom (car lst)) (cond \n");
  LISP_SEND(fp,"			   ((eq (car lst) 'dx) (dx (cadr lst)))\n");
  LISP_SEND(fp,"			   ((eq (car lst) 'dy) (dy (cadr lst)))\n");
  LISP_SEND(fp,"			   ((eq (car lst) 'dz) (dz (cadr lst)))\n");
  LISP_SEND(fp,"			   (t (cons(car lst) (mapcar #'d-formula(cdr lst))))))\n");
  LISP_SEND(fp,"	(t (cond ((eq (caar lst) 'dx)\n");
  LISP_SEND(fp,"		  (append (dx (cdar lst))(mapcar #'d-formula (cdr lst))))\n");
  LISP_SEND(fp,"		 ((eq (caar lst) 'dy)\n");
  LISP_SEND(fp,"		  (append (dy (cdar lst))(mapcar #'d-formula (cdr lst))))\n");
  LISP_SEND(fp,"		 ((eq (caar lst) 'dz)\n");
  LISP_SEND(fp,"		  (append (dz (cdar lst))(mapcar #'d-formula (cdr lst))))\n");
  LISP_SEND(fp,"		 (t (cons (car lst) (mapcar #'d-formula (cdr lst))))))))\n");
}
