#include <stdio.h>

void lisplib_diff_fmla_m( fp )
     FILE *fp;
{
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun diff-fmla-m (fmla var)\n");
  LISP_SEND(fp,"  (cond \n");
  LISP_SEND(fp,"   ((numberp fmla) 0)                        ; 定数？\n");
  LISP_SEND(fp,"   ((symbolp fmla)                           ; 変数\n");
  LISP_SEND(fp,"    (if (eq fmla var)\n");
  LISP_SEND(fp,"	1                                    ; dm?/dm? = 1\n");
  LISP_SEND(fp,"	0))                                  ; m?以外は０\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"   (t (case (car fmla)           ; リストの場合\n");
  LISP_SEND(fp,"	    \n");
  LISP_SEND(fp,"	    (+ (cons '+          ; 和の微分法\n");
  LISP_SEND(fp,"		     (mapcar #'(lambda (f) (diff-fmla-m f var))\n");
  LISP_SEND(fp,"			     (cdr fmla))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"            (- (list '-          ; 差の微分法\n");
  LISP_SEND(fp,"		     (mapcar #'(lambda (f) (diff-fmla-m f var))\n");
  LISP_SEND(fp,"			     (cdr fmla))))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"	    (* (cons '+          ; 積の微分法\n");
  LISP_SEND(fp,"		     (mapcar #'(lambda (fmlas) (cons '* fmlas))\n");
  LISP_SEND(fp,"			     (diff-*-args-m (cdr fmla) var))))\n");
  LISP_SEND(fp,"	    \n");
  LISP_SEND(fp,"	    (^ (if (numberp (caddr fmla))\n");
  LISP_SEND(fp,"		   (list '*          ; 指数の微分法\n");
  LISP_SEND(fp,"			 (caddr fmla)\n");
  LISP_SEND(fp,"			 (list '^ (cadr fmla) (1- (caddr fmla)))\n");
  LISP_SEND(fp,"			 (diff-fmla-m (cadr fmla) var))\n");
  LISP_SEND(fp,"	       (format t \"階乗の微分で指数が数字ではありません。\")))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"                                 ; 指数関数\n");
  LISP_SEND(fp,"	    (exp (list '*  fmla (diff-fmla-m (cadr fmla) var)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"                                 ; 指数関数\n");
  LISP_SEND(fp,"	    (dexp (list '*  fmla (diff-fmla-m (cadr fmla) var)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"                                 ; 三角関数\n");
  LISP_SEND(fp,"	    (sin (list '* \n");
  LISP_SEND(fp,"		       (append (list 'cos) (cdr fmla)) \n");
  LISP_SEND(fp,"		       (diff-fmla-m (cadr fmla) var)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"	    (dsin (list '* \n");
  LISP_SEND(fp,"		       (append (list 'dcos) (cdr fmla)) \n");
  LISP_SEND(fp,"		       (diff-fmla-m (cadr fmla) var)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"	    (cos (list '*\n");
  LISP_SEND(fp,"		       (list '- (append '(sin) (cdr fmla)))\n");
  LISP_SEND(fp,"		       (diff-fmla-m (cadr fmla) var)))\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"	    (dcos (list '*\n");
  LISP_SEND(fp,"		       (list '- (append '(dsin) (cdr fmla)))\n");
  LISP_SEND(fp,"		       (diff-fmla-m (cadr fmla) var)))\n");
  LISP_SEND(fp,"	    (dx 0)\n");
  LISP_SEND(fp,"	    (dy 0)\n");
  LISP_SEND(fp,"	    (dz 0)\n");
  LISP_SEND(fp,"	    )\n");
  LISP_SEND(fp,"      )\n");
  LISP_SEND(fp,"   )\n");
  LISP_SEND(fp,")\n");
  LISP_SEND(fp,"(defun diff-*-args-m (fmlas var)\n");
  LISP_SEND(fp,"  (if (null fmlas)\n");
  LISP_SEND(fp,"      nil\n");
  LISP_SEND(fp,"    (cons (cons  (diff-fmla-m (car fmlas ) var)\n");
  LISP_SEND(fp,"		(cdr fmlas))\n");
  LISP_SEND(fp,"	  (mapcar #'(lambda (fs)\n");
  LISP_SEND(fp,"		      (cons (car fmlas) fs))\n");
  LISP_SEND(fp,"		  (diff-*-args-m (cdr fmlas) var)))))\n");
}
