#include <stdio.h>

void lisplib_make_num_integral( fp )
     FILE *fp;
{
  LISP_SEND(fp,"(defun make-num-integral ()\n");
  LISP_SEND(fp,"  (progn\n");
  LISP_SEND(fp,"    (setq *num-integral-term* nil)\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"    (make-fem-term-list *fem-integrand*  )  ; 要素行列項\n");
  LISP_SEND(fp,"    (make-fem-term-list *load-integrand* )  ; 荷重項\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"    (do* ((dim    *dimension* (- dim 1))\n");
  LISP_SEND(fp,"	  (ptr    '(dx dy dz)  (cdr ptr))\n");
  LISP_SEND(fp,"	  )\n");
  LISP_SEND(fp,"	 ((eq 0 dim ) t)\n");
  LISP_SEND(fp,"	 (do ((dlst *shape-funcs* (cdr dlst))\n");
  LISP_SEND(fp,"	      (diff (car ptr)               ))\n");
  LISP_SEND(fp,"	     ((null dlst) t)\n");
  LISP_SEND(fp,"	     (make-fem-term-list (cons diff (list (car dlst))))))\n");
  LISP_SEND(fp,"	     \n");
  LISP_SEND(fp,"    (if(or (member 'x *num-integral-term*)\n");
  LISP_SEND(fp,"	   (member 'y *num-integral-term*)\n");
  LISP_SEND(fp,"	   (member 'z *num-integral-term*))\n");
  LISP_SEND(fp,"	(do (( dlst *shape-funcs* (cdr dlst)) )\n");
  LISP_SEND(fp,"	    ((null dlst) t)\n");
  LISP_SEND(fp,"	    (make-fem-term-list (car dlst))))\n");
  LISP_SEND(fp,"    (make-num-integral-term-main)\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"    )  ;progn の終わり\n");
  LISP_SEND(fp,"  )    ;defun の終わり\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"(defun make-num-integral-nonlinear ()\n");
  LISP_SEND(fp,"  (progn\n");
  LISP_SEND(fp,"    (setq *num-integral-term* nil)\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"    (make-fem-term-list *fem-integrand*  )  ; 要素行列項\n");
  LISP_SEND(fp,"    (make-fem-term-list *fem-weak-eq* )     ; 非線形問題の残差荷重\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"    (do* ((dim    *dimension* (- dim 1))\n");
  LISP_SEND(fp,"	  (ptr    '(dx dy dz)  (cdr ptr))\n");
  LISP_SEND(fp,"	  )\n");
  LISP_SEND(fp,"	 ((eq 0 dim ) t)\n");
  LISP_SEND(fp,"	 (do ((dlst *shape-funcs* (cdr dlst))\n");
  LISP_SEND(fp,"	      (diff (car ptr)               ))\n");
  LISP_SEND(fp,"	     ((null dlst) t)\n");
  LISP_SEND(fp,"	     (make-fem-term-list (cons diff (list (car dlst))))))\n");
  LISP_SEND(fp,"	     \n");
  LISP_SEND(fp,"    (if(or (member 'x *num-integral-term*)\n");
  LISP_SEND(fp,"	   (member 'y *num-integral-term*)\n");
  LISP_SEND(fp,"	   (member 'z *num-integral-term*))\n");
  LISP_SEND(fp,"	(do (( dlst *shape-funcs* (cdr dlst)) )\n");
  LISP_SEND(fp,"	    ((null dlst) t)\n");
  LISP_SEND(fp,"	    (make-fem-term-list (car dlst))))\n");
  LISP_SEND(fp,"    (make-num-integral-term-main)\n");
  LISP_SEND(fp,"\n");
  LISP_SEND(fp,"    )  ;progn の終わり\n");
  LISP_SEND(fp,"  )    ;defun の終わり\n");
  LISP_SEND(fp,"\n");
}
