/*
   FEEL p2  MAKE FORTRAN LIBRARY   report
 */

#include <stdio.h>
#include "../feel_def/feel_def.h"
#include "../system/system.h"

#define FNAME "report.f"
void lib_report()
{
   FILE *fp;
   StoreMakefile(FNAME,SYSTEM_LIBRARY);
   if(LIMIT_FILE == 1) return;
   fp = OpenFileToWrite( FNAME );
   F77("      subroutine report( cha )\n");
   F77("      implicit real*8 (a-h,o-z)\n");
   F77("      character cha*(*)\n");
   F77("      character date*17,getdate*17\n");
   F77("*\n");
   common_parameters(fp);
   COM;
   CommonBlock(fp);
   comment1(fp);
   F77("*\n");
   F77("      data timlog/0.0d0/\n");
   F77("      save timlog\n");
   F77("c\n");
   F77("      tim = erapstime()\n");
   F77("      write(io_out,900) tim ,tim - timlog , cha\n");
   F77("\n");
   F77(" 900  format(1x,f11.3,1x,'   [',f11.3,'] :  ',a)\n");
   F77("      timlog = tim\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine rep_head\n");
   F77("*\n");
   common_parameters(fp);
   COM;
   CommonBlock(fp);
   comment1(fp);
   F77("*\n");
   F77("      write(io_out,800)\n");
   F77(" 800  format('FEEL P2 (Ver 0.00) PROCEDURE REPORT  [NEC Corporation 1993-1997]')\n");
   F77("      date = getdate()\n");
   F77("\n");
   F77("      write(io_out,801) date\n");
   F77(" 801  format('                             START   ',a16)\n");
   F77("\n");
   F77("      \n");
   F77("\n");
   F77("      write(io_out,*)\n");
   F77("      write(io_out,900)\n");
   F77("      write(io_out,910)\n");
   F77("      write(io_out,920)\n");
   F77(" 900  format('   Sum-up         Sub-Proc        Proc STATUS')\n");
   F77(" 910  format('   CPU time       CPU time        REPORT     ')\n");
   F77(" 920  format('-------------   -------------    -----------------------------------')\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine rep_var\n");
   F77("*\n");
   common_parameters(fp);
   COM;
   CommonBlock(fp);
   comment1(fp);
   F77("*    \n");
   F77("* npmax\n");
   F77("      write(io_out,200) npmax\n");
   F77("* xyz\n");
   F77("      write(io_out,201) ndim,np_x,np_fem-1\n");
   F77("* fem\n");
   F77("      if(nvars_fem .eq. 0) then\n");
   F77("         write(io_out,202) \n");
   F77("      else\n");
   F77("         write(io_out,203) nvars_fem,np_fem,np_ewise-1\n");
   F77("      endif\n");
   F77("* ew\n");
   F77("      if(nvars_ewise .eq. 0) then\n");
   F77("         write(io_out,204)\n");
   F77("      else\n");
   F77("         write(io_out,205) nvars_ewise,np_ewise,\n");
   F77("     $                     np_work_get_falloc()-1\n");
   F77("       endif\n");
   F77("      write(io_out,206) (np_work_get_falloc()-1)*2\n");
   F77("*\n");
   F77(" 200  format('                              :  NODES   ',i5)\n");
   F77(" 201  format('                              :  DIMENSION  ',i2,' ',i7,'-',i7)\n");
   F77(" 202  format('                              :  NO FEM   VARIABLE')\n");
   F77(" 203  format('                              :  FEM VARS   ',i2,' ',i7,'-',i7)\n");
   F77(" 204  format('                              :  NO EWISE VARIABLE')\n");
   F77(" 205  format('                              :  EWISE VARS ',i2,' ',i7,'-',i7)\n");
   F77(" 206  format('                              :  SPACE FOR VARS',i7,'bytes')\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine rep_msize(neq,ncof)\n");
   common_parameters(fp);
   COM;
   CommonBlock(fp);
   comment1(fp);
   F77("\n");
   F77("      write(io_out,200) neq\n");
   F77("      write(io_out,210) ncof\n");
   F77("      write(io_out,220) np_work_get_falloc()*4\n");
   F77("\n");
   F77(" 200  format('                              :  NEQ      ',i8)\n");
   F77(" 210  format('                              :  NCOF     ',i8)\n");
   F77(" 220  format('                              :  HEAP MAX ',i8,'(',i9,'bytes)')\n");
   F77("*\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine rep_CG(iter,zansa)\n");
   F77("      real*8 zansa\n");
   common_parameters(fp);
   COM;
   CommonBlock(fp);
   comment1(fp);
   F77("\n");
   F77("      write(io_out,200) iter \n");
   F77("      write(io_out,210) zansa\n");
   F77("\n");
   F77(" 200  format('                              :  ITERATION ',i8)\n");
   F77(" 210  format('                              :  RESIDUAL  ',PE15.7)\n");
   F77("*\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine rep_non(NITER)\n");
   common_parameters(fp);
   COM;
   CommonBlock(fp);
   comment1(fp);
   F77("\n");
   F77("      write(io_out,200) NITER\n");
   F77(" 200  format('                              :  ITERATION',i8)\n");
   F77("*\n");
   F77("      return\n");
   F77("      end\n");
   F77("      subroutine rep_last\n");
   F77("      implicit real*8 (a-h,o-z)\n");
   common_parameters(fp);
   COM;
   CommonBlock(fp);
   comment1(fp);
   F77("      tim  = erapstime()\n");
   F77("      write(io_out,100)\n");
   F77("      write(io_out,110) tim\n");
   F77("      write(io_out,120) max_heap\n");
   F77("      write(io_out,100)\n");
   F77("*\n");
   F77("      close(unit=io_out)\n");
   F77("*\n");
   F77("      return\n");
   F77("*\n");
   F77(" 100  format('====================================================================')\n");
   F77(" 110  format(' FEEL P2 PROCESS TERMINATE    TOTAL CPU TIME  ',F11.3,' seconds')\n");
   F77(" 120  format('                              MAX ARRAY SIZE  ',I11,' words')\n");
   F77("*\n");
   F77("      end\n");
   F77("\n");
   F77("\n");
   F77("\n");
 CloseFile(fp);
 return;
}
