CFLAGS =  $(ADDITIONALCFLAGS)
mesh_bamg_exec.a :mesh_bamg_exec.a(make_MESH_REF_bamg.o) mesh_bamg_exec.a(make_bamg_info.o) mesh_bamg_exec.a(make_boundary_data_bamg.o) mesh_bamg_exec.a(make_feel_data_file_bamg.o) mesh_bamg_exec.a(mesh_bamg_exec.o) mesh_bamg_exec.a(push_boundary_edat_bamg.o) mesh_bamg_exec.a(push_boundary_nset_bamg.o) mesh_bamg_exec.a(push_boundary_plot_data_bamg.o) 
