      subroutine dcond1_1(mypeid,nprocs,
     $     nsetno,nsetnodes,nsetnp,dcon,dinfo,
     $     isumup,myeqfrom,myeqto,neqtotal,
     $     enptr,con,nelem,
     $     x,y,ipf,ipd,npmax,
     $     enptr_ex,con_ex,nelem_ex,
     $     ndno,peno,x_ex,y_ex,ipfex,ipdex,nouter,
     $     iptrcol,indrow,valmat,vfg,neq,ncof
     $ )
*------------------------------------------------------------
* Generated by feelfem Copyright(c) 1999-2001 NEC Corporation
*------------------------------------------------------------
* FEEL P2/DRAMA Program Model
* 2001/11/14 11:11
*----------------------------------------------------
      implicit real*8(a-h,o-z)
*------------------------------------------------------------
*
*
      integer*4 dcon(2,*),dinfo(nsetnp,*)
*
      integer*4 isumup(*)
      integer*4 enptr(2,*),con(2,*)
      real   *8 x(*),y(*)
      integer*4 ipf(*),ipd(*)
*
      integer*4 enptr_ex(2,*),con_ex(2,*)
      integer*4 ndno(*),peno(*)
      real   *8 x_ex(*),y_ex(*)
      integer*4 ipfex(*),ipdex(*)
*------------------------------------------------------------
*
      real*8  valmat(*)
      real*8  vfg(*)
      integer indrow(*)
      integer iptrcol(*)
*
*--------------------
* Confirm nsetnp is 1
*--------------------
      if(nsetnp .NE. 1) then
        write(*,*) 'nsetnp is not 1'
        call abortexit(mypeid,'nsetnp error in dcond')
      endif
*------------------------------------------------------------
      do 100 i=1,nsetnodes
*
       ind = dcon(1,i)
       ipe = dcon(2,i)
*------------------------------------------------------------
* If the Dirichlet node is in my PE region, row and column
* If the Dirichlet node is NOT in my PE region,
* and it relates my region, column
*------------------------------------------------------------
       if(ipe .NE. mypeid) then
        nd = ndsearch_ex2(ind,ipe,ndno,peno,nouter)
        if(nd .LT. 1) goto 100
*
        ieq = 0
        jeq = ipdex(nd)+dinfo(1,i)+isumup(ipe+1)
*
        x_dpt = x_ex(nd)
        y_dpt = y_ex(nd)
*
       else
*
        ieq = ipd(ind)+dinfo(1,i)
        jeq = ieq                +isumup(ipe+1)
*
        x_dpt = x(ind)
        y_dpt = y(ind)
*
       endif
*
       u   = ((x_dpt*x_dpt)*x_dpt)+(y_dpt*y_dpt)
*
*---------------------------
* ieq local  equation number
* jeq global equation number
*---------------------------
*
**********
* row ieq
**********
         if(ieq .eq. 0) goto  150
*
         iptf = iptrcol(ieq  )
         iptt = iptrcol(ieq+1)-1
*
         do 110 j=iptf,iptt
            if(indrow(j) .eq. jeq) then
               valmat(j) = 1.0d0
            else
               valmat(j) = 0.0d0
            endif
 110     continue
         vfg(ieq) = u

***********
* column
***********
 150     continue

**
         if( ieq  .ne. 0) then
*
* Assume non-zero element is symmetric
*
            iptf = iptrcol(ieq  )
            iptt = iptrcol(ieq+1)-1

            do 160 j=iptf,iptt
               irptr = indrow(j)
               if(irptr .LT. myeqfrom .OR. irptr .GT. myeqto) goto 160
               if(irptr .EQ. jeq ) goto 160

               irptr_local = irptr - myeqfrom+1
               if(irptr_local .LT. 1 .OR. irptr_local .GT. neq) then
                  write(*,*) 'irptr_local ERROR ',irptr_local
                  call abortexit(mypeid,'dcond irptr_local error')
               endif

               iptf2 = iptrcol(irptr_local)
               iptt2 = iptrcol(irptr_local+1)-1
               do 165 k=iptf2,iptt2
                  if(indrow(k) .eq. jeq) goto 170
 165           continue
*
               write(*,*) 'cannot find in dcond'
               call abortexit(mypeid,'Cannot find dcond in my region')
*
 170           continue
               vfg(irptr_local)=vfg(irptr_local)-valmat(k)*u
               valmat(k) = 0.0d0
 160        continue

*
* end of my case
*
         else
*
* now search all!!!!!!!!!!!!!
*
            do 200 j=1,neq
               iptf_all = iptrcol(j)
               iptt_all = iptrcol(j+1)-1
               do 210 k=iptf_all,iptt_all
                  if(indrow(k) .eq. jeq ) then
                     vfg(j) = vfg(j) - valmat(k)*u
                     valmat(k) =0.0d0
                     goto 200
                  endif
 210           continue
 200        continue
         endif
*
* end of column
*
 100  continue
*------------------------------------------------------------
      return
      end
