      program feelfem
*------------------------------------------------------------
* Generated by feelfem Copyright(c) 1999-2001 NEC Corporation
*------------------------------------------------------------
* FEEL P2/DRAMA Program Model
* 2001/11/14 11:11
*----------------------------------------------------
      implicit real*8(a-h,o-z)
*------------------------------------------------------------
      include'mpif.h'
*------------------------------------------------------------
      parameter (MAX_FEEL = 10000000)
      parameter (MAX_PROC = 256)
*------------------------------------------------------------
      real*4     feel(MAX_FEEL)
      real*8    dfeel
      integer*4  myrank,nprocs
      integer*4  ndim
      integer*4  npmax_g,nelem_g,nedat_g,nnset_g,nnum_g,nip_g
*
      equivalence (feel,dfeel)
*------------------------------------------------------------
      call f_alloc_init(MAX_FEEL)
*
      call mpi_init(ierr)
      call mpi_comm_size(mpi_comm_world,nprocs,ierr)
      call mpi_comm_rank(mpi_comm_world,myrank,ierr)
*------------------------------------------------------------
      if(myrank.eq.0) call preportinit(1)
*
*----------------
* MESH DATA READ 
*----------------
      if(myrank.eq.0) then
       call preport('INITIALIZATION')
*
*---
       call datinp(feel,
     $      ndim,npmax_g,nelem_g,nedat_g,nnset_g,nnum_g,nip_g,
     $      np_x_g,np_y_g,np_z_g,np_ip_g,
     $      nvars_fem,nvars_ewise,netype,20000412)
*
       call preportmodule('DATINP ')
*
*---
       call read_solv(feel,medatno,nredat,nbedat,nsolvs,
     $                np_redatlst,np_bedatlst          )
*
       call preportmodule('READ solv_dat')
*
*---
       call f_alloc(np_metis,'element group array',nelem_g,0,0)
*
       call f_alloc_push
       call f_alloc(np_tmp,'tmp array',nelem_g,0,0)
       call read_metis(feel(np_metis),feel(np_tmp),nelem_g,ndiv)
       call f_alloc_pop
*
       call preportmodule('READ_METIS')
*
*---
       call f_alloc(np_redatctr,'redatctr',nredat*5,0,0)
       call get_edat_lst(feel,nredat,feel(np_redatlst),
     $                               feel(np_redatctr) )
*
*---
       if(nbedat .ne. 0) then
         call f_alloc(np_inbctr,'inbctr',nbedat*5,0,0)
         call get_edat_lst(feel,nbedat,feel(np_bedatlst),
     $                     feel(np_inbctr)               )
       else
         np_inbctr = 1
       endif
*
*---
       nbnset = nnset_g
       if(nbnset .NE. 0) then
        call f_alloc(np_idbctr,'idbctr',nbnset*4,0,0)
        call get_bnset(feel,nbnset,feel(np_idbctr))
       else
        np_idbctr = 1
       endif
*
*---
       nwords = np_work_get_falloc()
*
      endif
*--------------------------------------
* Fundamental data syncronization
*--------------------------------------
*
      call pgetparam30(myrank,nprocs,
     $ 27,
     $ ndim       ,npmax_g    ,nelem_g ,nedat_g,nnset_g ,nnum_g   ,
     $ nip_g      ,np_x_g     ,np_y_g  ,np_z_g ,np_ip_g ,nvars_fem,
     $ nvars_ewise,netype     ,medatno ,nredat ,nbedat  ,nsolvs   ,
     $ np_redatlst,np_bedatlst,np_metis,ndiv,np_redatctr,np_inbctr,
     $ nbnset     ,np_idbctr  ,nwords  ,idum1  ,idum2   ,idum3     )
*
      if(ndiv .NE. nprocs) then
        call abortexit(myrank,'NPROC .NE. METIS division')
      endif
*
*----------------------
* Syncronize the memory
*----------------------
      call feelbcast(myrank,nprocs,feel,1,nwords-1)
      if(myrank.ne.0) then
       call np_work_set_falloc(nwords)
      endif
*
      if(myrank.eq.0) call preportmodule('INITIAL DISTRIBUTE')
*
*---------------------------------------------------
*  MAKE DRAMA double index data in every PE
*  STEP 1: LONUMERATE   Local node number generation
*          mynode,myelem,loc(2,*) array calculated
*---------------------------------------------------
      call f_alloc(np_loc,'local indices',npmax_g*2,0,0)
      call lonumerate_lst(feel,myrank   ,nprocs ,
     $                    feel(np_loc)  ,npmax_g,
     $                    feel(np_metis),nelem_g,
     $                    nredat,feel(np_redatctr),
     $                    mynode,myelem            )
*
      if(myrank.eq.0) call preportmodule('LONUMERATE_LST')
*
*-------------------------------------------------------
*  MAKE DRAMA double index data in every PE
*  STEP 2: MKLOCCOOR    Make local node coordinate array
*          xloc(*),yloc(*) Generated
*-------------------------------------------------------
      call f_alloc(np_xloc,    'local x coordinate',mynode,1,0)
      call f_alloc(np_yloc,    'local y coordinate',mynode,1,0)
      call mkloccoor(myrank,nprocs,
     $               feel(np_x_g),feel(np_y_g),feel(np_loc),npmax_g,
     $               feel(np_xloc),feel(np_yloc)       ,mynode  )
*
      if(myrank.eq.0) call preportmodule('MKLOCCOOR')
*
*-------------------------------------------------------
*  MAKE DRAMA double index data in every PE
*  STEP 3: Make REGIONAL LOCAL EDAT SET(ENPTR,CON)
*          myelem is fixed
*          enptrlst(*),matnolst(*),conlst(*) generated
*-------------------------------------------------------
      call f_alloc(np_redatinfo,'(redatinfo)',nredat*3,0,0)
      call f_alloc(np_enptrlst,'(Enptr lst)',nredat,0,0)
      call f_alloc(np_matnolst,'(Matno lst)',nredat,0,0)
      call f_alloc(np_conlst,  '(Con   lst)',nredat,0,0)
*
      call mklocredats(feel,myrank,nprocs,
     $                 feel(np_loc),npmax_g,
     $                 feel(np_metis),nelem_g,
     $                 myelem,
     $                 nredat,feel(np_redatctr),
     $                 feel(np_redatinfo),
     $                 feel(np_enptrlst),feel(np_matnolst),
     $                 feel(np_conlst))
*
      if(myrank.eq.0) call preportmodule('MKLOCREDATS')
*
*-------------------------------------------------------
*  MAKE DRAMA double index data in every PE
*  STEP 4: Make BOUNDARY EDAT SET(ENPTR,CON)
*          This is GLOBALLY gather/scattered data
*          inbctr2(5,*) Generated
*-------------------------------------------------------
      if(nbedat .NE. 0) then
*
       call f_alloc(np_inbctr2,'inbctr2',nbedat*5,0,0)
       call mkglobalbedats(feel,myrank,nprocs,
     $                     feel(np_loc),npmax_g,
     $             nbedat, feel(np_inbctr),feel(np_inbctr2))
*
      else
       np_inbctr2 = 1
      endif
*
      if(myrank.eq.0) call preportmodule('MKGLOBALBEDATS')
*
*-------------------------------------------------------
*  MAKE DRAMA double index data in every PE
*  STEP 5: Make BOUNDARY NSET SET
*          This is GLOBALLY gather/scattered data
*          idbctr2(5,*) generated
*-------------------------------------------------------
      if(nbnset .NE. 0) then
        call f_alloc(np_idbctr2,'idbctr2',nbnset*5,0,0)
        call mkglobalbnsets(feel,myrank,nprocs,
     $                      feel(np_loc),npmax_g,
     $              nbnset, feel(np_idbctr),feel(np_idbctr2))
*
      else
        np_idbctr2 = 1
      endif
*
      if(myrank.eq.0) call preportmodule('MKGLOBALBNSETS')
*
*-------------------------------------------------------
*  MAKE DRAMA double index data in every PE
*  STEP 6: Memory Move
*-------------------------------------------------------
      call pmeminitloc(feel,myrank,nprocs,
     $ mynode,np_xloc,np_yloc,feel(np_xloc),feel(np_yloc),
     $ nredat,myelem,
     $ np_redatinfo,np_enptrlst,np_matnolst,np_conlst,
     $ feel(np_redatinfo),
     $ feel(np_enptrlst),feel(np_matnolst),feel(np_conlst),
     $ nbedat,np_inbctr2,feel(np_inbctr2),
     $ nbnset,np_idbctr2,feel(np_idbctr2) )
*
      if(myrank.eq.0) call preportmodule('PMEMINITLOC')
*******************************************************
*** This is temporary func for DoMainRoutineSchemeStart
*******************************************************
********************************************************
*** This is temporary func for DoMainRoutineSchemeFinish
********************************************************
*------------------------------------------------------------
      call preportallmem(myrank,nprocs)
      if(myrank.eq.0) call preportfini
*
      call mpi_finalize(ierr)
*
      end
