CFLAGS =  $(ADDITIONALCFLAGS)
var_comp.a :var_comp.a(ewise_info.o) var_comp.a(get_elem_name_by_ND.o) var_comp.a(get_fem_var_freedom_by_ND.o) var_comp.a(is_number_string.o) var_comp.a(modulef_var_ctrl.o) var_comp.a(var_comp.o) var_comp.a(var_init.o) 
