C*********************************************************************
C
C     MODIFICATION OF TRIANGLES TO QUADRILATERALS          main.f
C
C*********************************************************************
      PROGRAM QUAD
C
      IMPLICIT REAL*8( A-H,O-Z )
C
      PARAMETER( KTJ = 20000 )
      PARAMETER( KTE = 20000 )
      PARAMETER( KTB = 100 )
      PARAMETER( KTC = 500 )
C
      DIMENSION PX( KTJ ),PY( KTJ ),MTJ( KTE,9 ),JAC( KTE,4 )
      DIMENSION IDM( KTE ),IFIX( KTJ ),KV( KTE )
      DIMENSION ID( KTE ),MAP( KTE ),MMTJ( KTE,4 ),IDMM( KTE )
      DIMENSION JNT( KTJ ),IEDG( KTB,6 ),IBND( KTB,KTC )
C
      CALL INPUT( NODE,NELM,MTJ,JAC,IDM,IFIX,PX,PY,KTJ,KTE,
     &     NEDG,IEDG,KTB )
C
      CALL EXELM( NODE,NELM,MTJ,JAC,KV,IDM,MAP,PX,PY,KTJ,KTE )
C
      CALL ISOGEN( NODE,NELM,MTJ,JAC,PX,PY,ID,MMTJ,IFIX,
     &     IDM,IDMM,KTJ,KTE )
C
      CALL RENUM4( NODE,NELM,MMTJ,PX,PY,IFIX,JNT,KTJ,KTE )
C
      CALL RMKJAC( NODE,NELM,MMTJ,JAC,MTJ,KTE )
C
      CALL BNDNOD( NODE,NELM,MMTJ,JAC,IDMM,JNT,
     &     IEDG,IBND,KTJ,KTE,KTB,KTC,NEDG,MTJ )
C
      CALL LAPLAS( NODE,NELM,MMTJ,PX,PY,IFIX,KTJ,KTE )
C
      CALL OUTPUT( NODE,NELM,MMTJ,JAC,IDMM,PX,PY,IFIX,
     &     IEDG,IBND,KTJ,KTE,KTB,KTC,NEDG)
C
      STOP
      E N D
