feel.Qua.exe: area.o bndnod.o delete.o edge.o exelm.o input.o isogen.o laplas.o main.o output.o renum4.o rmkjac.o square.o
	f77 -o feel.Qua.exe area.o bndnod.o delete.o edge.o exelm.o input.o isogen.o laplas.o main.o output.o renum4.o rmkjac.o square.o
