# THIS MAKEFILE IS GENERATED BY MAKEMAKE PROGRAM.
# Typical usage of makemake command is as follows.
#
# DIR | makemake execute-filename
#

cc   = cl
f77  = fl32
link = link

proj = feel.Qua
objs = area.obj bndnod.obj delete.obj edge.obj exelm.obj input.obj isogen.obj laplas.obj main.obj output.obj renum4.obj rmkjac.obj square.obj 

all : $(proj).exe

$(proj).exe: $(objs)
	$(link) $(objs) $(f77libs) $(gui_libs) -out:$@ $(lflags) \
           $(lnk_debug) $(guiflags)

area.obj  :   area.f
	$(f77) $(fflags) area.f /c

bndnod.obj  :   bndnod.f
	$(f77) $(fflags) bndnod.f /c

delete.obj  :   delete.f
	$(f77) $(fflags) delete.f /c

edge.obj  :   edge.f
	$(f77) $(fflags) edge.f /c

exelm.obj  :   exelm.f
	$(f77) $(fflags) exelm.f /c

input.obj  :   input.f
	$(f77) $(fflags) input.f /c

isogen.obj  :   isogen.f
	$(f77) $(fflags) isogen.f /c

laplas.obj  :   laplas.f
	$(f77) $(fflags) laplas.f /c

main.obj  :   main.f
	$(f77) $(fflags) main.f /c

output.obj  :   output.f
	$(f77) $(fflags) output.f /c

renum4.obj  :   renum4.f
	$(f77) $(fflags) renum4.f /c

rmkjac.obj  :   rmkjac.f
	$(f77) $(fflags) rmkjac.f /c

square.obj  :   square.f
	$(f77) $(fflags) square.f /c


clean :
	-del *.obj
	-del *.exe
