CFLAGS = $(ADDITIONALCFLAGS)
solve_fort77.a :solve_fort77.a(mf_make_solve_ctrl77.o) solve_fort77.a(mf_make_solve_fort77.o) solve_fort77.a(mf_mk_dobper.o) solve_fort77.a(mf_mk_elem_pr.o) solve_fort77.a(mf_mk_milieu.o) solve_fort77.a(mf_mk_pnraid.o) solve_fort77.a(mf_mk_solve_maco.o) solve_fort77.a(mf_mk_solve_mili.o) solve_fort77.a(mf_mk_solve_tae.o) 
